-- ============================================================
-- ENGLISH (UK)
-- ============================================================

-- ======== VOORBEELDEN (EN) ========
INSERT INTO examples (locale, channel, sender, subject, body, annotations, sort_order) VALUES
('en', 'email',
 'Barclays Service <service@barclays-secure-login.com>',
 'Important: your account will be blocked',
 E'Dear customer,\n\nWe have noticed a suspicious transaction on your account. Your account will be BLOCKED within 24 hours unless you confirm your details.\n\nClick here to secure your account: http://barclays-secure-login.com/verify\n\nKind regards,\nBarclays Security Team',
 '[{"quote": "service@barclays-secure-login.com", "note": "Look at what comes AFTER the @: barclays-secure-login.com. That is not Barclays. Real Barclays always uses @barclays.co.uk. The part BEFORE the @ (\"service\") can be anything the scammer wants."}, {"quote": "BLOCKED within 24 hours unless you confirm your details", "note": "Creating fear and urgency. A real bank never does this."}, {"quote": "Dear customer", "note": "No name. Your bank knows your name."}, {"quote": "http://barclays-secure-login.com/verify", "note": "Odd link that is not from Barclays. Do not click!"}]'::jsonb,
 10),

('en', 'email',
 'HMRC <noreply@hmrc-refund.co.uk>',
 'You are entitled to a £423.50 tax refund',
 E'Dear taxpayer,\n\nAfter a review, you are entitled to a tax refund of £423.50. Please fill in your details quickly to receive the amount.\n\nClick here: http://hmrc-refund.co.uk/claim\n\nHMRC',
 '[{"quote": "noreply@hmrc-refund.co.uk", "note": "Look after the @: hmrc-refund.co.uk. That is NOT HMRC. The real HMRC domain is hmrc.gov.uk."}, {"quote": "Dear taxpayer", "note": "Generic greeting without your name. HMRC addresses you by name."}, {"quote": "entitled to a tax refund of £423.50", "note": "A promise of money is a classic bait. HMRC never emails to announce refunds with a link."}, {"quote": "http://hmrc-refund.co.uk/claim", "note": "Odd link, not gov.uk. Do not click."}]'::jsonb,
 20),

('en', 'email',
 'NHS login <info@nhs-verify.org>',
 'Please confirm your NHS login details',
 E'Dear Sir/Madam,\n\nWe kindly ask you to confirm your NHS login details. Click the link below and sign in with your username and password.\n\nhttp://nhs-verify.org/signin\n\nThank you,\nNHS Digital',
 '[{"quote": "info@nhs-verify.org", "note": "Look after the @: nhs-verify.org. The real domain is nhs.uk — nothing else."}, {"quote": "Dear Sir/Madam", "note": "Generic greeting. A real organisation knows your name."}, {"quote": "sign in with your username and password", "note": "The NHS NEVER asks for your password by email. Always phishing."}, {"quote": "http://nhs-verify.org/signin", "note": "Odd link. Only open NHS services via nhs.uk or the official NHS app."}]'::jsonb,
 30);

-- ======== INBOX (EN) ========
INSERT INTO inbox_messages
  (locale, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- 1. PHISHING — Barclays
('en',
 'Barclays Bank',
 'service@barclays-secure-login.com',
 'Look after the @: barclays-secure-login.com. Real Barclays always uses @barclays.co.uk.',
 'today 08:42',
 'Important: your account will be blocked',
 'Dear customer, we have noticed a suspicious transaction on your...',
 E'<div class="eml fam-bank" style="--brand:#00aeef;--cta:#00aeef;--logo:#0088ba"><div class="eml-top"><span class="eml-logo">BARCLAYS</span></div><div class="eml-body"><p>Dear customer,</p><p>We have noticed a suspicious transaction on your account. To prevent misuse, your account will be BLOCKED within 24 hours unless you confirm your details.</p><p>Confirm straight away via {{link:0}}.</p><p>Kind regards,<br>Barclays Security Team</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 BARCLAYS</p></div></div>',
 '[{"label":"this secure page","real_url":"http://barclays-secure-login.com/verify","suspicious":true,"warning":"This link does NOT go to barclays.co.uk but to barclays-secure-login.com. That is a fake site dressed up to look like Barclays."}]'::jsonb,
 TRUE,
 '["Sender address does not end in @barclays.co.uk","Threatens a block within 24 hours — manufactured panic","Greeting is \"Dear customer\" without your name","Link goes to barclays-secure-login.com, not barclays.co.uk"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Barclays never emails you to confirm your details under time pressure. If in doubt, open the Barclays app yourself or call the number on the back of your bank card.',
 10),

-- 2. REAL — GP surgery
('en',
 'Oakwood Surgery',
 'reception@oakwoodsurgery.nhs.uk',
 'The address ends in the surgery''s own domain — normal.',
 'today 09:15',
 'Reminder: your appointment tomorrow at 10:15',
 'Dear Ms Smith, this is a reminder of your appointment with Dr...',
 E'Dear Ms Smith,\n\nThis is a reminder of your appointment with Dr Patel tomorrow at 10:15.\n\nTo cancel or rearrange, please call 020 7946 0123.\n\nSee you tomorrow.\n\nOakwood Surgery\n12 High Street, London',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Personal greeting with your name","No link, no button","A phone number you can call yourself","No request for details or money","Concrete, expected information"]'::jsonb,
 'This is an ordinary appointment reminder. No links, no details requested — you can just phone if you want to change anything.',
 20),

-- 3. PHISHING — HMRC
('en',
 'HMRC',
 'noreply@hmrc-refund.co.uk',
 'Not @hmrc.gov.uk — so not really from HMRC, even though the name appears.',
 'today 10:03',
 'You are entitled to a £423.50 tax refund',
 'After a review, you are entitled to a tax refund...',
 E'<div class="eml fam-gov" style="--brand:#008476;--cta:#008476"><div class="eml-top"><span class="eml-logo">HM Revenue &amp; Customs</span></div><div class="eml-body"><p>Dear taxpayer,</p><p>After a review, you are entitled to a tax refund of £423.50.</p><p>Fill in your details to receive the amount within 3 working days: {{link:0}}.</p><p>HMRC</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 HM Revenue &amp; Customs</p></div></div>',
 '[{"label":"HMRC online","real_url":"http://hmrc-refund.co.uk/claim","suspicious":true,"warning":"The real domain is hmrc.gov.uk. This link goes to hmrc-refund.co.uk — a fake site."}]'::jsonb,
 TRUE,
 '["Sender is @hmrc-refund.co.uk, not @hmrc.gov.uk","HMRC NEVER emails about refunds","Promises money to bait a click","Link goes to an unknown website"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. HMRC communicates about refunds through your Personal Tax Account on gov.uk or by post — never by email with a link. If in doubt, sign in to gov.uk yourself.',
 30),

-- 4. PHISHING — Royal Mail
('en',
 'Royal Mail Tracking',
 'track@royal-mail-delivery.info',
 'The real domain is royalmail.com. ".info" is often suspicious.',
 'yesterday 16:48',
 'Your parcel could not be delivered',
 'Your parcel is waiting for you. There is an outstanding customs fee...',
 E'<div class="eml fam-parcel" style="--brand:#de1212;--cta:#de1212"><div class="eml-hero"><span class="eml-logo">Royal Mail</span></div><div class="eml-body"><p>Dear customer,</p><p>Your parcel is waiting at the depot. There is an outstanding customs fee (£1.95).</p><p>Pay now to avoid a delay: {{link:0}}</p><p>Royal Mail</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 Royal Mail</p></div></div>',
 '[{"label":"royal-mail-delivery.info/pay","real_url":"http://royal-mail-delivery.info/pay","suspicious":true,"warning":"The real address for Royal Mail is royalmail.com. \".info\" domains are widely used for scams."}]'::jsonb,
 TRUE,
 '["Small amount (£1.95) so you pay without thinking","Sender @royal-mail-delivery.info instead of @royalmail.com","\"Pay now\" — time pressure","No name, generic greeting"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Royal Mail never asks for customs fees by email. Expecting a parcel? Check using the official Royal Mail app or via royalmail.com.',
 40),

-- 5. REAL — Library
('en',
 'Camden Libraries',
 'libraries@camden.gov.uk',
 'Official Camden Council domain — correct.',
 'yesterday 11:22',
 'Your borrowed book is due back',
 'Dear Ms Smith, this is a reminder that your book...',
 E'Dear Ms Smith,\n\nThis is a reminder that the book "Wolf Hall" must be returned to a Camden library branch by Friday 28 April at the latest.\n\nAny questions? Call 020 7974 4001 or drop in.\n\nKind regards,\nCamden Libraries',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Personal greeting","Concrete information about your book and date","No link, no payment","A phone number you can call yourself"]'::jsonb,
 'This is a genuine reminder from your library. No danger.',
 50),

-- 6. PHISHING — Gov.uk Verify
('en',
 'GOV.UK Verify',
 'info@gov-uk-verify.org',
 'The real domain is gov.uk. ".org" on Gov.uk is suspicious.',
 '2 days ago 14:30',
 'Please re-confirm your Gov.uk details',
 'Dear Sir/Madam, we kindly ask you to re-confirm your Gov.uk...',
 E'<div class="eml fam-gov" style="--brand:#0b0c0c;--cta:#0b0c0c"><div class="eml-top"><span class="eml-logo">GOV.UK</span></div><div class="eml-body"><p>Dear Sir/Madam,</p><p>For a security check, we ask you to re-confirm your Gov.uk details.</p><p>Sign in via {{link:0}} and enter your username and password.</p><p>Thank you,<br>GOV.UK</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 GOV.UK</p></div></div>',
 '[{"label":"this secure page","real_url":"http://gov-uk-verify.org/signin","suspicious":true,"warning":"Gov.uk NEVER asks for your password by email. The real domain is gov.uk — not gov-uk-verify.org."}]'::jsonb,
 TRUE,
 '["Sender @gov-uk-verify.org — not @gov.uk","Asks for both username AND password (Gov.uk NEVER does that)","Generic \"Dear Sir/Madam\" greeting","Link to an unknown .org address"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Gov.uk never emails a link asking you to confirm your password. Only sign in via gov.uk directly.',
 60),

-- 7. REAL — BT invoice
('en',
 'BT',
 'no-reply@bt.com',
 'Sender @bt.com is the official domain — correct.',
 '3 days ago',
 'Your April bill is ready',
 'Dear customer, your bill of £49.95 is ready in MyBT...',
 E'<div class="eml fam-tech" style="--brand:#5514b4;--cta:#5514b4"><div class="eml-top"><span class="eml-logo">BT</span></div><div class="eml-body"><p>Dear Ms Smith,</p><p>Your BT bill of £49.95 for April is ready in MyBT.</p><p>You can view the bill by signing in yourself at bt.com/mybt (type the address in your browser yourself or use the MyBT app).</p><p>The amount will be taken automatically on 1 May.</p><p>BT Customer Service</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 BT</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Sender is @bt.com (real)","Personal greeting","The amount and date match your contract","No clickable link — you are asked to sign in YOURSELF","Expected monthly bill"]'::jsonb,
 'This is a real BT bill notice. Even with genuine messages, it is safer NOT to click links but to go to the site or app yourself.',
 70),

-- 8. PHISHING — Microsoft
('en',
 'Microsoft',
 'support@microsoft-security-check.com',
 'The real Microsoft domain is microsoft.com, not microsoft-security-check.com.',
 '4 days ago',
 'Warning: your account has been blocked',
 'Your Microsoft account has been blocked due to suspicious activity...',
 E'<div class="eml fam-tech" style="--brand:#0067b8;--cta:#0067b8"><div class="eml-top"><span class="eml-logo">Microsoft</span></div><div class="eml-body"><p>Dear user,</p><p>Your Microsoft account has been temporarily blocked due to suspicious sign-in attempts from Russia.</p><p>If you do not unlock your account within 12 hours, you will lose all your files.</p><p>Unlock your account: {{link:0}}</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 Microsoft</p></div></div>',
 '[{"label":"Unlock account","real_url":"http://microsoft-security-check.com/unlock","suspicious":true,"warning":"Microsoft never uses domains with dashes like microsoft-security-check.com. This is fake."}]'::jsonb,
 TRUE,
 '["Panic: \"you will lose all your files\"","Odd sender, not @microsoft.com","Threat about sign-in from another country","Countdown (12 hours) to rush you"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Microsoft never calls or emails you out of the blue about blocked accounts. Ignore it and sign in yourself at account.microsoft.com to check.',
 80),

-- 9. REAL — Pharmacy
('en',
 'Boots Pharmacy',
 'pharmacy@boots.co.uk',
 'Boots'' own domain — correct.',
 '5 days ago',
 'Your prescription is ready to collect',
 'Your prescription is ready at Boots Pharmacy. You can collect it...',
 E'Dear Ms Smith,\n\nYour prescription is ready to collect at Boots Pharmacy, 12 High Street.\n\nWe are open today until 17:30. Please bring your ID or collection slip.\n\nAny questions? Call 020 7946 0555.\n\nBoots Pharmacy',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Personal greeting","Known pharmacy, own domain","Concrete information: address and opening hours","No link, no payment","A phone number you can call yourself"]'::jsonb,
 'This is a normal message from your pharmacy. No danger.',
 90),

-- 10. PHISHING — Amazon prize
('en',
 'Amazon',
 'prize@amazon-prize-draw.net',
 'Real Amazon emails come from @amazon.co.uk, not from @amazon-prize-draw.net.',
 '6 days ago',
 'Congratulations! You have won an iPhone 15',
 'You are our lucky winner! Claim your prize within 2 hours...',
 E'<div class="eml fam-retail" style="--brand:#232f3e;--cta:#232f3e"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">amazon</span></div><div class="eml-body"><p>Dear customer,</p><p>Congratulations! You have been drawn from thousands of entrants as the winner of a brand-new iPhone 15.</p><p>Claim your prize within 2 hours by paying a small postage fee: {{link:0}}</p><p>Amazon Prize Draw Team</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 amazon</p></div></div>',
 '[{"label":"Claim your prize","real_url":"http://amazon-prize-draw.net/claim","suspicious":true,"warning":"Amazon only ever uses amazon.co.uk. A \"postage fee\" for a prize you won is always a scam."}]'::jsonb,
 TRUE,
 '["You never entered a prize draw","Asks for a \"postage fee\" — real prizes are never sent against payment","Urgency: \"within 2 hours\"","Sender @amazon-prize-draw.net instead of @amazon.co.uk"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. You cannot win a prize you never entered. A real prize draw never asks you to pay a fee upfront.',
 100);


