-- ============================================================
-- FRANÇAIS (FR)
-- ============================================================

-- ======== VOORBEELDEN (FR) ========
INSERT INTO examples (locale, channel, sender, subject, body, annotations, sort_order) VALUES
('fr', 'email',
 'Crédit Agricole <service@credit-agricole-securite.com>',
 'Important : votre compte va être bloqué',
 E'Cher client,\n\nNous avons détecté une transaction suspecte sur votre compte. Votre compte sera BLOQUÉ sous 24 heures si vous ne confirmez pas vos informations.\n\nCliquez ici pour sécuriser votre compte : http://credit-agricole-securite.com/verifier\n\nCordialement,\nService Sécurité Crédit Agricole',
 '[{"quote": "service@credit-agricole-securite.com", "note": "Regardez ce qui vient APRÈS le @ : credit-agricole-securite.com. Ce n''est pas le Crédit Agricole. Le vrai Crédit Agricole utilise toujours @credit-agricole.fr. Ce qui est AVANT le @ (« service ») peut être choisi par l''escroc."}, {"quote": "BLOQUÉ sous 24 heures si vous ne confirmez pas vos informations", "note": "On vous fait peur et on vous presse. Une vraie banque ne fait jamais cela."}, {"quote": "Cher client", "note": "Pas de nom. Votre banque connaît votre nom."}, {"quote": "http://credit-agricole-securite.com/verifier", "note": "Lien étrange qui n''est pas du Crédit Agricole. Ne cliquez pas !"}]'::jsonb,
 10),

('fr', 'email',
 'Impôts <noreply@impots-remboursement.fr>',
 'Vous avez droit à un remboursement de 423,50 €',
 E'Cher contribuable,\n\nAprès vérification, vous avez droit à un remboursement d''impôts de 423,50 €. Remplissez vite vos informations pour recevoir le montant.\n\nCliquez ici : http://impots-remboursement.fr/reclamer\n\nDirection Générale des Finances Publiques',
 '[{"quote": "noreply@impots-remboursement.fr", "note": "Regardez après le @ : impots-remboursement.fr. Ce n''est PAS la DGFiP. Le vrai domaine est dgfip.finances.gouv.fr."}, {"quote": "Cher contribuable", "note": "Salutation générique sans votre nom. La DGFiP connaît votre identité."}, {"quote": "droit à un remboursement d''impôts de 423,50 €", "note": "La promesse d''argent est un appât classique. Les impôts ne communiquent jamais un remboursement par e-mail avec un lien."}, {"quote": "http://impots-remboursement.fr/reclamer", "note": "Lien étrange, ce n''est pas impots.gouv.fr. Ne cliquez pas."}]'::jsonb,
 20),

('fr', 'email',
 'Ameli <info@ameli-controle.org>',
 'Confirmez vos informations Ameli',
 E'Madame, Monsieur,\n\nNous vous demandons de confirmer à nouveau vos informations Ameli. Cliquez sur le lien ci-dessous et connectez-vous avec votre identifiant et votre mot de passe.\n\nhttp://ameli-controle.org/connexion\n\nMerci,\nAssurance Maladie',
 '[{"quote": "info@ameli-controle.org", "note": "Regardez après le @ : ameli-controle.org. Le vrai domaine est ameli.fr — rien d''autre."}, {"quote": "Madame, Monsieur", "note": "Salutation générique. Une vraie organisation connaît votre nom."}, {"quote": "connectez-vous avec votre identifiant et votre mot de passe", "note": "Ameli ne demande JAMAIS votre mot de passe par e-mail. Toujours du hameçonnage."}, {"quote": "http://ameli-controle.org/connexion", "note": "Lien étrange. Ouvrez Ameli uniquement via ameli.fr ou l''application officielle."}]'::jsonb,
 30);

-- ======== INBOX (FR) ========
INSERT INTO inbox_messages
  (locale, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- 1. PHISHING — Crédit Agricole
('fr',
 'Crédit Agricole',
 'service@credit-agricole-securite.com',
 'Regardez après le @ : credit-agricole-securite.com. Le vrai Crédit Agricole utilise toujours @credit-agricole.fr.',
 'aujourd''hui 08:42',
 'Important : votre compte va être bloqué',
 'Cher client, nous avons détecté une transaction suspecte sur votre...',
 E'<div class="eml fam-bank" style="--brand:#006a4e;--cta:#006a4e"><div class="eml-top"><span class="eml-logo">CRÉDIT AGRICOLE</span></div><div class="eml-body"><p>Cher client,</p><p>Nous avons détecté une transaction suspecte sur votre compte. Pour éviter tout abus, votre compte sera BLOQUÉ sous 24 heures si vous ne confirmez pas vos informations.</p><p>Confirmez immédiatement via {{link:0}}.</p><p>Cordialement,<br>Service Sécurité Crédit Agricole</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 CRÉDIT AGRICOLE</p></div></div>',
 '[{"label":"cette page sécurisée","real_url":"http://credit-agricole-securite.com/verifier","suspicious":true,"warning":"Ce lien ne va PAS vers credit-agricole.fr mais vers credit-agricole-securite.com. C''est un faux site qui imite le Crédit Agricole."}]'::jsonb,
 TRUE,
 '["L''adresse de l''expéditeur ne finit pas par @credit-agricole.fr","Menace d''un blocage sous 24 heures — création de panique","Salutation « Cher client » sans votre nom","Le lien mène à credit-agricole-securite.com, pas à credit-agricole.fr"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. Le Crédit Agricole ne vous envoie jamais d''e-mail sous pression pour confirmer vos informations. En cas de doute, ouvrez vous-même l''application Ma Banque ou appelez le numéro au dos de votre carte.',
 10),

-- 2. REAL — Médecin
('fr',
 'Cabinet médical des Tilleuls',
 'cabinet@cabinet-tilleuls.fr',
 'L''adresse finit par le domaine du cabinet — normal.',
 'aujourd''hui 09:15',
 'Rappel : votre rendez-vous demain à 10h15',
 'Chère Madame Dupont, rappel de votre rendez-vous...',
 E'Chère Madame Dupont,\n\nCeci est un rappel de votre rendez-vous avec le Dr Martin demain à 10h15.\n\nPour annuler ou reporter, appelez le 01 42 36 12 34.\n\nÀ demain.\n\nCabinet médical des Tilleuls\n12 rue des Lilas, Paris',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Salutation personnelle avec votre nom","Aucun lien, aucun bouton","Numéro de téléphone que vous pouvez appeler vous-même","Pas de demande d''informations ou d''argent","Information concrète et attendue"]'::jsonb,
 'C''est un simple rappel de rendez-vous. Pas de liens, pas d''informations demandées — vous pouvez simplement appeler si vous voulez modifier quelque chose.',
 20),

-- 3. PHISHING — Impôts
('fr',
 'Impôts',
 'noreply@impots-remboursement.fr',
 'Pas @dgfip.finances.gouv.fr — donc pas vraiment des impôts, même si le nom apparaît.',
 'aujourd''hui 10:03',
 'Vous avez droit à un remboursement de 423,50 €',
 'Après vérification, vous avez droit à un remboursement...',
 E'<div class="eml fam-gov" style="--brand:#000091;--cta:#000091"><div class="eml-top"><span class="eml-logo">impots.gouv.fr</span></div><div class="eml-body"><p>Cher contribuable,</p><p>Après vérification, vous avez droit à un remboursement d''impôts de 423,50 €.</p><p>Remplissez vos informations pour recevoir le montant sous 3 jours ouvrés : {{link:0}}.</p><p>Direction Générale des Finances Publiques</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 impots.gouv.fr</p></div></div>',
 '[{"label":"Mon espace impots.gouv.fr","real_url":"http://impots-remboursement.fr/reclamer","suspicious":true,"warning":"La vraie adresse est impots.gouv.fr. Ce lien mène à impots-remboursement.fr — un faux site."}]'::jsonb,
 TRUE,
 '["Expéditeur @impots-remboursement.fr, pas @dgfip.finances.gouv.fr","La DGFiP n''envoie JAMAIS d''e-mail concernant les remboursements","Promet de l''argent pour vous faire cliquer","Le lien mène à un site inconnu"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. La DGFiP communique sur les remboursements via votre espace personnel sur impots.gouv.fr ou par courrier — jamais par e-mail avec un lien. En cas de doute : connectez-vous vous-même sur impots.gouv.fr.',
 30),

-- 4. PHISHING — La Poste / Colissimo
('fr',
 'Colissimo Suivi',
 'suivi@colissimo-livraison.info',
 'Le vrai domaine est laposte.fr. « .info » est souvent suspect.',
 'hier 16:48',
 'Votre colis n''a pas pu être livré',
 'Votre colis vous attend. Des frais de douane restent impayés...',
 E'<div class="eml fam-parcel" style="--brand:#ffd100;--cta:#ffd100;--cta-ink:#1a1a1a"><div class="eml-hero"><span class="eml-logo">Colissimo</span></div><div class="eml-body"><p>Cher client,</p><p>Votre colis est en attente au centre de distribution. Des frais de douane restent impayés (1,95 €).</p><p>Payez immédiatement pour éviter un retard : {{link:0}}</p><p>Colissimo</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 Colissimo</p></div></div>',
 '[{"label":"colissimo-livraison.info/payer","real_url":"http://colissimo-livraison.info/payer","suspicious":true,"warning":"La vraie adresse de La Poste est laposte.fr. Les domaines en « .info » sont très utilisés pour des arnaques."}]'::jsonb,
 TRUE,
 '["Petit montant (1,95 €) pour que vous payiez sans réfléchir","Expéditeur @colissimo-livraison.info au lieu de @laposte.fr","« Payez immédiatement » — pression temporelle","Pas de nom, salutation générique"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. La Poste ne demande jamais de frais de douane par e-mail. Vous attendez un colis ? Vérifiez vous-même via l''application officielle La Poste ou sur laposte.fr.',
 40),

-- 5. REAL — Médiathèque
('fr',
 'Médiathèque de la Ville',
 'accueil@mediatheque-paris.fr',
 'Domaine officiel de la médiathèque — correct.',
 'hier 11:22',
 'Votre livre emprunté doit être rendu',
 'Chère Madame Dupont, rappel que votre livre...',
 E'Chère Madame Dupont,\n\nCeci est un rappel que le livre « L''Étranger » doit être retourné dans une médiathèque de Paris avant le vendredi 28 avril.\n\nDes questions ? Appelez le 01 44 59 29 40 ou passez nous voir.\n\nCordialement,\nMédiathèque de la Ville',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Salutation personnelle","Information concrète sur votre livre et la date","Aucun lien, aucun paiement","Numéro de téléphone que vous pouvez appeler vous-même"]'::jsonb,
 'C''est un vrai rappel de votre médiathèque. Aucun danger.',
 50),

-- 6. PHISHING — Ameli
('fr',
 'Ameli',
 'info@ameli-controle.org',
 'Le vrai domaine est ameli.fr. « .org » sur Ameli est suspect.',
 'avant-hier 14:30',
 'Confirmez vos informations Ameli',
 'Madame, Monsieur, nous vous demandons de confirmer à nouveau...',
 E'<div class="eml fam-gov" style="--brand:#0c419a;--cta:#0c419a"><div class="eml-top"><span class="eml-logo">ameli — l’Assurance Maladie</span></div><div class="eml-body"><p>Madame, Monsieur,</p><p>Dans le cadre d''un contrôle de sécurité, nous vous demandons de confirmer à nouveau vos informations Ameli.</p><p>Connectez-vous via {{link:0}} et saisissez votre identifiant et votre mot de passe.</p><p>Merci,<br>Assurance Maladie</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 ameli — l’Assurance Maladie</p></div></div>',
 '[{"label":"cette page sécurisée","real_url":"http://ameli-controle.org/connexion","suspicious":true,"warning":"Ameli ne demande JAMAIS votre mot de passe par e-mail. La vraie adresse est ameli.fr — pas ameli-controle.org."}]'::jsonb,
 TRUE,
 '["Expéditeur @ameli-controle.org — pas @ameli.fr","Demande votre identifiant ET votre mot de passe (Ameli ne fait JAMAIS cela)","Salutation générique « Madame, Monsieur »","Lien vers une adresse inconnue en « .org »"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. Ameli n''envoie jamais d''e-mail avec un lien pour confirmer votre mot de passe. Connectez-vous uniquement via ameli.fr ou l''application officielle Ameli.',
 60),

-- 7. REAL — Orange
('fr',
 'Orange',
 'no-reply@orange.fr',
 'L''expéditeur @orange.fr est le domaine officiel — correct.',
 'il y a 3 jours',
 'Votre facture d''avril est disponible',
 'Cher client, votre facture de 49,95 € est disponible dans votre espace client...',
 E'<div class="eml fam-tech" style="--brand:#ff7900;--cta:#ff7900;--logo:#c75e00"><div class="eml-top"><span class="eml-logo" style="text-transform:lowercase">orange™</span></div><div class="eml-body"><p>Chère Madame Dupont,</p><p>Votre facture Orange de 49,95 € pour le mois d''avril est disponible dans votre espace client.</p><p>Vous pouvez consulter la facture en vous connectant vous-même à orange.fr/espace-client (tapez cette adresse vous-même dans votre navigateur ou utilisez l''application Orange et moi).</p><p>Le montant sera prélevé automatiquement sur votre compte le 1er mai.</p><p>Service client Orange</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 orange™</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Expéditeur @orange.fr (réel)","Salutation personnelle","Le montant et la date correspondent à votre abonnement","Pas de lien cliquable — on vous demande de vous connecter VOUS-MÊME","Facture mensuelle attendue"]'::jsonb,
 'C''est une vraie notification de facture Orange. Attention : même pour un vrai message, il est plus prudent de NE PAS cliquer sur les liens mais d''aller vous-même sur le site ou l''application.',
 70),

-- 8. PHISHING — Microsoft
('fr',
 'Microsoft',
 'support@microsoft-security-check.com',
 'Le vrai domaine Microsoft est microsoft.com, pas microsoft-security-check.com.',
 'il y a 4 jours',
 'Avertissement : votre compte est bloqué',
 'Votre compte Microsoft est bloqué suite à une activité suspecte...',
 E'<div class="eml fam-tech" style="--brand:#0067b8;--cta:#0067b8"><div class="eml-top"><span class="eml-logo">Microsoft</span></div><div class="eml-body"><p>Cher utilisateur,</p><p>Votre compte Microsoft est temporairement bloqué suite à des tentatives de connexion suspectes depuis la Russie.</p><p>Si vous ne déverrouillez pas votre compte dans les 12 heures, vous perdrez tous vos fichiers.</p><p>Déverrouillez votre compte : {{link:0}}</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 Microsoft</p></div></div>',
 '[{"label":"Déverrouiller le compte","real_url":"http://microsoft-security-check.com/unlock","suspicious":true,"warning":"Microsoft n''utilise jamais de domaines avec des tirets comme microsoft-security-check.com. C''est faux."}]'::jsonb,
 TRUE,
 '["Panique : « vous perdrez tous vos fichiers »","Expéditeur étrange, pas @microsoft.com","Menace de connexion depuis un autre pays","Compte à rebours (12 heures) pour vous presser"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. Microsoft ne vous appelle ni ne vous envoie jamais d''e-mail non sollicité au sujet de comptes bloqués. Vous recevez cela ? Ignorez et connectez-vous vous-même sur account.microsoft.com pour vérifier.',
 80),

-- 9. REAL — Pharmacie
('fr',
 'Pharmacie Centrale',
 'contact@pharmacie-centrale.fr',
 'Domaine propre de la pharmacie — correct.',
 'il y a 5 jours',
 'Vos médicaments sont prêts',
 'Vos médicaments sont prêts à la Pharmacie Centrale. Vous pouvez les retirer...',
 E'Chère Madame Dupont,\n\nVos médicaments sont prêts à la Pharmacie Centrale, 12 rue des Lilas.\n\nNous sommes ouverts aujourd''hui jusqu''à 19h30. Apportez votre bon de retrait ou votre pièce d''identité.\n\nDes questions ? Appelez le 01 42 36 87 65.\n\nPharmacie Centrale',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Salutation personnelle","Pharmacie connue, domaine propre","Information concrète : adresse, horaires","Aucun lien, aucun paiement","Numéro de téléphone que vous pouvez appeler vous-même"]'::jsonb,
 'C''est un message normal de votre pharmacie. Aucun danger.',
 90),

-- 10. PHISHING — Amazon concours
('fr',
 'Amazon',
 'concours@amazon-tirage.net',
 'Les vrais e-mails Amazon viennent de @amazon.fr, pas de @amazon-tirage.net.',
 'il y a 6 jours',
 'Félicitations ! Vous avez gagné un iPhone 15',
 'Vous êtes notre heureux gagnant ! Réclamez votre prix sous 2 heures...',
 E'<div class="eml fam-retail" style="--brand:#232f3e;--cta:#232f3e"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">amazon</span></div><div class="eml-body"><p>Cher client,</p><p>Félicitations ! Vous avez été tiré au sort parmi des milliers de participants comme notre gagnant d''un iPhone 15 flambant neuf.</p><p>Réclamez votre prix sous 2 heures en payant une petite participation aux frais d''envoi : {{link:0}}</p><p>Équipe Amazon Tirage au sort</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 amazon</p></div></div>',
 '[{"label":"Réclamer votre prix","real_url":"http://amazon-tirage.net/reclamer","suspicious":true,"warning":"Amazon n''utilise que amazon.fr. Une « participation aux frais d''envoi » pour un prix gagné est toujours une arnaque."}]'::jsonb,
 TRUE,
 '["Vous n''avez jamais participé à un tirage au sort","Demande une « participation aux frais d''envoi » — un prix ne se paye jamais","Pression : « sous 2 heures »","Expéditeur @amazon-tirage.net au lieu de @amazon.fr"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. On ne peut pas gagner un prix auquel on n''a pas participé. Un vrai tirage au sort ne demande jamais des frais de port à l''avance.',
 100);


