-- ============================================================
-- DEUTSCH (DE)
-- ============================================================

-- ======== VOORBEELDEN (DE) ========
INSERT INTO examples (locale, channel, sender, subject, body, annotations, sort_order) VALUES
('de', 'email',
 'Sparkasse <service@sparkasse-sicher-login.com>',
 'Wichtig: Ihr Konto wird gesperrt',
 E'Sehr geehrter Kunde,\n\nWir haben eine verdächtige Transaktion auf Ihrem Konto festgestellt. Innerhalb von 24 Stunden wird Ihr Konto GESPERRT, wenn Sie Ihre Daten nicht bestätigen.\n\nKlicken Sie hier, um Ihr Konto zu sichern: http://sparkasse-sicher-login.com/verify\n\nMit freundlichen Grüßen,\nSparkasse Sicherheitsteam',
 '[{"quote": "service@sparkasse-sicher-login.com", "note": "Achten Sie darauf, was NACH dem @ steht: sparkasse-sicher-login.com. Das ist nicht die Sparkasse. Die echte Sparkasse nutzt immer @sparkasse.de. Der Teil VOR dem @ („service“) kann vom Betrüger frei gewählt werden."}, {"quote": "GESPERRT, wenn Sie Ihre Daten nicht bestätigen", "note": "Angst und Eile erzeugen. Eine echte Bank macht das nie."}, {"quote": "Sehr geehrter Kunde", "note": "Kein Name. Ihre Bank kennt Ihren Namen."}, {"quote": "http://sparkasse-sicher-login.com/verify", "note": "Verdächtiger Link, der nicht von der Sparkasse ist. Nicht anklicken!"}]'::jsonb,
 10),

('de', 'email',
 'Finanzamt <noreply@finanzamt-erstattung.de>',
 'Sie haben Anspruch auf 423,50 € Rückerstattung',
 E'Sehr geehrter Steuerzahler,\n\nNach unserer Prüfung haben Sie Anspruch auf eine Steuererstattung in Höhe von 423,50 €. Geben Sie schnell Ihre Daten ein, um den Betrag zu erhalten.\n\nKlicken Sie hier: http://finanzamt-erstattung.de/anfordern\n\nFinanzamt',
 '[{"quote": "noreply@finanzamt-erstattung.de", "note": "Achten Sie auf den Teil nach dem @: finanzamt-erstattung.de. Das ist NICHT das Finanzamt. Echte Kommunikation läuft über @elster.de oder Briefpost."}, {"quote": "Sehr geehrter Steuerzahler", "note": "Allgemeine Anrede ohne Ihren Namen. Das Finanzamt kennt Sie."}, {"quote": "Anspruch auf eine Steuererstattung in Höhe von 423,50 €", "note": "Ein Geldversprechen ist ein klassischer Köder. Das Finanzamt kündigt Erstattungen nie per E-Mail mit Link an."}, {"quote": "http://finanzamt-erstattung.de/anfordern", "note": "Verdächtiger Link, nicht elster.de. Nicht anklicken."}]'::jsonb,
 20),

('de', 'email',
 'ELSTER <info@elster-sicher.org>',
 'Bitte bestätigen Sie Ihre ELSTER-Daten',
 E'Sehr geehrte Damen und Herren,\n\nWir bitten Sie, Ihre ELSTER-Daten erneut zu bestätigen. Klicken Sie auf den untenstehenden Link und melden Sie sich mit Ihrem Benutzernamen und Passwort an.\n\nhttp://elster-sicher.org/anmelden\n\nMit freundlichen Grüßen,\nELSTER',
 '[{"quote": "info@elster-sicher.org", "note": "Achten Sie auf den Teil nach dem @: elster-sicher.org. Die echte Domain ist elster.de — nichts anderes."}, {"quote": "Sehr geehrte Damen und Herren", "note": "Allgemeine Anrede. Eine echte Organisation kennt Ihren Namen."}, {"quote": "melden Sie sich mit Ihrem Benutzernamen und Passwort an", "note": "ELSTER fragt NIEMALS per E-Mail nach Ihrem Passwort. Immer Phishing."}, {"quote": "http://elster-sicher.org/anmelden", "note": "Verdächtiger Link. Öffnen Sie ELSTER nur über elster.de oder die offizielle App."}]'::jsonb,
 30);

-- ======== INBOX (DE) ========
INSERT INTO inbox_messages
  (locale, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- 1. PHISHING — Sparkasse
('de',
 'Sparkasse',
 'service@sparkasse-sicher-login.com',
 'Achten Sie auf den Teil nach dem @: sparkasse-sicher-login.com. Die echte Sparkasse nutzt immer @sparkasse.de.',
 'heute 08:42',
 'Wichtig: Ihr Konto wird gesperrt',
 'Sehr geehrter Kunde, wir haben eine verdächtige Transaktion auf Ihrem...',
 E'<div class="eml fam-bank" style="--brand:#ff0000;--cta:#ff0000;--logo:#fa0000"><div class="eml-top"><span class="eml-logo">Sparkasse</span></div><div class="eml-body"><p>Sehr geehrter Kunde,</p><p>Wir haben eine verdächtige Transaktion auf Ihrem Konto festgestellt. Um Missbrauch zu verhindern, wird Ihr Konto innerhalb von 24 Stunden GESPERRT, wenn Sie Ihre Daten nicht bestätigen.</p><p>Bestätigen Sie sofort über {{link:0}}.</p><p>Mit freundlichen Grüßen,<br>Sparkasse Sicherheitsteam</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 Sparkasse</p></div></div>',
 '[{"label":"diese sichere Seite","real_url":"http://sparkasse-sicher-login.com/verify","suspicious":true,"warning":"Dieser Link führt NICHT zu sparkasse.de, sondern zu sparkasse-sicher-login.com. Das ist eine gefälschte Seite, die wie die Sparkasse aussieht."}]'::jsonb,
 TRUE,
 '["Absenderadresse endet nicht auf @sparkasse.de","Droht mit Sperrung innerhalb von 24 Stunden — Panikmache","Anrede „Sehr geehrter Kunde“ ohne Ihren Namen","Link führt zu sparkasse-sicher-login.com, nicht zu sparkasse.de"]'::jsonb,
 '[]'::jsonb,
 'Das ist Phishing. Die Sparkasse schickt niemals E-Mails unter Zeitdruck, um Ihre Daten bestätigen zu lassen. Im Zweifel öffnen Sie selbst die Sparkassen-App oder rufen die Nummer auf der Rückseite Ihrer Karte an.',
 10),

-- 2. REAL — Hausarzt
('de',
 'Hausarztpraxis Dr. Schmidt',
 'praxis@hausarzt-schmidt.de',
 'Die Adresse endet auf der eigenen Domain der Praxis — normal.',
 'heute 09:15',
 'Erinnerung: Ihr Termin morgen um 10:15',
 'Sehr geehrte Frau Müller, dies ist eine Erinnerung an Ihren Termin...',
 E'Sehr geehrte Frau Müller,\n\nDies ist eine Erinnerung an Ihren Termin bei Dr. Schmidt morgen um 10:15.\n\nMöchten Sie absagen oder verschieben? Dann rufen Sie bitte 030 123 45 67 an.\n\nBis morgen.\n\nHausarztpraxis Dr. Schmidt\nHauptstraße 12, Berlin',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Persönliche Anrede mit Ihrem Namen","Kein Link, keine Schaltfläche","Telefonnummer, die Sie selbst anrufen können","Keine Frage nach Daten oder Geld","Konkrete, erwartete Information"]'::jsonb,
 'Das ist eine ganz normale Terminerinnerung. Keine Links, keine Datenabfrage — Sie können einfach anrufen, wenn Sie etwas ändern möchten.',
 20),

-- 3. PHISHING — Finanzamt
('de',
 'Finanzamt',
 'noreply@finanzamt-erstattung.de',
 'Nicht @elster.de — also nicht vom Finanzamt, auch wenn der Name erscheint.',
 'heute 10:03',
 'Sie haben Anspruch auf 423,50 € Rückerstattung',
 'Nach unserer Prüfung haben Sie Anspruch auf eine Steuererstattung...',
 E'<div class="eml fam-gov" style="--brand:#003064;--cta:#003064"><div class="eml-top"><span class="eml-logo">Finanzamt</span></div><div class="eml-body"><p>Sehr geehrter Steuerzahler,</p><p>Nach unserer Prüfung haben Sie Anspruch auf eine Steuererstattung in Höhe von 423,50 €.</p><p>Geben Sie Ihre Daten ein, um den Betrag innerhalb von 3 Werktagen zu erhalten: {{link:0}}.</p><p>Finanzamt</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 Finanzamt</p></div></div>',
 '[{"label":"Mein ELSTER","real_url":"http://finanzamt-erstattung.de/anfordern","suspicious":true,"warning":"Die echte Adresse ist elster.de. Dieser Link führt zu finanzamt-erstattung.de — einer gefälschten Seite."}]'::jsonb,
 TRUE,
 '["Absender @finanzamt-erstattung.de, nicht @elster.de","Das Finanzamt versendet NIEMALS E-Mails zu Erstattungen","Verspricht Geld, um Sie zum Klick zu bewegen","Link führt zu einer unbekannten Website"]'::jsonb,
 '[]'::jsonb,
 'Das ist Phishing. Das Finanzamt kommuniziert über ELSTER (elster.de) oder per Briefpost — niemals per E-Mail mit Link. Im Zweifel: melden Sie sich selbst bei elster.de an.',
 30),

-- 4. PHISHING — DHL
('de',
 'DHL Sendungsverfolgung',
 'tracking@dhl-paket-info.com',
 'Die echte Domain ist dhl.de. „.com“ mit Bindestrichen ist oft verdächtig.',
 'gestern 16:48',
 'Ihr Paket konnte nicht zugestellt werden',
 'Ihr Paket wartet auf Sie. Es gibt noch unbezahlte Zollgebühren...',
 E'<div class="eml fam-parcel" style="--brand:#ffcc00;--cta:#ffcc00;--cta-ink:#d40511"><div class="eml-hero"><span class="eml-logo">DHL</span></div><div class="eml-body"><p>Sehr geehrter Kunde,</p><p>Ihr Paket wartet im Verteilzentrum. Es gibt noch unbezahlte Zollgebühren (1,95 €).</p><p>Zahlen Sie sofort, um Verzögerungen zu vermeiden: {{link:0}}</p><p>DHL</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 DHL</p></div></div>',
 '[{"label":"dhl-paket-info.com/zahlen","real_url":"http://dhl-paket-info.com/zahlen","suspicious":true,"warning":"Die echte Adresse von DHL ist dhl.de. Domains mit Bindestrichen werden oft für Betrug genutzt."}]'::jsonb,
 TRUE,
 '["Kleiner Betrag (1,95 €), damit Sie ohne Nachdenken zahlen","Absender @dhl-paket-info.com statt @dhl.de","„Zahlen Sie sofort“ — Zeitdruck","Kein Name, allgemeine Anrede"]'::jsonb,
 '[]'::jsonb,
 'Das ist Phishing. DHL verlangt niemals Zollgebühren per E-Mail. Erwarten Sie ein Paket? Prüfen Sie es selbst über die offizielle DHL-App oder auf dhl.de.',
 40),

-- 5. REAL — Stadtbibliothek
('de',
 'Stadtbibliothek Berlin',
 'info@zlb.de',
 'Offizielle Domain der Berliner Stadtbibliothek (zlb.de) — passt.',
 'gestern 11:22',
 'Ihr geliehenes Buch muss zurück',
 'Sehr geehrte Frau Müller, dies ist eine Erinnerung, dass Sie Ihr Buch...',
 E'Sehr geehrte Frau Müller,\n\nDies ist eine Erinnerung, dass das Buch „Der Vorleser“ spätestens am Freitag, 28. April, in einer Zweigstelle der Zentral- und Landesbibliothek zurückgegeben werden muss.\n\nFragen? Rufen Sie 030 90226 401 an oder kommen Sie vorbei.\n\nMit freundlichen Grüßen,\nStadtbibliothek Berlin',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Persönliche Anrede","Konkrete Information zu Ihrem Buch und Datum","Kein Link, keine Zahlung","Telefonnummer, die Sie selbst anrufen können"]'::jsonb,
 'Das ist eine echte Erinnerung Ihrer Bibliothek. Keine Gefahr.',
 50),

-- 6. PHISHING — ELSTER
('de',
 'ELSTER',
 'info@elster-sicher.org',
 'Die echte Domain ist elster.de. „.org“ bei ELSTER ist verdächtig.',
 'vorgestern 14:30',
 'Bitte bestätigen Sie Ihre ELSTER-Daten',
 'Sehr geehrte Damen und Herren, wir bitten Sie, Ihre ELSTER-Daten...',
 E'<div class="eml fam-gov" style="--brand:#5a8f22;--cta:#5a8f22;--logo:#588c21"><div class="eml-top"><span class="eml-logo">ELSTER</span></div><div class="eml-body"><p>Sehr geehrte Damen und Herren,</p><p>Im Rahmen einer Sicherheitsprüfung bitten wir Sie, Ihre ELSTER-Daten erneut zu bestätigen.</p><p>Melden Sie sich über {{link:0}} an und geben Sie Ihren Benutzernamen und Ihr Passwort ein.</p><p>Mit freundlichen Grüßen,<br>ELSTER</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 ELSTER</p></div></div>',
 '[{"label":"diese sichere Seite","real_url":"http://elster-sicher.org/anmelden","suspicious":true,"warning":"ELSTER fragt NIEMALS per E-Mail nach Ihrem Passwort. Die echte Adresse ist elster.de — nicht elster-sicher.org."}]'::jsonb,
 TRUE,
 '["Absender @elster-sicher.org — nicht @elster.de","Fragt nach Benutzername UND Passwort (das macht ELSTER NIEMALS)","Allgemeine Anrede „Sehr geehrte Damen und Herren“","Link zu unbekannter „.org“-Adresse"]'::jsonb,
 '[]'::jsonb,
 'Das ist Phishing. ELSTER verschickt nie eine E-Mail mit Link, um Ihr Passwort bestätigen zu lassen. Melden Sie sich nur über elster.de oder die offizielle ElsterSmart-App an.',
 60),

-- 7. REAL — Telekom
('de',
 'Telekom',
 'no-reply@telekom.de',
 'Absender @telekom.de ist die offizielle Domain — passt.',
 'vor 3 Tagen',
 'Ihre April-Rechnung liegt bereit',
 'Sehr geehrter Kunde, Ihre Rechnung über 49,95 € liegt in MeineTelekom bereit...',
 E'<div class="eml fam-tech" style="--brand:#e20074;--cta:#e20074"><div class="eml-top"><span class="eml-logo">T · Telekom</span></div><div class="eml-body"><p>Sehr geehrte Frau Müller,</p><p>Ihre Telekom-Rechnung über 49,95 € für den Monat April liegt in MeineTelekom bereit.</p><p>Sie können die Rechnung einsehen, indem Sie sich selbst unter telekom.de/meinetelekom anmelden (tippen Sie diese Adresse selbst in Ihren Browser oder nutzen Sie die MeineTelekom-App).</p><p>Der Betrag wird am 1. Mai automatisch von Ihrem Konto abgebucht.</p><p>Telekom Kundenservice</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 T · Telekom</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Absender ist @telekom.de (echt)","Persönliche Anrede","Betrag und Datum stimmen mit Ihrem Vertrag überein","Kein anklickbarer Link — Sie werden gebeten, sich SELBST anzumelden","Erwartete Monatsrechnung"]'::jsonb,
 'Das ist eine echte Rechnungsbenachrichtigung der Telekom. Hinweis: Auch bei echten Nachrichten ist es sicherer, NICHT auf Links zu klicken, sondern selbst zur Website oder App zu gehen.',
 70),

-- 8. PHISHING — Microsoft
('de',
 'Microsoft',
 'support@microsoft-security-check.com',
 'Die echte Microsoft-Domain ist microsoft.com, nicht microsoft-security-check.com.',
 'vor 4 Tagen',
 'Warnung: Ihr Konto wurde gesperrt',
 'Ihr Microsoft-Konto wurde wegen verdächtiger Aktivität gesperrt...',
 E'<div class="eml fam-tech" style="--brand:#0067b8;--cta:#0067b8"><div class="eml-top"><span class="eml-logo">Microsoft</span></div><div class="eml-body"><p>Sehr geehrter Nutzer,</p><p>Ihr Microsoft-Konto wurde wegen verdächtiger Anmeldeversuche aus Russland vorübergehend gesperrt.</p><p>Wenn Sie Ihr Konto nicht innerhalb von 12 Stunden entsperren, verlieren Sie alle Ihre Dateien.</p><p>Konto entsperren: {{link:0}}</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 Microsoft</p></div></div>',
 '[{"label":"Konto entsperren","real_url":"http://microsoft-security-check.com/unlock","suspicious":true,"warning":"Microsoft nutzt niemals Domains mit Bindestrichen wie microsoft-security-check.com. Das ist gefälscht."}]'::jsonb,
 TRUE,
 '["Panikmache: „verlieren Sie alle Ihre Dateien“","Seltsamer Absender, nicht @microsoft.com","Drohung über Anmeldung aus einem anderen Land","Countdown (12 Stunden), um Sie zu Eile zu zwingen"]'::jsonb,
 '[]'::jsonb,
 'Das ist Phishing. Microsoft ruft Sie nie ungefragt an oder schreibt Sie wegen gesperrter Konten an. Erhalten Sie so etwas? Ignorieren und selbst unter account.microsoft.com anmelden, um zu prüfen.',
 80),

-- 9. REAL — Apotheke
('de',
 'Apotheke am Rathaus',
 'apotheke@apotheke-am-rathaus.de',
 'Eigene Domain der Apotheke — passt.',
 'vor 5 Tagen',
 'Ihre Medikamente sind abholbereit',
 'Ihre Medikamente sind abholbereit in der Apotheke am Rathaus. Sie können sie...',
 E'Sehr geehrte Frau Müller,\n\nIhre Medikamente sind abholbereit in der Apotheke am Rathaus, Hauptstraße 12.\n\nWir haben heute bis 18:30 Uhr geöffnet. Bringen Sie bitte Ihren Abholschein oder einen Ausweis mit.\n\nFragen? Rufen Sie 030 111 22 33 an.\n\nApotheke am Rathaus',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Persönliche Anrede","Bekannte Apotheke, eigene Domain","Konkrete Information: Adresse, Öffnungszeit","Kein Link, keine Zahlung","Telefonnummer, die Sie selbst anrufen können"]'::jsonb,
 'Das ist eine normale Nachricht Ihrer Apotheke. Keine Gefahr.',
 90),

-- 10. PHISHING — Amazon Gewinnspiel
('de',
 'Amazon',
 'gewinn@amazon-gewinnspiel.net',
 'Echte Amazon-Mails kommen von @amazon.de, nicht von @amazon-gewinnspiel.net.',
 'vor 6 Tagen',
 'Herzlichen Glückwunsch! Sie haben ein iPhone 15 gewonnen',
 'Sie sind unser glücklicher Gewinner! Fordern Sie Ihren Preis innerhalb von 2 Stunden an...',
 E'<div class="eml fam-retail" style="--brand:#232f3e;--cta:#232f3e"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">amazon</span></div><div class="eml-body"><p>Sehr geehrter Kunde,</p><p>Herzlichen Glückwunsch! Sie wurden aus Tausenden von Teilnehmern als Gewinner eines brandneuen iPhone 15 gezogen.</p><p>Fordern Sie Ihren Preis innerhalb von 2 Stunden an, indem Sie einen kleinen Versandbeitrag zahlen: {{link:0}}</p><p>Amazon Gewinnspiel-Team</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 amazon</p></div></div>',
 '[{"label":"Preis anfordern","real_url":"http://amazon-gewinnspiel.net/anfordern","suspicious":true,"warning":"Amazon nutzt nur amazon.de. Ein „Versandbeitrag“ für einen gewonnenen Preis ist immer Betrug."}]'::jsonb,
 TRUE,
 '["Sie haben überhaupt nicht an einem Gewinnspiel teilgenommen","Fordert einen „Versandbeitrag“ — Preise werden nie gegen Bezahlung verschickt","Druck: „innerhalb von 2 Stunden“","Absender @amazon-gewinnspiel.net statt @amazon.de"]'::jsonb,
 '[]'::jsonb,
 'Das ist Phishing. Sie können keinen Preis gewinnen, an dem Sie nicht teilgenommen haben. Ein echtes Gewinnspiel verlangt niemals Versandgebühren im Voraus.',
 100);


