-- ============================================================
-- NEDERLANDS (BELGIË / VLAAMS) — nl-BE
-- ============================================================

-- ======== VOORBEELDEN (nl-BE) ========
INSERT INTO examples (locale, channel, sender, subject, body, annotations, sort_order) VALUES
('nl-BE', 'email',
 'BNP Paribas Fortis <service@bnp-veilig-login.com>',
 'Belangrijk: uw rekening wordt geblokkeerd',
 E'Geachte klant,\n\nWij hebben een verdachte transactie op uw rekening opgemerkt. Binnen 24 uur wordt uw rekening GEBLOKKEERD als u uw gegevens niet bevestigt.\n\nKlik hier om uw rekening te beveiligen: http://bnp-veilig-login.com/login\n\nMet vriendelijke groeten,\nBNP Paribas Fortis Beveiligingsteam',
 '[{"quote": "service@bnp-veilig-login.com", "note": "Kijk naar wat NA de @ staat: bnp-veilig-login.com. Dat is niet BNP Paribas Fortis. De echte bank gebruikt altijd @bnpparibasfortis.com. Het deel vóór de @ (\"service\") mag de oplichter zelf verzinnen."}, {"quote": "GEBLOKKEERD als u uw gegevens niet bevestigt", "note": "Angst maken en haast. Een echte bank doet dit nooit."}, {"quote": "Geachte klant", "note": "Geen naam. Uw bank kent uw naam."}, {"quote": "http://bnp-veilig-login.com/login", "note": "Vreemde link die niet van BNP Paribas Fortis is. Niet op klikken!"}]'::jsonb,
 10),

('nl-BE', 'email',
 'FOD Financiën <noreply@minfin-teruggave.be>',
 'U heeft recht op € 423,50 terugbetaling',
 E'Beste burger,\n\nNa controle blijkt u recht te hebben op een belastingteruggave van € 423,50. Vul snel uw gegevens in om het bedrag te ontvangen.\n\nKlik hier: http://minfin-teruggave.be/claim\n\nFOD Financiën',
 '[{"quote": "noreply@minfin-teruggave.be", "note": "Kijk na de @: minfin-teruggave.be. Dat is NIET de FOD Financiën. Het echte domein is minfin.fed.be."}, {"quote": "Beste burger", "note": "Algemene aanspreking zonder uw naam. De FOD Financiën kent u."}, {"quote": "recht te hebben op een belastingteruggave van € 423,50", "note": "Belofte van geld is een klassieke lokker. De FOD Financiën mailt nooit over teruggaven."}, {"quote": "http://minfin-teruggave.be/claim", "note": "Vreemde link, niet myminfin.be. Niet op klikken."}]'::jsonb,
 20),

('nl-BE', 'email',
 'itsme <info@itsme-controle.org>',
 'Bevestig uw itsme-gegevens',
 E'Geachte heer/mevrouw,\n\nWij vragen u om uw itsme opnieuw te bevestigen. Klik op onderstaande link en meld u aan met uw gebruikersnaam en paswoord.\n\nhttp://itsme-controle.org/aanmelden\n\nBedankt,\nitsme',
 '[{"quote": "info@itsme-controle.org", "note": "Kijk na de @: itsme-controle.org. Het echte domein is itsme.be — niets anders."}, {"quote": "Geachte heer/mevrouw", "note": "Algemene aanspreking. Een echte organisatie kent uw naam."}, {"quote": "meld u aan met uw gebruikersnaam en paswoord", "note": "itsme werkt via uw eigen app en vraagt NOOIT uw paswoord per e-mail. Altijd phishing."}, {"quote": "http://itsme-controle.org/aanmelden", "note": "Vreemde link. Gebruik itsme alleen via de officiële app of via itsme.be."}]'::jsonb,
 30);

-- ======== INBOX (nl-BE) ========
INSERT INTO inbox_messages
  (locale, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- 1. PHISHING — BNP Paribas Fortis
('nl-BE',
 'BNP Paribas Fortis',
 'service@bnp-veilig-login.com',
 'Kijk na de @: bnp-veilig-login.com. BNP Paribas Fortis gebruikt altijd @bnpparibasfortis.com.',
 'vandaag 08:42',
 'Belangrijk: uw rekening wordt geblokkeerd',
 'Geachte klant, wij hebben een verdachte transactie opgemerkt op uw...',
 E'<div class="eml fam-bank" style="--brand:#00965e;--cta:#00965e;--logo:#00905a"><div class="eml-top"><span class="eml-logo">BNP Paribas Fortis</span></div><div class="eml-body"><p>Geachte klant,</p><p>Wij hebben een verdachte transactie opgemerkt op uw rekening. Om misbruik te voorkomen wordt uw rekening binnen 24 uur GEBLOKKEERD als u uw gegevens niet bevestigt.</p><p>Bevestig onmiddellijk via {{link:0}}.</p><p>Met vriendelijke groeten,<br>BNP Paribas Fortis Beveiligingsteam</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 BNP Paribas Fortis</p></div></div>',
 '[{"label":"deze beveiligde pagina","real_url":"http://bnp-veilig-login.com/login","suspicious":true,"warning":"Deze link gaat NIET naar bnpparibasfortis.com maar naar bnp-veilig-login.com. Dat is een nepwebsite die op BNP Paribas Fortis lijkt."}]'::jsonb,
 TRUE,
 '["Afzenderadres eindigt niet op @bnpparibasfortis.com","Dreigt met blokkering binnen 24 uur — paniek maken","Aanspreking \"Geachte klant\" zonder uw naam","Link gaat naar bnp-veilig-login.com, niet naar bnpparibasfortis.com"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. BNP Paribas Fortis stuurt nooit e-mails om u onder tijdsdruk uw gegevens te laten bevestigen. Had u getwijfeld? Open dan altijd zelf de Easy Banking App of bel Card Stop (078 170 170) om uw kaart te blokkeren.',
 10),

-- 2. REAL — Huisarts
('nl-BE',
 'Huisartsenpraktijk De Linde',
 'praktijk@huisartsendelinde.be',
 'Het adres eindigt op het eigen domein van de praktijk — normaal.',
 'vandaag 09:15',
 'Herinnering: uw afspraak morgen om 10u15',
 'Beste mevrouw Peeters, dit is een herinnering aan uw afspraak...',
 E'Beste mevrouw Peeters,\n\nDit is een herinnering aan uw afspraak bij dokter Vermeulen morgen om 10u15.\n\nWilt u afzeggen of verzetten? Bel dan 03 123 45 67.\n\nTot morgen.\n\nHuisartsenpraktijk De Linde\nMarkt 12, Antwerpen',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Persoonlijke aanspreking met uw naam","Geen link, geen knop","Telefoonnummer om zelf te bellen","Geen vraag om gegevens of geld","Concrete, verwachte informatie"]'::jsonb,
 'Dit is een gewone afspraakherinnering. Geen links, geen gegevens gevraagd — u kunt gewoon bellen als u iets wilt wijzigen.',
 20),

-- 3. PHISHING — FOD Financiën
('nl-BE',
 'FOD Financiën',
 'noreply@minfin-teruggave.be',
 'Niet @minfin.fed.be — dus niet van de FOD Financiën, ook al staat de naam er in.',
 'vandaag 10:03',
 'U heeft recht op € 423,50 terugbetaling',
 'Na controle blijkt u recht te hebben op een belastingteruggave...',
 E'<div class="eml fam-gov" style="--brand:#005a9c;--cta:#005a9c"><div class="eml-top"><span class="eml-logo">FOD Financiën</span></div><div class="eml-body"><p>Beste burger,</p><p>Na controle blijkt u recht te hebben op een belastingteruggave van € 423,50.</p><p>Vul uw gegevens in om het bedrag binnen 3 werkdagen te ontvangen: {{link:0}}.</p><p>FOD Financiën</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 FOD Financiën</p></div></div>',
 '[{"label":"MyMinfin","real_url":"http://minfin-teruggave.be/claim","suspicious":true,"warning":"Het echte adres is myminfin.be. Deze link gaat naar minfin-teruggave.be — een nepsite."}]'::jsonb,
 TRUE,
 '["Afzender is @minfin-teruggave.be, niet @minfin.fed.be","De FOD Financiën stuurt NOOIT e-mails over teruggaven","Belooft geld om u op de link te laten klikken","Link gaat naar een onbekende website"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. De FOD Financiën communiceert over teruggaven via MyMinfin of per post — nooit per e-mail met een link. Bij twijfel: meld u zelf aan bij myminfin.be met itsme of uw eID.',
 30),

-- 4. PHISHING — bpost
('nl-BE',
 'bpost Tracking',
 'track@bpost-levering.info',
 'Het echte domein is bpost.be. ".info" is vaak verdacht.',
 'gisteren 16:48',
 'Uw pakket kan niet bezorgd worden',
 'Uw pakket wacht op u. Er zijn nog onbetaalde invoerkosten...',
 E'<div class="eml fam-parcel" style="--brand:#e30613;--cta:#e30613"><div class="eml-hero"><span class="eml-logo">bpost</span></div><div class="eml-body"><p>Beste klant,</p><p>Uw pakket wacht in het sorteercentrum. Er zijn nog onbetaalde invoerkosten (€ 1,95).</p><p>Betaal onmiddellijk om uitstel te vermijden: {{link:0}}</p><p>bpost</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 bpost</p></div></div>',
 '[{"label":"bpost-levering.info/betaal","real_url":"http://bpost-levering.info/betaal","suspicious":true,"warning":"Het echte adres van bpost is bpost.be. \".info\"-domeinen worden veel gebruikt voor oplichting."}]'::jsonb,
 TRUE,
 '["Klein bedrag (€ 1,95) om u zonder nadenken te laten betalen","Afzender @bpost-levering.info in plaats van @bpost.be","\"Betaal onmiddellijk\" — druk uitoefenen","Geen naam, algemene aanspreking"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. bpost vraagt nooit per e-mail om invoerkosten. Verwacht u een pakket? Controleer het zelf via de officiële My bpost app of via bpost.be.',
 40),

-- 5. REAL — Bibliotheek
('nl-BE',
 'Bibliotheek Antwerpen',
 'info@bibliotheek.antwerpen.be',
 'Officieel domein van de stad Antwerpen — klopt.',
 'gisteren 11:22',
 'Uw geleend boek moet terug',
 'Beste mevrouw Peeters, dit is een herinnering dat u uw boek...',
 E'Beste mevrouw Peeters,\n\nDit is een herinnering dat u het boek "Het verdriet van België" ten laatste op vrijdag 28 april moet terugbrengen naar een filiaal van de Bibliotheek Antwerpen.\n\nVragen? Bel 03 338 88 88 of kom langs.\n\nMet vriendelijke groeten,\nBibliotheek Antwerpen',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Persoonlijke aanspreking","Concrete informatie over uw boek en datum","Geen link, geen betaling","Telefoonnummer dat u zelf kunt bellen"]'::jsonb,
 'Dit is een echte herinnering van uw bibliotheek. Geen gevaar.',
 50),

-- 6. PHISHING — itsme
('nl-BE',
 'itsme',
 'info@itsme-controle.org',
 'Het echte domein is itsme.be. ".org" op itsme is verdacht.',
 'eergisteren 14:30',
 'Bevestig uw itsme-gegevens',
 'Geachte heer/mevrouw, wij vragen u om uw itsme opnieuw te bevestigen...',
 E'<div class="eml fam-gov" style="--brand:#ff4612;--cta:#ff4612;--logo:#e53f10"><div class="eml-top"><span class="eml-logo">itsme®</span></div><div class="eml-body"><p>Geachte heer/mevrouw,</p><p>In verband met een veiligheidscontrole vragen wij u uw itsme opnieuw te bevestigen.</p><p>Meld u aan via {{link:0}} en vul uw gebruikersnaam en paswoord in.</p><p>Bedankt,<br>itsme</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 itsme®</p></div></div>',
 '[{"label":"deze beveiligde pagina","real_url":"http://itsme-controle.org/aanmelden","suspicious":true,"warning":"itsme vraagt NOOIT per e-mail om uw paswoord. Het echte adres is itsme.be — niet itsme-controle.org. itsme werkt alleen via de eigen app."}]'::jsonb,
 TRUE,
 '["Afzender @itsme-controle.org — niet @itsme.be","Vraagt om gebruikersnaam én paswoord (doet itsme NOOIT, want itsme werkt zonder paswoord)","Algemene aanspreking \"Geachte heer/mevrouw\"","Link naar onbekend \".org\"-adres"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. itsme werkt via uw eigen gsm-app met vingerafdruk of code — niet via e-mail met een link. Gebruik itsme alleen via de officiële app.',
 60),

-- 7. REAL — Proximus factuur
('nl-BE',
 'Proximus',
 'no-reply@proximus.be',
 'Afzender @proximus.be is het officiële domein — klopt.',
 '3 dagen geleden',
 'Uw factuur van april staat klaar',
 'Beste klant, uw factuur van € 49,95 staat klaar in MyProximus...',
 E'<div class="eml fam-tech" style="--brand:#5c2d91;--cta:#5c2d91"><div class="eml-top"><span class="eml-logo">Proximus</span></div><div class="eml-body"><p>Beste mevrouw Peeters,</p><p>Uw Proximus-factuur van € 49,95 voor de maand april staat klaar in MyProximus.</p><p>U kunt de factuur bekijken door zelf aan te melden op proximus.be/myproximus (typ dit adres zelf in uw browser of gebruik de MyProximus-app).</p><p>Het bedrag wordt op 1 mei automatisch van uw rekening afgeschreven.</p><p>Proximus Klantendienst</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 Proximus</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Afzender is @proximus.be (echt)","Persoonlijke aanspreking","Bedrag en datum kloppen met uw abonnement","Geen klikbare link — u wordt gevraagd ZELF aan te melden","Verwachte maandelijkse factuur"]'::jsonb,
 'Dit is een echte Proximus-factuurmelding. Let op: ook bij een echt bericht is het verstandig om NIET op links te klikken maar zelf naar de website of app te gaan.',
 70),

-- 8. PHISHING — Microsoft
('nl-BE',
 'Microsoft',
 'support@microsoft-security-check.com',
 'Het echte Microsoft-domein is microsoft.com, niet microsoft-security-check.com.',
 '4 dagen geleden',
 'Waarschuwing: uw account is geblokkeerd',
 'Uw Microsoft-account is geblokkeerd wegens verdachte activiteit...',
 E'<div class="eml fam-tech" style="--brand:#0067b8;--cta:#0067b8"><div class="eml-top"><span class="eml-logo">Microsoft</span></div><div class="eml-body"><p>Beste gebruiker,</p><p>Uw Microsoft-account is tijdelijk geblokkeerd wegens verdachte aanmeldpogingen vanuit Rusland.</p><p>Als u uw account niet binnen 12 uur ontgrendelt, verliest u al uw bestanden.</p><p>Ontgrendel uw account: {{link:0}}</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 Microsoft</p></div></div>',
 '[{"label":"Ontgrendel account","real_url":"http://microsoft-security-check.com/unlock","suspicious":true,"warning":"Microsoft gebruikt nooit domeinen met koppeltekens zoals microsoft-security-check.com. Dit is nep."}]'::jsonb,
 TRUE,
 '["Paniek: \"verliest u al uw bestanden\"","Rare afzender, niet @microsoft.com","Dreiging over aanmelding vanuit een ander land","Afteltijd (12 uur) om u te laten haasten"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. Microsoft belt of mailt u nooit ongevraagd over geblokkeerde accounts. Ontvangt u zoiets? Negeer het en meld u zelf aan op account.microsoft.com om te controleren.',
 80),

-- 9. REAL — Apotheek
('nl-BE',
 'Apotheek Peeters',
 'apotheek@apotheek-peeters.be',
 'Eigen domein van de apotheek — klopt.',
 '5 dagen geleden',
 'Uw medicijnen liggen klaar',
 'Uw medicijnen liggen klaar bij Apotheek Peeters. U kunt ze afhalen...',
 E'Beste mevrouw Peeters,\n\nUw medicijnen liggen klaar bij Apotheek Peeters, Markt 12.\n\nWij zijn vandaag open tot 18u30. Breng uw afhaalbon of identiteitskaart mee.\n\nVragen? Bel 03 111 22 33.\n\nApotheek Peeters',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Persoonlijke aanspreking","Bekende apotheek, eigen domein","Concrete informatie: adres, openingsuren","Geen link, geen betaling","Telefoonnummer om zelf te bellen"]'::jsonb,
 'Dit is een normale melding van uw apotheek. Geen gevaar.',
 90),

-- 10. PHISHING — Bol.com winactie
('nl-BE',
 'Bol.com',
 'winactie@bol-winactie.net',
 'Echte Bol.com-mails komen van @bol.com, niet van @bol-winactie.net.',
 '6 dagen geleden',
 'Gefeliciteerd! U heeft een iPhone 15 gewonnen',
 'U bent onze gelukkige winnaar! Claim uw prijs binnen 2 uur...',
 E'<div class="eml fam-retail" style="--brand:#0000a4;--cta:#0000a4"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">bol.com</span></div><div class="eml-body"><p>Beste klant,</p><p>Gefeliciteerd! U bent uit duizenden deelnemers getrokken als onze winnaar van een gloednieuwe iPhone 15.</p><p>Claim uw prijs binnen 2 uur door een kleine verzendbijdrage te betalen: {{link:0}}</p><p>Bol.com Winactie Team</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 bol.com</p></div></div>',
 '[{"label":"Claim uw prijs","real_url":"http://bol-winactie.net/claim","suspicious":true,"warning":"Bol.com gebruikt alleen bol.com als adres. Een \"verzendbijdrage\" bij een gewonnen prijs is altijd oplichterij."}]'::jsonb,
 TRUE,
 '["U heeft helemaal niet deelgenomen aan een winactie","Vraagt om \"verzendbijdrage\" — prijzen zijn nooit tegen betaling","Druk: \"binnen 2 uur\"","Afzender @bol-winactie.net in plaats van @bol.com"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. U kunt geen prijs winnen waar u niet aan heeft deelgenomen. Een echte winactie vraagt nooit om een verzendbijdrage op voorhand.',
 100);


