-- ============================================================
-- FRANÇAIS (BELGIQUE) — fr-BE
-- ============================================================

-- ======== VOORBEELDEN (fr-BE) ========
INSERT INTO examples (locale, channel, sender, subject, body, annotations, sort_order) VALUES
('fr-BE', 'email',
 'Belfius <service@belfius-securise.com>',
 'Important : votre compte va être bloqué',
 E'Cher client,\n\nNous avons détecté une transaction suspecte sur votre compte. Votre compte sera BLOQUÉ sous 24 heures si vous ne confirmez pas vos informations.\n\nCliquez ici pour sécuriser votre compte : http://belfius-securise.com/verifier\n\nCordialement,\nService Sécurité Belfius',
 '[{"quote": "service@belfius-securise.com", "note": "Regardez ce qui vient APRÈS le @ : belfius-securise.com. Ce n''est pas Belfius. La vraie banque utilise toujours @belfius.be. Ce qui est AVANT le @ (« service ») peut être choisi par l''escroc."}, {"quote": "BLOQUÉ sous 24 heures si vous ne confirmez pas vos informations", "note": "On vous fait peur et on vous presse. Une vraie banque ne fait jamais cela."}, {"quote": "Cher client", "note": "Pas de nom. Votre banque connaît votre nom."}, {"quote": "http://belfius-securise.com/verifier", "note": "Lien étrange qui n''est pas de Belfius. Ne cliquez pas !"}]'::jsonb,
 10),

('fr-BE', 'email',
 'SPF Finances <noreply@minfin-remboursement.be>',
 'Vous avez droit à un remboursement de 423,50 €',
 E'Cher contribuable,\n\nAprès vérification, vous avez droit à un remboursement d''impôts de 423,50 €. Remplissez vite vos informations pour recevoir le montant.\n\nCliquez ici : http://minfin-remboursement.be/reclamer\n\nSPF Finances',
 '[{"quote": "noreply@minfin-remboursement.be", "note": "Regardez après le @ : minfin-remboursement.be. Ce n''est PAS le SPF Finances. Le vrai domaine est minfin.fed.be."}, {"quote": "Cher contribuable", "note": "Salutation générique sans votre nom. Le SPF Finances connaît votre identité."}, {"quote": "droit à un remboursement d''impôts de 423,50 €", "note": "La promesse d''argent est un appât classique. Le SPF Finances ne communique jamais un remboursement par e-mail avec un lien."}, {"quote": "http://minfin-remboursement.be/reclamer", "note": "Lien étrange, ce n''est pas myminfin.be. Ne cliquez pas."}]'::jsonb,
 20),

('fr-BE', 'email',
 'itsme <info@itsme-controle.org>',
 'Confirmez vos informations itsme',
 E'Madame, Monsieur,\n\nNous vous demandons de confirmer à nouveau vos informations itsme. Cliquez sur le lien ci-dessous et connectez-vous avec votre identifiant et votre mot de passe.\n\nhttp://itsme-controle.org/connexion\n\nMerci,\nitsme',
 '[{"quote": "info@itsme-controle.org", "note": "Regardez après le @ : itsme-controle.org. Le vrai domaine est itsme.be — rien d''autre."}, {"quote": "Madame, Monsieur", "note": "Salutation générique. Une vraie organisation connaît votre nom."}, {"quote": "connectez-vous avec votre identifiant et votre mot de passe", "note": "itsme fonctionne via votre application personnelle et ne demande JAMAIS votre mot de passe par e-mail. Toujours du hameçonnage."}, {"quote": "http://itsme-controle.org/connexion", "note": "Lien étrange. Utilisez itsme uniquement via l''application officielle ou via itsme.be."}]'::jsonb,
 30);

-- ======== INBOX (fr-BE) ========
INSERT INTO inbox_messages
  (locale, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- 1. PHISHING — Belfius
('fr-BE',
 'Belfius',
 'service@belfius-securise.com',
 'Regardez après le @ : belfius-securise.com. Le vrai Belfius utilise toujours @belfius.be.',
 'aujourd''hui 08:42',
 'Important : votre compte va être bloqué',
 'Cher client, nous avons détecté une transaction suspecte sur votre...',
 E'<div class="eml fam-bank" style="--brand:#c30045;--cta:#c30045"><div class="eml-top"><span class="eml-logo">Belfius</span></div><div class="eml-body"><p>Cher client,</p><p>Nous avons détecté une transaction suspecte sur votre compte. Pour éviter tout abus, votre compte sera BLOQUÉ sous 24 heures si vous ne confirmez pas vos informations.</p><p>Confirmez immédiatement via {{link:0}}.</p><p>Cordialement,<br>Service Sécurité Belfius</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 Belfius</p></div></div>',
 '[{"label":"cette page sécurisée","real_url":"http://belfius-securise.com/verifier","suspicious":true,"warning":"Ce lien ne va PAS vers belfius.be mais vers belfius-securise.com. C''est un faux site qui imite Belfius."}]'::jsonb,
 TRUE,
 '["L''adresse de l''expéditeur ne finit pas par @belfius.be","Menace d''un blocage sous 24 heures — création de panique","Salutation « Cher client » sans votre nom","Le lien mène à belfius-securise.com, pas à belfius.be"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. Belfius ne vous envoie jamais d''e-mail sous pression pour confirmer vos informations. En cas de doute, ouvrez vous-même l''application Belfius Mobile ou appelez Card Stop (078 170 170) pour bloquer votre carte.',
 10),

-- 2. REAL — Médecin
('fr-BE',
 'Cabinet médical des Tilleuls',
 'cabinet@cabinet-tilleuls.be',
 'L''adresse finit par le domaine du cabinet — normal.',
 'aujourd''hui 09:15',
 'Rappel : votre rendez-vous demain à 10h15',
 'Chère Madame Dubois, rappel de votre rendez-vous...',
 E'Chère Madame Dubois,\n\nCeci est un rappel de votre rendez-vous avec le Dr Vermeulen demain à 10h15.\n\nPour annuler ou reporter, appelez le 02 123 45 67.\n\nÀ demain.\n\nCabinet médical des Tilleuls\nRue de la Loi 12, Bruxelles',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Salutation personnelle avec votre nom","Aucun lien, aucun bouton","Numéro de téléphone que vous pouvez appeler vous-même","Pas de demande d''informations ou d''argent","Information concrète et attendue"]'::jsonb,
 'C''est un simple rappel de rendez-vous. Pas de liens, pas d''informations demandées — vous pouvez simplement appeler si vous voulez modifier quelque chose.',
 20),

-- 3. PHISHING — SPF Finances
('fr-BE',
 'SPF Finances',
 'noreply@minfin-remboursement.be',
 'Pas @minfin.fed.be — donc pas vraiment du SPF Finances, même si le nom apparaît.',
 'aujourd''hui 10:03',
 'Vous avez droit à un remboursement de 423,50 €',
 'Après vérification, vous avez droit à un remboursement...',
 E'<div class="eml fam-gov" style="--brand:#005a9c;--cta:#005a9c"><div class="eml-top"><span class="eml-logo">SPF Finances</span></div><div class="eml-body"><p>Cher contribuable,</p><p>Après vérification, vous avez droit à un remboursement d''impôts de 423,50 €.</p><p>Remplissez vos informations pour recevoir le montant sous 3 jours ouvrables : {{link:0}}.</p><p>SPF Finances</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 SPF Finances</p></div></div>',
 '[{"label":"Mon espace MyMinfin","real_url":"http://minfin-remboursement.be/reclamer","suspicious":true,"warning":"La vraie adresse est myminfin.be. Ce lien mène à minfin-remboursement.be — un faux site."}]'::jsonb,
 TRUE,
 '["Expéditeur @minfin-remboursement.be, pas @minfin.fed.be","Le SPF Finances n''envoie JAMAIS d''e-mail concernant les remboursements","Promet de l''argent pour vous faire cliquer","Le lien mène à un site inconnu"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. Le SPF Finances communique sur les remboursements via MyMinfin ou par courrier — jamais par e-mail avec un lien. En cas de doute : connectez-vous vous-même sur myminfin.be avec itsme ou votre eID.',
 30),

-- 4. PHISHING — bpost
('fr-BE',
 'bpost Suivi',
 'suivi@bpost-livraison.info',
 'Le vrai domaine est bpost.be. « .info » est souvent suspect.',
 'hier 16:48',
 'Votre colis n''a pas pu être livré',
 'Votre colis vous attend. Des frais d''importation restent impayés...',
 E'<div class="eml fam-parcel" style="--brand:#e30613;--cta:#e30613"><div class="eml-hero"><span class="eml-logo">bpost</span></div><div class="eml-body"><p>Cher client,</p><p>Votre colis est en attente au centre de tri. Des frais d''importation restent impayés (1,95 €).</p><p>Payez immédiatement pour éviter un retard : {{link:0}}</p><p>bpost</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 bpost</p></div></div>',
 '[{"label":"bpost-livraison.info/payer","real_url":"http://bpost-livraison.info/payer","suspicious":true,"warning":"La vraie adresse de bpost est bpost.be. Les domaines en « .info » sont très utilisés pour des arnaques."}]'::jsonb,
 TRUE,
 '["Petit montant (1,95 €) pour que vous payiez sans réfléchir","Expéditeur @bpost-livraison.info au lieu de @bpost.be","« Payez immédiatement » — pression temporelle","Pas de nom, salutation générique"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. bpost ne demande jamais de frais d''importation par e-mail. Vous attendez un colis ? Vérifiez vous-même via l''application officielle My bpost ou sur bpost.be.',
 40),

-- 5. REAL — Bibliothèque
('fr-BE',
 'Bibliothèque de Bruxelles',
 'accueil@bibliotheque.bruxelles.be',
 'Domaine officiel de la Ville de Bruxelles — correct.',
 'hier 11:22',
 'Votre livre emprunté doit être rendu',
 'Chère Madame Dubois, rappel que votre livre...',
 E'Chère Madame Dubois,\n\nCeci est un rappel que le livre « Le Chagrin des Belges » doit être retourné dans une succursale de la Bibliothèque de Bruxelles avant le vendredi 28 avril.\n\nDes questions ? Appelez le 02 279 37 60 ou passez nous voir.\n\nCordialement,\nBibliothèque de Bruxelles',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Salutation personnelle","Information concrète sur votre livre et la date","Aucun lien, aucun paiement","Numéro de téléphone que vous pouvez appeler vous-même"]'::jsonb,
 'C''est un vrai rappel de votre bibliothèque. Aucun danger.',
 50),

-- 6. PHISHING — itsme
('fr-BE',
 'itsme',
 'info@itsme-controle.org',
 'Le vrai domaine est itsme.be. « .org » sur itsme est suspect.',
 'avant-hier 14:30',
 'Confirmez vos informations itsme',
 'Madame, Monsieur, nous vous demandons de confirmer à nouveau...',
 E'<div class="eml fam-gov" style="--brand:#ff4612;--cta:#ff4612;--logo:#e53f10"><div class="eml-top"><span class="eml-logo">itsme®</span></div><div class="eml-body"><p>Madame, Monsieur,</p><p>Dans le cadre d''un contrôle de sécurité, nous vous demandons de confirmer à nouveau vos informations itsme.</p><p>Connectez-vous via {{link:0}} et saisissez votre identifiant et votre mot de passe.</p><p>Merci,<br>itsme</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 itsme®</p></div></div>',
 '[{"label":"cette page sécurisée","real_url":"http://itsme-controle.org/connexion","suspicious":true,"warning":"itsme ne demande JAMAIS votre mot de passe par e-mail. La vraie adresse est itsme.be — pas itsme-controle.org. itsme fonctionne uniquement via sa propre application."}]'::jsonb,
 TRUE,
 '["Expéditeur @itsme-controle.org — pas @itsme.be","Demande votre identifiant ET votre mot de passe (itsme ne fait JAMAIS cela, puisque itsme fonctionne sans mot de passe)","Salutation générique « Madame, Monsieur »","Lien vers une adresse inconnue en « .org »"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. itsme fonctionne via votre application GSM avec empreinte digitale ou code — jamais par e-mail avec un lien. Utilisez itsme uniquement via l''application officielle.',
 60),

-- 7. REAL — Proximus
('fr-BE',
 'Proximus',
 'no-reply@proximus.be',
 'L''expéditeur @proximus.be est le domaine officiel — correct.',
 'il y a 3 jours',
 'Votre facture d''avril est disponible',
 'Cher client, votre facture de 49,95 € est disponible dans MyProximus...',
 E'<div class="eml fam-tech" style="--brand:#5c2d91;--cta:#5c2d91"><div class="eml-top"><span class="eml-logo">Proximus</span></div><div class="eml-body"><p>Chère Madame Dubois,</p><p>Votre facture Proximus de 49,95 € pour le mois d''avril est disponible dans MyProximus.</p><p>Vous pouvez consulter la facture en vous connectant vous-même à proximus.be/myproximus (tapez cette adresse vous-même dans votre navigateur ou utilisez l''application MyProximus).</p><p>Le montant sera prélevé automatiquement sur votre compte le 1er mai.</p><p>Service client Proximus</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 Proximus</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Expéditeur @proximus.be (réel)","Salutation personnelle","Le montant et la date correspondent à votre abonnement","Pas de lien cliquable — on vous demande de vous connecter VOUS-MÊME","Facture mensuelle attendue"]'::jsonb,
 'C''est une vraie notification de facture Proximus. Attention : même pour un vrai message, il est plus prudent de NE PAS cliquer sur les liens mais d''aller vous-même sur le site ou l''application.',
 70),

-- 8. PHISHING — Microsoft
('fr-BE',
 'Microsoft',
 'support@microsoft-security-check.com',
 'Le vrai domaine Microsoft est microsoft.com, pas microsoft-security-check.com.',
 'il y a 4 jours',
 'Avertissement : votre compte est bloqué',
 'Votre compte Microsoft est bloqué suite à une activité suspecte...',
 E'<div class="eml fam-tech" style="--brand:#0067b8;--cta:#0067b8"><div class="eml-top"><span class="eml-logo">Microsoft</span></div><div class="eml-body"><p>Cher utilisateur,</p><p>Votre compte Microsoft est temporairement bloqué suite à des tentatives de connexion suspectes depuis la Russie.</p><p>Si vous ne déverrouillez pas votre compte dans les 12 heures, vous perdrez tous vos fichiers.</p><p>Déverrouillez votre compte : {{link:0}}</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 Microsoft</p></div></div>',
 '[{"label":"Déverrouiller le compte","real_url":"http://microsoft-security-check.com/unlock","suspicious":true,"warning":"Microsoft n''utilise jamais de domaines avec des tirets comme microsoft-security-check.com. C''est faux."}]'::jsonb,
 TRUE,
 '["Panique : « vous perdrez tous vos fichiers »","Expéditeur étrange, pas @microsoft.com","Menace de connexion depuis un autre pays","Compte à rebours (12 heures) pour vous presser"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. Microsoft ne vous appelle ni ne vous envoie jamais d''e-mail non sollicité au sujet de comptes bloqués. Vous recevez cela ? Ignorez et connectez-vous vous-même sur account.microsoft.com pour vérifier.',
 80),

-- 9. REAL — Pharmacie
('fr-BE',
 'Pharmacie Dubois',
 'contact@pharmacie-dubois.be',
 'Domaine propre de la pharmacie — correct.',
 'il y a 5 jours',
 'Vos médicaments sont prêts',
 'Vos médicaments sont prêts à la Pharmacie Dubois. Vous pouvez les retirer...',
 E'Chère Madame Dubois,\n\nVos médicaments sont prêts à la Pharmacie Dubois, Rue de la Loi 12.\n\nNous sommes ouverts aujourd''hui jusqu''à 18h30. Apportez votre bon de retrait ou votre carte d''identité.\n\nDes questions ? Appelez le 02 111 22 33.\n\nPharmacie Dubois',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Salutation personnelle","Pharmacie connue, domaine propre","Information concrète : adresse, horaires","Aucun lien, aucun paiement","Numéro de téléphone que vous pouvez appeler vous-même"]'::jsonb,
 'C''est un message normal de votre pharmacie. Aucun danger.',
 90),

-- 10. PHISHING — Bol.com concours
('fr-BE',
 'Bol.com',
 'concours@bol-concours.net',
 'Les vrais e-mails Bol.com viennent de @bol.com, pas de @bol-concours.net.',
 'il y a 6 jours',
 'Félicitations ! Vous avez gagné un iPhone 15',
 'Vous êtes notre heureux gagnant ! Réclamez votre prix sous 2 heures...',
 E'<div class="eml fam-retail" style="--brand:#0000a4;--cta:#0000a4"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">bol.com</span></div><div class="eml-body"><p>Cher client,</p><p>Félicitations ! Vous avez été tiré au sort parmi des milliers de participants comme notre gagnant d''un iPhone 15 flambant neuf.</p><p>Réclamez votre prix sous 2 heures en payant une petite participation aux frais d''envoi : {{link:0}}</p><p>Équipe Bol.com Concours</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 bol.com</p></div></div>',
 '[{"label":"Réclamer votre prix","real_url":"http://bol-concours.net/reclamer","suspicious":true,"warning":"Bol.com n''utilise que bol.com. Une « participation aux frais d''envoi » pour un prix gagné est toujours une arnaque."}]'::jsonb,
 TRUE,
 '["Vous n''avez jamais participé à un concours","Demande une « participation aux frais d''envoi » — un prix ne se paye jamais","Pression : « sous 2 heures »","Expéditeur @bol-concours.net au lieu de @bol.com"]'::jsonb,
 '[]'::jsonb,
 'C''est du hameçonnage. On ne peut pas gagner un prix auquel on n''a pas participé. Un vrai concours ne demande jamais des frais de port à l''avance.',
 100);


