-- ============================================================
-- GEVORDERD (advanced difficulty) — subtiele phishing
-- Professionele opmaak, geen spelfouten, bijna-correcte domeinen.
-- Bedoeld voor gebruikers die de basis al beheersen.
-- ============================================================

INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty) VALUES

('nl', 'both',
 'Rabobank',
 'noreply@rabobank-authenticatie.com',
 'Kijk goed na de @: rabobank-authenticatie.com. De echte Rabobank stuurt altijd vanuit @rabobank.nl.',
 'vandaag 09:15',
 'Uw Rabo Scanner verloopt over 3 dagen — verleng nu',
 'Beste klant, uw Rabo Scanner-koppeling verloopt binnenkort. Zonder actie kunt u...',
 E'<div class="eml fam-bank" style="--brand:#fd6400;--cta:#fd6400;--logo:#d55400"><div class="eml-top"><span class="eml-logo">Rabobank</span></div><div class="eml-body"><p>Beste klant,</p><p>Uw Rabo Scanner-koppeling verloopt over 3 dagen. Na het verlopen kunt u niet meer inloggen in Mobiel Bankieren of betalingen goedkeuren.</p><p>Verleng uw Rabo Scanner via {{link:0}}. Het duurt minder dan 2 minuten.</p><p>Met vriendelijke groet,<br>Rabobank Klantendienst</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 Rabobank</p></div></div>',
 '[{"label":"Rabo Scanner verlengen","real_url":"http://rabobank-authenticatie.com/scanner/verleng","suspicious":true,"warning":"Deze link gaat naar rabobank-authenticatie.com, niet naar rabobank.nl. Typ altijd zelf rabobank.nl in uw browser of open de Rabo-app."}]'::jsonb,
 TRUE,
 '["Afzender eindigt op .com in plaats van @rabobank.nl","De link gaat naar rabobank-authenticatie.com, geen Rabobank-domein","Tijdsdruk: over 3 dagen maar de bank belt u altijd persoonlijk voor dit soort zaken","De echte Rabo-app toont uw koppelstatus — daar kunt u het zelf controleren"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. Het domein rabobank-authenticatie.com lijkt op Rabobank, maar is het niet. De echte Rabobank gebruikt altijd @rabobank.nl. Open de Rabo-app rechtstreeks — nooit via een link in een e-mail.',
 100, 'advanced'),

('nl', 'both',
 'PostNL',
 'noreply@postnl-pakket.com',
 'Let op het domein: postnl-pakket.com. PostNL gebruikt @postnl.nl voor e-mails.',
 'gisteren 16:03',
 'Uw pakket wordt aangehouden — betaal €2,45 douanekosten',
 'Uw pakket met trackingnummer 3SPBR123456789 wordt aangehouden bij de douane...',
 E'<div class="eml fam-parcel" style="--brand:#f56900;--cta:#f56900"><div class="eml-hero"><span class="eml-logo">PostNL</span></div><div class="eml-body"><p>Geachte afzender,</p><p>Uw pakket met trackingnummer 3SPBR123456789 wordt aangehouden bij de douane. Om uw pakket vrij te geven, dient u een bedrag van €2,45 aan douanekosten te voldoen.</p><p>Betaal eenvoudig via {{link:0}}. Na betaling wordt uw pakket binnen 1-2 werkdagen bezorgd.</p><p>Met vriendelijke groet,<br>PostNL Bezorgservice</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 PostNL</p></div></div>',
 '[{"label":"Douanekosten betalen","real_url":"http://postnl-pakket.com/betalen?id=3SPBR123456789","suspicious":true,"warning":"Deze link gaat naar postnl-pakket.com, niet naar postnl.nl. Het is een namaakwebsite om uw betaalgegevens te stelen."}]'::jsonb,
 TRUE,
 '["Domein postnl-pakket.com is niet van PostNL — het echte adres is @postnl.nl","Kleine betaling om u snel te laten klikken zonder veel nadenken","Bij echte douanekosten ontvangt u een fysieke brief, geen e-mail met betaallink","Controleer trackingnummers altijd zelf op postnl.nl"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. De domeinnaam postnl-pakket.com lijkt op PostNL maar is het niet. Echte PostNL-e-mails komen van @postnl.nl. Bij werkelijke douanekosten ontvangt u een brief van de Douane zelf, nooit een e-mail met een betaallink.',
 110, 'advanced'),

('nl', 'both',
 'Belastingdienst',
 'mijn@belasting-terugave.nl',
 'Domein belasting-terugave.nl is niet van de overheid. De Belastingdienst gebruikt belastingdienst.nl.',
 'gisteren 11:47',
 'Uw belastingteruggave van €387,00 staat klaar',
 'Geachte belastingplichtige, wij hebben uw aangifte verwerkt en een teruggave...',
 E'<div class="eml fam-gov" style="--brand:#154273;--cta:#154273"><div class="eml-top"><span class="eml-logo">Belastingdienst</span></div><div class="eml-body"><p>Geachte belastingplichtige,</p><p>Wij hebben uw aangifte inkomstenbelasting verwerkt en vastgesteld dat u recht heeft op een teruggave van €387,00.</p><p>Om de teruggave te ontvangen, bevestig uw rekeningnummer via {{link:0}}. Zonder bevestiging kunnen wij het bedrag niet uitbetalen.</p><p>Met vriendelijke groet,<br>Belastingdienst Nederland</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 Belastingdienst</p></div></div>',
 '[{"label":"Rekeningnummer bevestigen","real_url":"http://belasting-terugave.nl/bevestig","suspicious":true,"warning":"Dit is geen officieel overheidsdomein. De echte Belastingdienst bereikt u via belastingdienst.nl of MijnOverheid. Vul nooit uw bankgegevens in via een link in een e-mail."}]'::jsonb,
 TRUE,
 '["Domein belasting-terugave.nl is geen overheidsdomein — let op de koppeltekens en het ontbrekende woord dienst","De Belastingdienst kent uw rekeningnummer al uit eerdere aangiften","Teruggave-berichten komen via MijnBelastingdienst of een brief, nooit met een betaallink","Controleer altijd via mijn.belastingdienst.nl of er werkelijk een teruggave is"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. De Belastingdienst stuurt geen e-mails met een link om uw rekeningnummer te bevestigen — zij kennen dit al. Controleer teruggaven altijd via mijn.belastingdienst.nl, nooit via een link in een e-mail.',
 120, 'advanced'),

('nl', 'both',
 'ABN AMRO',
 'noreply@abnamro.nl',
 'Het adres eindigt op @abnamro.nl — het officiële domein van de bank.',
 'gisteren 07:30',
 'Uw maandoverzicht van mei 2026 staat klaar',
 'Beste mevrouw Janssen, uw maandoverzicht van april is beschikbaar in...',
 E'<div class="eml fam-bank" style="--brand:#009286;--cta:#009286;--logo:#008c81"><div class="eml-top"><span class="eml-logo">ABN AMRO</span></div><div class="eml-body"><p>Beste mevrouw Janssen,</p><p>Uw maandoverzicht van mei 2026 is beschikbaar in Mijn ABN AMRO en in de ABN AMRO-app.</p><p>U vindt het overzicht onder Documenten → Rekeningafschriften.</p><p>Heeft u vragen? Bel ons op 0900-0024 (lokaal tarief).</p><p>Met vriendelijke groet,<br>ABN AMRO Bank</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 ABN AMRO</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Afzender @abnamro.nl is het officiële domein van de bank","Geen link in het bericht — de bank vraagt u zelf de app te openen","Persoonlijke aanhef met uw eigen naam","Geen vraag om wachtwoord, pincode of andere gegevens","Verwijst naar het officiële telefoonnummer van de bank"]'::jsonb,
 'Dit is een echt bericht. Let op hoe de bank nooit vraagt om op een link te klikken — ze verwijzen u naar de app of het officiële telefoonnummer. De afzender eindigt correct op @abnamro.nl.',
 130, 'advanced'),

('nl', 'both',
 'LinkedIn',
 'messages-noreply@linkedin.com',
 'Het adres eindigt op @linkedin.com — het officiële domein van LinkedIn.',
 'vandaag 08:52',
 'Jan de Vries wil graag met u connecten op LinkedIn',
 'Jan de Vries (Senior Accountmanager bij Philips) wil graag met u connecten...',
 E'<div class="eml fam-tech" style="--brand:#0a66c2;--cta:#0a66c2"><div class="eml-top"><span class="eml-logo">LinkedIn</span></div><div class="eml-body"><p>Jan de Vries wil graag met u connecten op LinkedIn.</p><p>Jan de Vries<br>Senior Accountmanager bij Philips<br>32 connecties</p><p>U kunt deze uitnodiging bekijken en accepteren of negeren in uw LinkedIn-profiel. Log daarvoor zelf in op linkedin.com.</p><p>U ontvangt dit bericht omdat u e-mailberichten van LinkedIn heeft ingeschakeld.</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 LinkedIn</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Afzender @linkedin.com is het officiële domein","Geen dringende vraag of betaalverzoek","Bericht bevat geen links die u ergens anders naartoe sturen","LinkedIn raadt aan zelf in te loggen op linkedin.com, niet via een link"]'::jsonb,
 'Dit is een echt LinkedIn-bericht. Tip: ook al is dit echt, het is nog veiliger om zelf naar linkedin.com te gaan dan op een link in de e-mail te klikken — zo weet u altijd zeker dat u op de echte site bent.',
 140, 'advanced'),

('en', 'both',
 'HM Revenue & Customs',
 'refunds@hmrc-gov-refund.com',
 'Note the domain: hmrc-gov-refund.com. Real HMRC emails come from @hmrc.gov.uk.',
 'yesterday 14:22',
 'Your tax refund of £312.00 is ready to process',
 'Dear taxpayer, we have calculated that you are entitled to a tax refund of...',
 E'<div class="eml fam-gov" style="--brand:#008476;--cta:#008476"><div class="eml-top"><span class="eml-logo">HM Revenue &amp; Customs</span></div><div class="eml-body"><p>Dear taxpayer,</p><p>Following a review of your tax records, we have calculated that you are entitled to a refund of £312.00 for the 2025-2026 tax year.</p><p>To receive your refund, please verify your bank details via {{link:0}}. Refunds not claimed within 14 days will be returned to HMRC.</p><p>Yours faithfully,<br>HM Revenue &amp; Customs</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 HM Revenue &amp; Customs</p></div></div>',
 '[{"label":"Claim your refund","real_url":"http://hmrc-gov-refund.com/claim","suspicious":true,"warning":"This link goes to hmrc-gov-refund.com, not hmrc.gov.uk. Real HMRC communications always use hmrc.gov.uk — never a .com address."}]'::jsonb,
 TRUE,
 '["Domain hmrc-gov-refund.com ends in .com, not .gov.uk — UK government sites always use .gov.uk","HMRC already holds your bank details from previous returns","Artificial deadline (14 days) creates pressure to act without thinking","Real HMRC refunds are processed automatically — they never ask you to verify bank details by email"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. HMRC never asks you to verify bank details via email. Any refund is paid automatically to the account on record. Check your tax position directly at gov.uk/personal-tax-account.',
 100, 'advanced'),

('en', 'both',
 'Royal Mail',
 'delivery@royalmail-parcel.co.uk',
 'Note: royalmail-parcel.co.uk is not Royal Mail. The official domain is royalmail.com.',
 'today 10:41',
 'Your parcel is being held — customs fee of £1.99 required',
 'We attempted to deliver your parcel but it requires a customs payment before...',
 E'<div class="eml fam-parcel" style="--brand:#de1212;--cta:#de1212"><div class="eml-hero"><span class="eml-logo">Royal Mail</span></div><div class="eml-body"><p>We attempted to deliver your parcel (reference RL123456789GB) but it is currently being held at our depot.</p><p>A customs fee of £1.99 is required before we can release your parcel for delivery. Once paid, your parcel will be delivered within 2 working days.</p><p>Pay the fee via {{link:0}}.</p><p>Royal Mail Customer Services</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 Royal Mail</p></div></div>',
 '[{"label":"Pay customs fee","real_url":"http://royalmail-parcel.co.uk/pay?ref=RL123456789GB","suspicious":true,"warning":"This link goes to royalmail-parcel.co.uk, not royalmail.com. This is a fake site designed to steal your payment details."}]'::jsonb,
 TRUE,
 '["Domain royalmail-parcel.co.uk is not Royal Mail — the official site is royalmail.com","Small fee amount (£1.99) designed to make you pay without thinking","Real customs charges come as physical cards through your letterbox, not email payment links","Check any Royal Mail reference on royalmail.com directly"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Royal Mail never requests customs payments via email. Genuine customs charges are delivered as physical notices. Check any parcel on royalmail.com directly.',
 110, 'advanced'),

('en', 'both',
 'Microsoft account team',
 'account-security@microsoft-accounts.net',
 'The real Microsoft uses @microsoft.com or @accountprotection.microsoft.com — never microsoft-accounts.net.',
 'today 07:18',
 'Unusual sign-in activity detected on your Microsoft account',
 'We detected an unusual sign-in to your Microsoft account from an unrecognised device...',
 E'<div class="eml fam-tech" style="--brand:#0067b8;--cta:#0067b8"><div class="eml-top"><span class="eml-logo">Microsoft account</span></div><div class="eml-body"><p>We detected an unusual sign-in to your Microsoft account.</p><p>Date: Today at 06:47<br>Location: Frankfurt, Germany<br>Device: Windows PC (unrecognised)</p><p>If this was you, you can ignore this message. If this was not you, your account may be at risk.</p><p>Secure your account immediately via {{link:0}}.</p><p>The Microsoft account team</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 Microsoft account</p></div></div>',
 '[{"label":"Review recent activity","real_url":"http://microsoft-accounts.net/security","suspicious":true,"warning":"This link goes to microsoft-accounts.net, not microsoft.com. Real Microsoft security alerts link to account.microsoft.com only."}]'::jsonb,
 TRUE,
 '["Domain microsoft-accounts.net is not Microsoft — the real domain is microsoft.com","Mentions a foreign location to trigger concern and make you act fast","Real Microsoft alerts link to account.microsoft.com, not third-party domains","Go directly to account.microsoft.com to check your sign-in history without clicking any link"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Microsoft security emails always come from @microsoft.com domains and link to account.microsoft.com. Check your account directly at account.microsoft.com — never via a link in a suspicious email.',
 120, 'advanced'),

('en', 'both',
 'GitHub',
 'noreply@github.com',
 'The address ends in @github.com — GitHub official domain.',
 'yesterday 22:05',
 'A new public key was added to your account',
 'A new SSH key was added to your GitHub account. If you did not add this key...',
 E'<div class="eml fam-tech" style="--brand:#24292f;--cta:#24292f"><div class="eml-top"><span class="eml-logo">GitHub</span></div><div class="eml-body"><p>A new public key was added to your GitHub account.</p><p>Key fingerprint: SHA256:AbCdEf1234...<br>Added: yesterday at 21:58</p><p>If you added this key, no action is needed.</p><p>If you did not add this key, visit your account security settings to remove it and consider changing your password.</p><p>The GitHub Team</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 GitHub</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Sender is @github.com — GitHub official domain","No link asking you to click — you are told to go to your settings yourself","Informational tone: tells you what happened without demanding immediate action","Explains what to do if it was not you, without creating panic"]'::jsonb,
 'This is a genuine GitHub notification. Notice it contains no links — it tells you to visit your settings yourself. This is how legitimate security notifications should work.',
 130, 'advanced'),

('en', 'both',
 'Spotify',
 'no-reply@spotify.com',
 'The address ends in @spotify.com — Spotify official domain.',
 '3 days ago',
 'Your Spotify Premium subscription has been renewed',
 'Hi there, your monthly Spotify Premium subscription has been renewed...',
 E'<div class="eml fam-retail" style="--brand:#1db954;--cta:#1db954"><div class="eml-hero"><span class="eml-logo" style="font-weight:800">Spotify</span></div><div class="eml-body"><p>Hi there,</p><p>Your monthly Spotify Premium subscription has been renewed.</p><p>Amount charged: £10.99<br>Date: 3 days ago<br>Payment method: Visa ending in 4242</p><p>You can manage your subscription and view past invoices in your account settings at spotify.com/account.</p><p>Thanks for being a Premium member.<br>The Spotify Team</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 Spotify</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Sender @spotify.com is Spotify official domain","Shows the exact amount and last 4 digits of card — matches what you would expect","No link demanding immediate action","Refers you to account settings at spotify.com, not a separate domain"]'::jsonb,
 'This is a genuine Spotify renewal receipt. The email shows exactly what was charged and tells you to manage your account at spotify.com. No suspicious links or urgent demands.',
 140, 'advanced'),

('fr', 'both',
 'Crédit Agricole',
 'securite@credit-agricole-services.com',
 'Domaine credit-agricole-services.com : ce n’est pas Crédit Agricole. Le vrai domaine est credit-agricole.fr.',
 'hier 15:33',
 'Votre accès à votre espace client est temporairement suspendu',
 'Cher client, nous avons détecté une activité inhabituelle sur votre compte…',
 E'<div class="eml fam-bank" style="--brand:#006a4e;--cta:#006a4e"><div class="eml-top"><span class="eml-logo">CRÉDIT AGRICOLE</span></div><div class="eml-body"><p>Cher client,</p><p>Nous avons détecté une activité inhabituelle sur votre compte Crédit Agricole. Par mesure de sécurité, votre accès a été temporairement suspendu.</p><p>Pour rétablir votre accès, veuillez vérifier votre identité via {{link:0}}. Sans action de votre part sous 48 heures, votre compte sera définitivement bloqué.</p><p>Cordialement,<br>Le Service Sécurité Crédit Agricole</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 CRÉDIT AGRICOLE</p></div></div>',
 '[{"label":"Vérifier mon identité","real_url":"http://credit-agricole-services.com/verifier","suspicious":true,"warning":"Ce lien mène vers credit-agricole-services.com, pas vers credit-agricole.fr. C’est un faux site qui imite votre banque."}]'::jsonb,
 TRUE,
 '["Le domaine credit-agricole-services.com n’est pas celui de la banque — le vrai est credit-agricole.fr","La menace de blocage définitif en 48 h crée une pression artificielle","Le Crédit Agricole ne demande jamais de vérifier votre identité par e-mail","Connectez-vous directement sur credit-agricole.fr ou appelez le numéro au dos de votre carte"]'::jsonb,
 '[]'::jsonb,
 'Il s’agit de phishing. Le Crédit Agricole ne suspend pas les comptes par e-mail et ne vous demande pas de vérifier votre identité via un lien. Connectez-vous directement sur credit-agricole.fr ou appelez le numéro inscrit au dos de votre carte.',
 100, 'advanced'),

('fr', 'both',
 'La Poste',
 'suivi@laposte-livraison.fr',
 'Domaine laposte-livraison.fr : ce n’est pas La Poste. L’adresse officielle est @laposte.fr.',
 'aujourd’hui 11:08',
 'Votre colis est retenu — réglez les frais de douane (2,99 €)',
 'Votre colis (référence LP123456789FR) est actuellement retenu en douane…',
 E'<div class="eml fam-parcel" style="--brand:#ffd100;--cta:#ffd100;--cta-ink:#003366"><div class="eml-hero"><span class="eml-logo">LA POSTE</span></div><div class="eml-body"><p>Votre colis (référence LP123456789FR) est actuellement retenu en douane.</p><p>Pour procéder à la livraison, des frais de douane d’un montant de 2,99 € doivent être réglés.</p><p>Effectuez le paiement via {{link:0}}. Après validation, votre colis sera livré sous 2 jours ouvrables.</p><p>La Poste — Service Clients</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 LA POSTE</p></div></div>',
 '[{"label":"Payer les frais","real_url":"http://laposte-livraison.fr/payer?ref=LP123456789FR","suspicious":true,"warning":"Ce lien mène vers laposte-livraison.fr, pas vers laposte.fr. C’est un faux site conçu pour voler vos données bancaires."}]'::jsonb,
 TRUE,
 '["Le domaine laposte-livraison.fr n’est pas celui de La Poste — le vrai est @laposte.fr","Un petit montant (2,99 €) pour que vous payiez sans réfléchir","Les vrais frais de douane sont notifiés par un avis papier dans votre boîte aux lettres, jamais par un lien e-mail","Vérifiez tout colis directement sur laposte.fr"]'::jsonb,
 '[]'::jsonb,
 'Il s’agit de phishing. La Poste ne demande pas le règlement de frais de douane par e-mail avec un lien de paiement. Les vrais frais de douane sont notifiés par courrier physique. Vérifiez votre colis directement sur laposte.fr.',
 110, 'advanced'),

('fr', 'both',
 'Direction Générale des Finances Publiques',
 'remboursement@impots-gouv.net',
 'impots-gouv.net n’est pas un domaine officiel. Le vrai service utilise impots.gouv.fr.',
 'hier 09:55',
 'Votre remboursement d’impôts de 274 € est disponible',
 'Madame, Monsieur, suite au traitement de votre déclaration, vous bénéficiez…',
 E'<div class="eml fam-gov" style="--brand:#000091;--cta:#000091"><div class="eml-top"><span class="eml-logo">impots.gouv.fr</span></div><div class="eml-body"><p>Madame, Monsieur,</p><p>Suite au traitement de votre déclaration de revenus, vous bénéficiez d’un remboursement de 274,00 €.</p><p>Afin de procéder au virement, veuillez confirmer votre relevé d’identité bancaire (RIB) via {{link:0}}. Passé un délai de 15 jours, le remboursement sera annulé.</p><p>Cordialement,<br>Direction Générale des Finances Publiques</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 impots.gouv.fr</p></div></div>',
 '[{"label":"Confirmer mon RIB","real_url":"http://impots-gouv.net/confirmer-rib","suspicious":true,"warning":"Ce lien mène vers impots-gouv.net — pas impots.gouv.fr. Les sites officiels français utilisent toujours le domaine .gouv.fr."}]'::jsonb,
 TRUE,
 '["impots-gouv.net n’est pas un site gouvernemental — les sites officiels français utilisent .gouv.fr","La DGFiP connaît déjà votre RIB et rembourse automatiquement — elle ne vous le demande jamais par e-mail","L’échéance de 15 jours crée une pression artificielle","Vérifiez votre situation fiscale directement sur impots.gouv.fr"]'::jsonb,
 '[]'::jsonb,
 'Il s’agit de phishing. Les remboursements d’impôts sont effectués automatiquement sur le compte connu du fisc. La DGFiP ne demande jamais de confirmer un RIB par e-mail. Vérifiez toujours sur impots.gouv.fr.',
 120, 'advanced'),

('fr', 'both',
 'Doctolib',
 'notification@doctolib.fr',
 'L’adresse se termine par @doctolib.fr — le domaine officiel de la plateforme.',
 'aujourd’hui 08:00',
 'Rappel : votre rendez-vous demain à 10h30 — Dr Martin',
 'Bonjour, voici un rappel pour votre rendez-vous de demain avec le Dr Martin…',
 E'<div class="eml fam-tech" style="--brand:#107aca;--cta:#107aca"><div class="eml-top"><span class="eml-logo">Doctolib</span></div><div class="eml-body"><p>Bonjour,</p><p>Voici un rappel pour votre rendez-vous de demain :</p><p>• Praticien : Dr Sophie Martin — Médecin généraliste<br>• Date : demain à 10h30<br>• Adresse : 12 rue des Lilas, 75011 Paris</p><p>Pour annuler ou reporter, connectez-vous à votre espace Doctolib sur doctolib.fr.</p><p>Doctolib</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 Doctolib</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["L’expéditeur @doctolib.fr est le domaine officiel","Pas de lien à cliquer — vous êtes renvoyé vers doctolib.fr pour gérer le rendez-vous","Informations concrètes et attendues (praticien, date, adresse)","Aucune demande de paiement ni d’informations personnelles"]'::jsonb,
 'Il s’agit d’un vrai rappel Doctolib. Notez qu’il ne contient aucun lien de paiement ou demande d’informations sensibles — seulement les détails du rendez-vous et une invitation à gérer cela sur doctolib.fr.',
 130, 'advanced'),

('fr', 'both',
 'Amazon',
 'shipment-tracking@amazon.fr',
 'L’adresse se termine par @amazon.fr — le domaine officiel d’Amazon France.',
 'avant-hier 17:45',
 'Votre commande a été expédiée — livraison prévue vendredi',
 'Bonjour, bonne nouvelle : votre commande est en route. Voici les détails…',
 E'<div class="eml fam-retail" style="--brand:#232f3e;--cta:#232f3e"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">amazon</span></div><div class="eml-body"><p>Bonjour,</p><p>Bonne nouvelle : votre commande est en route !</p><p>📦 Commande n° 406-1234567-8901234<br>Livraison estimée : vendredi entre 14h et 18h<br>Transporteur : Amazon Logistics</p><p>Vous pouvez suivre votre colis dans la rubrique « Mes commandes » de votre compte Amazon sur amazon.fr.</p><p>Merci de votre confiance.<br>Amazon</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 amazon</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["L’expéditeur @amazon.fr est le domaine officiel d’Amazon France","Numéro de commande concret — vérifiable dans votre compte","Pas de demande de paiement ou d’informations bancaires","Vous êtes renvoyé vers amazon.fr pour le suivi, pas vers un domaine externe"]'::jsonb,
 'Il s’agit d’un vrai e-mail d’Amazon. Il contient un numéro de commande concret et vous renvoie vers amazon.fr pour le suivi. Aucune demande de paiement ni d’informations personnelles.',
 140, 'advanced'),

('de', 'both',
 'Sparkasse',
 'sicherheit@sparkasse-online.de',
 'Achtung: sparkasse-online.de ist nicht die echte Sparkasse. Das offizielle Domain ist sparkasse.de.',
 'gestern 16:21',
 'Wichtige Sicherheitsprüfung Ihres Kontos erforderlich',
 'Sehr geehrte/r Kundin/Kunde, im Rahmen unserer Sicherheitsmaßnahmen…',
 E'<div class="eml fam-bank" style="--brand:#ff0000;--cta:#ff0000;--logo:#fa0000"><div class="eml-top"><span class="eml-logo">Sparkasse</span></div><div class="eml-body"><p>Sehr geehrte/r Kundin/Kunde,</p><p>im Rahmen unserer Sicherheitsmaßnahmen bitten wir Sie, Ihre Online-Banking-Zugangsdaten einmalig zu bestätigen. Ohne diese Bestätigung wird Ihr Konto in 48 Stunden eingeschränkt.</p><p>Bestätigen Sie Ihre Daten über {{link:0}}.</p><p>Mit freundlichen Grüßen,<br>Ihr Sparkassen-Sicherheitsteam</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 Sparkasse</p></div></div>',
 '[{"label":"Zugangsdaten bestätigen","real_url":"http://sparkasse-online.de/sicherheit/bestaetigen","suspicious":true,"warning":"Dieser Link führt zu sparkasse-online.de, nicht zu sparkasse.de. Das ist eine gefälschte Website."}]'::jsonb,
 TRUE,
 '["sparkasse-online.de ist nicht das offizielle Domain — das echte ist sparkasse.de","Drohung mit Kontosperrung nach 48 Stunden erzeugt künstlichen Druck","Keine Sparkasse bittet per E-Mail um Bestätigung von Zugangsdaten","Melden Sie sich immer direkt über sparkasse.de an, nie über einen E-Mail-Link"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing. Kein Kreditinstitut fordert Sie per E-Mail auf, Zugangsdaten zu bestätigen. Loggen Sie sich direkt über sparkasse.de ein oder rufen Sie die Nummer auf Ihrer Bankkarte an.',
 100, 'advanced'),

('de', 'both',
 'DHL Paket',
 'tracking@dhl-pakete.com',
 'dhl-pakete.com ist nicht DHL. Die offizielle E-Mail-Domain von DHL lautet @dhl.de.',
 'heute 09:37',
 'Ihr Paket wird zurückgehalten — Zollgebühr von 2,99 € erforderlich',
 'Ihr Paket (Sendungsnummer 1Z999AA10123456784) befindet sich derzeit im Zoll…',
 E'<div class="eml fam-parcel" style="--brand:#ffcc00;--cta:#ffcc00;--cta-ink:#d40511"><div class="eml-hero"><span class="eml-logo">DHL</span></div><div class="eml-body"><p>Ihr Paket (Sendungsnummer 1Z999AA10123456784) befindet sich derzeit beim Zoll und kann erst nach Zahlung einer Zollgebühr von 2,99 € zugestellt werden.</p><p>Bitte begleichen Sie die Gebühr über {{link:0}}. Nach erfolgreicher Zahlung wird Ihr Paket innerhalb von 1-2 Werktagen zugestellt.</p><p>Mit freundlichen Grüßen,<br>DHL Kundenservice</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 DHL</p></div></div>',
 '[{"label":"Zollgebühr bezahlen","real_url":"http://dhl-pakete.com/zahlen?id=1Z999AA10123456784","suspicious":true,"warning":"Dieser Link führt zu dhl-pakete.com, nicht zu dhl.de. Es handelt sich um eine gefälschte Website."}]'::jsonb,
 TRUE,
 '["dhl-pakete.com ist nicht die offizielle DHL-Domain — das echte ist @dhl.de","Kleiner Betrag (2,99 €) soll dazu verleiten, ohne Nachdenken zu zahlen","Echte Zollgebühren werden durch einen physischen Benachrichtigungszettel angekündigt, nicht per E-Mail","Prüfen Sie Sendungen immer direkt auf dhl.de"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing. DHL fordert keine Zollgebühren per E-Mail mit Zahlungslink. Echte Zollbenachrichtigungen kommen als Papierzettel. Verfolgen Sie Sendungen direkt auf dhl.de.',
 110, 'advanced'),

('de', 'both',
 'Bundeszentralamt für Steuern',
 'erstattung@steuer-rueckzahlung.de',
 'steuer-rueckzahlung.de ist keine Behörden-Website. Offizielle Finanzämter nutzen die Domain bzst.de oder Ihr zuständiges Finanzamt.',
 'gestern 10:12',
 'Ihre Steuererstattung von 412 € steht zur Auszahlung bereit',
 'Sehr geehrte/r Steuerpflichtige/r, nach Prüfung Ihrer Einkommenssteuererklärung…',
 E'<div class="eml fam-gov" style="--brand:#003064;--cta:#003064"><div class="eml-top"><span class="eml-logo">Bundeszentralamt für Steuern</span></div><div class="eml-body"><p>Sehr geehrte/r Steuerpflichtige/r,</p><p>nach Prüfung Ihrer Einkommensteuererklärung für das Steuerjahr 2025 steht Ihnen eine Steuererstattung von 412,00 € zu.</p><p>Zur Auszahlung bestätigen Sie bitte Ihre Bankverbindung über {{link:0}}. Ohne Bestätigung innerhalb von 14 Tagen kann der Betrag nicht ausgezahlt werden.</p><p>Mit freundlichen Grüßen,<br>Bundeszentralamt für Steuern</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 Bundeszentralamt für Steuern</p></div></div>',
 '[{"label":"Bankverbindung bestätigen","real_url":"http://steuer-rueckzahlung.de/bestaetigen","suspicious":true,"warning":"steuer-rueckzahlung.de ist keine offizielle Behörden-Website. Deutsche Behörden nutzen immer .de-Domains wie bzst.de oder finanzamt.de."}]'::jsonb,
 TRUE,
 '["steuer-rueckzahlung.de ist kein offizielles Behörden-Domain — Finanzämter nutzen finanzamt.de oder ihr jeweiliges Landes-Domain","Das Finanzamt kennt Ihre Bankverbindung bereits aus früheren Steuerbescheiden","Die 14-Tage-Frist erzeugt künstlichen Druck","Erstattungen werden automatisch ausgezahlt — das Finanzamt fragt nie per E-Mail nach einer Bankverbindung"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing. Steuererstattungen werden automatisch an die bekannte Bankverbindung ausgezahlt. Das Finanzamt bittet nie per E-Mail um Bestätigung der Bankverbindung. Prüfen Sie Bescheide über Ihr ELSTER-Konto auf elster.de.',
 120, 'advanced'),

('de', 'both',
 'Amazon.de',
 'shipment-tracking@amazon.de',
 'Die Adresse endet auf @amazon.de — die offizielle Domain von Amazon Deutschland.',
 'vorgestern 18:30',
 'Ihre Bestellung wurde versandt — Lieferung voraussichtlich Freitag',
 'Hallo, Ihre Bestellung ist auf dem Weg zu Ihnen. Hier sind die Details…',
 E'<div class="eml fam-retail" style="--brand:#232f3e;--cta:#232f3e"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">amazon.de</span></div><div class="eml-body"><p>Hallo,</p><p>Ihre Bestellung ist auf dem Weg zu Ihnen!</p><p>📦 Bestellnummer: 302-1234567-8901234<br>Voraussichtliche Lieferung: Freitag zwischen 14 und 18 Uhr<br>Versanddienstleister: Amazon Logistics</p><p>Sie können Ihre Sendung im Bereich „Meine Bestellungen“ in Ihrem Amazon-Konto auf amazon.de verfolgen.</p><p>Vielen Dank für Ihren Einkauf.<br>Amazon</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 amazon.de</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Absender @amazon.de ist die offizielle Domain von Amazon Deutschland","Konkrete Bestellnummer — in Ihrem Konto nachprüfbar","Keine Zahlungsaufforderung oder Anfrage nach persönlichen Daten","Verweist auf amazon.de für die Sendungsverfolgung, nicht auf eine externe Domain"]'::jsonb,
 'Dies ist eine echte Amazon-Versandverfolgung. Sie enthält eine nachprüfbare Bestellnummer und verweist auf amazon.de. Keine verdächtigen Links, keine Zahlungsaufforderung.',
 130, 'advanced'),

('de', 'both',
 'LinkedIn',
 'messages-noreply@linkedin.com',
 'Die Adresse endet auf @linkedin.com — die offizielle Domain von LinkedIn.',
 'heute 08:14',
 'Markus Weber möchte sich mit Ihnen auf LinkedIn vernetzen',
 'Markus Weber (Senior Berater bei Deloitte) möchte sich mit Ihnen vernetzen…',
 E'<div class="eml fam-tech" style="--brand:#0a66c2;--cta:#0a66c2"><div class="eml-top"><span class="eml-logo">LinkedIn</span></div><div class="eml-body"><p>Markus Weber möchte sich mit Ihnen auf LinkedIn vernetzen.</p><p>Markus Weber<br>Senior Berater bei Deloitte<br>148 Kontakte</p><p>Sie können die Einladung in Ihrem LinkedIn-Profil annehmen oder ablehnen. Melden Sie sich dafür direkt auf linkedin.com an.</p><p>Sie erhalten diese Nachricht, weil Sie E-Mail-Benachrichtigungen von LinkedIn aktiviert haben.</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 LinkedIn</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Absender @linkedin.com ist die offizielle Domain","Keine dringende Aufforderung und keine Zahlungsanfrage","LinkedIn empfiehlt, sich direkt auf linkedin.com anzumelden, statt auf einen Link zu klicken","Keine externen Domains oder verdächtigen Links im Text"]'::jsonb,
 'Dies ist eine echte LinkedIn-Kontaktanfrage. Tipp: Auch wenn diese E-Mail echt ist, ist es noch sicherer, direkt auf linkedin.com zu gehen, statt auf einen Link in der E-Mail zu klicken.',
 140, 'advanced');

-- nl-BE en fr-BE: kopieën van nl/fr advanced-berichten met aangepaste locale.
INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty)
SELECT 'nl-BE', audience, sender_name, sender_address, sender_note, received_label,
       subject, preview, body, links, is_phishing, red_flags, green_flags,
       explanation, sort_order, difficulty
FROM inbox_messages
WHERE locale = 'nl' AND difficulty = 'advanced';

INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty)
SELECT 'fr-BE', audience, sender_name, sender_address, sender_note, received_label,
       subject, preview, body, links, is_phishing, red_flags, green_flags,
       explanation, sort_order, difficulty
FROM inbox_messages
WHERE locale = 'fr' AND difficulty = 'advanced';


-- Aanvullende advanced berichten om het totaal gelijk te maken aan normaal.
INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty) VALUES

('nl', 'both',
 'bol.com',
 'service@bol-service.com',
 'bol-service.com is niet bol.com. Echte bol.com-mails komen van @bol.com.',
 'vandaag 13:22',
 'Uw bestelling #1234567890 is geannuleerd — actie vereist',
 'Uw bestelling is geannuleerd wegens een probleem met uw betaling...',
 E'<div class="eml fam-retail" style="--brand:#0000a4;--cta:#0000a4"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">bol.com</span></div><div class="eml-body"><p>Beste klant,</p><p>Er was helaas een probleem met de betaling van uw bestelling #1234567890. Uw bestelling is daardoor geannuleerd.</p><p>Om uw bestelling opnieuw te plaatsen en uw betaalgegevens bij te werken, gaat u naar {{link:0}}.</p><p>Met vriendelijke groet,<br>bol.com Klantenservice</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 bol.com</p></div></div>',
 '[{"label":"Bestelling herstellen","real_url":"http://bol-service.com/betaling-bijwerken","suspicious":true,"warning":"bol-service.com is geen bol.com-domein. Het echte domein is altijd @bol.com. Typ zelf bol.com in uw browser."}]'::jsonb,
 TRUE,
 '["Domein bol-service.com is niet van bol.com — het echte is @bol.com","Geen ordernummer dat u kunt terugvinden in uw account","Vraagt om betaalgegevens bij te werken via een link — doet bol.com nooit zo","Controleer bestellingen altijd zelf in uw bol.com-account"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. Het domein bol-service.com is geen bol.com. Bol.com stuurt geen e-mails om betaalgegevens bij te werken via een link. Log altijd zelf in op bol.com om uw bestellingen te controleren.',
 150, 'advanced'),

('nl', 'both',
 'DHL',
 'noreply@dhl-bezorging.nl',
 'dhl-bezorging.nl is niet van DHL. Het officiële domein van DHL is dhl.nl of dhl.com.',
 'gisteren 10:55',
 'Bezorging mislukt — bevestig uw bezorgadres',
 'Wij konden uw pakket niet bezorgen. Bevestig uw adres om een nieuwe bezorging...',
 E'<div class="eml fam-parcel" style="--brand:#ffcc00;--cta:#ffcc00;--cta-ink:#d40511"><div class="eml-hero"><span class="eml-logo">DHL</span></div><div class="eml-body"><p>Geachte klant,</p><p>Wij hebben geprobeerd uw pakket (referentie DHL1234567890) te bezorgen, maar niemand was thuis.</p><p>Bevestig uw bezorgadres via {{link:0}} om een nieuwe bezorging te plannen. Uw pakket wordt 3 dagen bewaard.</p><p>Met vriendelijke groet,<br>DHL Bezorgservice</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 DHL</p></div></div>',
 '[{"label":"Bezorgadres bevestigen","real_url":"http://dhl-bezorging.nl/herplanning","suspicious":true,"warning":"Dit is niet dhl.nl of dhl.com. Het is een nagemaakte site die op DHL lijkt — bedoeld om uw persoonsgegevens of betaalgegevens te stelen."}]'::jsonb,
 TRUE,
 '["dhl-bezorging.nl is geen DHL-domein — het echte is dhl.nl","DHL vraagt nooit per e-mail om een adres te bevestigen via een externe link","Trackingnummers van DHL beginnen met specifieke patronen — controleer altijd op dhl.nl","De urgentie (3 dagen bewaard) is bedoeld om u snel te laten klikken"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. DHL vraagt u nooit via een e-mail-link om uw adres opnieuw te bevestigen. Controleer uw pakket altijd zelf via dhl.nl met het trackingnummer.',
 160, 'advanced'),

('nl', 'both',
 'Apple',
 'noreply@apple-id-info.com',
 'apple-id-info.com is geen Apple-domein. Apple stuurt meldingen altijd vanuit @apple.com.',
 'vandaag 06:41',
 'Uw Apple ID is gebruikt op een nieuw apparaat in Duitsland',
 'Uw Apple ID is zojuist aangemeld op een iPhone 15 in München...',
 E'<div class="eml fam-tech" style="--brand:#000000;--cta:#000000"><div class="eml-top"><span class="eml-logo">Apple</span></div><div class="eml-body"><p>Uw Apple ID (janssen.m@email.nl) is gebruikt om in te loggen op een nieuwe iPhone 15 in München, Duitsland.</p><p>Datum: vandaag om 06:38</p><p>Was dit u? Dan hoeft u niets te doen.</p><p>Was dit u niet? Beveilig uw account onmiddellijk via {{link:0}} om te voorkomen dat uw gegevens worden misbruikt.</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 Apple</p></div></div>',
 '[{"label":"Account beveiligen","real_url":"http://apple-id-info.com/beveiligen","suspicious":true,"warning":"apple-id-info.com is geen Apple-domein. Echte Apple-beveiligingsmeldingen linken altijd naar appleid.apple.com."}]'::jsonb,
 TRUE,
 '["apple-id-info.com is geen Apple-domein — het echte is @apple.com","Meldt een buitenlandse locatie om schrik aan te jagen","Echte Apple-beveiligingsmeldingen verwijzen naar appleid.apple.com, niet naar externe sites","Log zelf in via appleid.apple.com om recente aanmeldingen te controleren"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. Apple stuurt beveiligingsmeldingen altijd vanuit @apple.com en verwijst naar appleid.apple.com. Controleer uw account zelf via appleid.apple.com — nooit via een link in een e-mail.',
 170, 'advanced'),

('nl', 'both',
 'Coolblue',
 'noreply@coolblue.nl',
 'Het adres eindigt op @coolblue.nl — het officiële domein van Coolblue.',
 'vandaag 07:03',
 'Uw bestelling wordt morgen bezorgd tussen 10:00 en 12:00',
 'Beste mevrouw Janssen, uw bestelling met ordernummer 123456789 wordt morgen bezorgd...',
 E'<div class="eml fam-retail" style="--brand:#0090e3;--cta:#0090e3"><div class="eml-hero"><span class="eml-logo">Coolblue</span></div><div class="eml-body"><p>Beste mevrouw Janssen,</p><p>Goed nieuws: uw bestelling (ordernummer 123456789) wordt morgen bezorgd.</p><p>Bezorgmoment: morgen tussen 10:00 en 12:00<br>Adres: Dorpsstraat 12, 1234 AB Amsterdam</p><p>U hoeft niets te betalen bij de deur — alles is al voldaan.</p><p>Vragen? Bel ons op 010-7980090 of check de status in uw Coolblue-account.</p><p>Vriendelijke groet,<br>Coolblue</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 Coolblue</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Afzender @coolblue.nl is het officiële domein","Concrete bezorginformatie die overeenkomt met uw verwachte bestelling","Geen betaallink — alles is al voldaan","Verwijst naar eigen telefoonnummer en account, niet naar externe link"]'::jsonb,
 'Dit is een echte bezorgbevestiging van Coolblue. Let op: concrete ordernummer, geen betaalverzoek, en verwijs naar hun eigen kanalen. Echte bezorgmeldingen bevatten geen betaallinks.',
 180, 'advanced'),

('nl', 'both',
 'Google',
 'no-reply@accounts.google.com',
 'Het adres eindigt op @accounts.google.com — het officiële domein voor Google-beveiligingsmeldingen.',
 'gisteren 20:14',
 'Er is een nieuw apparaat aangemeld bij uw Google-account',
 'Er is een nieuwe aanmelding gedetecteerd op uw Google-account...',
 E'<div class="eml fam-tech" style="--brand:#4285f4;--cta:#4285f4;--logo:#3d7ae0"><div class="eml-top"><span class="eml-logo" style="font-weight:500">Google</span></div><div class="eml-body"><p>Er is een nieuwe aanmelding op uw Google-account gedetecteerd.</p><p>Apparaat: Windows-pc<br>Locatie: Amsterdam, Nederland<br>Tijdstip: gisteren om 20:11</p><p>Was dit u? Dan hoeft u niets te doen.</p><p>Was dit u niet? Ga dan zelf naar myaccount.google.com om uw wachtwoord te wijzigen en verdachte activiteit te bekijken.</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 Google</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Afzender @accounts.google.com is het officiële domein voor Google-meldingen","Geen link in het bericht — u wordt gevraagd zelf naar myaccount.google.com te gaan","Locatie Amsterdam past bij normaal gebruik","Informatieve toon zonder paniek of tijdsdruk"]'::jsonb,
 'Dit is een echte Google-aanmeldingsmelding. Let op hoe Google geen link stuurt om op te klikken, maar u vraagt zelf naar myaccount.google.com te gaan. Dat is precies hoe legitieme beveiligingsmeldingen horen te werken.',
 190, 'advanced'),

('nl', 'both',
 'NS Klantenservice',
 'klantenservice@ns.nl',
 'Het adres eindigt op @ns.nl — het officiële domein van NS.',
 '3 dagen geleden',
 'Uw treinticket voor 22 mei is gereed',
 'Beste mevrouw Janssen, uw ticket voor de reis Amsterdam-Rotterdam op 22 mei staat...',
 E'<div class="eml fam-parcel" style="--brand:#ffc917;--cta:#ffc917;--cta-ink:#003082"><div class="eml-hero"><span class="eml-logo">NS</span></div><div class="eml-body"><p>Beste mevrouw Janssen,</p><p>Uw treinticket voor de volgende reis is gereed:</p><p>Datum: woensdag 22 mei<br>Reis: Amsterdam Centraal → Rotterdam Centraal<br>Vertrek: 09:14 — Aankomst: 10:09<br>Klasse: 2e klas</p><p>Uw ticket staat in de NS-app. U kunt het ook bekijken via Mijn NS op ns.nl.</p><p>Goede reis!<br>NS</p></div><div class="eml-foot"><p>Dit is een automatisch verzonden bericht — antwoorden is niet mogelijk.</p><p>© 2026 NS</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Afzender @ns.nl is het officiële domein van NS","Concrete reisgegevens die u verwacht — datum, route, tijd","Geen betaalverzoek, geen link — verwijst naar de NS-app of ns.nl","Geen tijdsdruk of dreiging"]'::jsonb,
 'Dit is een echte NS-ticketbevestiging. Alle informatie klopt, er is geen betaallink en u wordt verwezen naar de NS-app of ns.nl voor details.',
 200, 'advanced'),

('en', 'both',
 'Amazon',
 'order-update@amazon-uk.com',
 'amazon-uk.com is not Amazon. Real Amazon UK emails come from @amazon.co.uk.',
 'today 14:07',
 'Your order has been cancelled — update your payment details',
 'We were unable to process payment for your order. Your order has been cancelled...',
 E'<div class="eml fam-retail" style="--brand:#232f3e;--cta:#232f3e"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">amazon</span></div><div class="eml-body"><p>Dear customer,</p><p>We were unable to process payment for your recent order. As a result, your order has been cancelled.</p><p>To reinstate your order and update your payment details, please visit {{link:0}} within 24 hours.</p><p>Kind regards,<br>Amazon Customer Service</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 amazon</p></div></div>',
 '[{"label":"Update payment details","real_url":"http://amazon-uk.com/payment-update","suspicious":true,"warning":"amazon-uk.com is not Amazon. The real domain is amazon.co.uk. Never update payment details via a link in an email — go directly to amazon.co.uk."}]'::jsonb,
 TRUE,
 '["Domain amazon-uk.com is not Amazon — the real domain is amazon.co.uk","Amazon never asks you to update payment details via an email link","The 24-hour deadline creates artificial urgency","Check your orders directly in your Amazon account at amazon.co.uk"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Amazon always sends emails from @amazon.co.uk and never asks you to update payment details via a link in an email. Check any order directly at amazon.co.uk.',
 150, 'advanced'),

('en', 'both',
 'Apple',
 'noreply@apple-account-verify.com',
 'apple-account-verify.com is not Apple. Real Apple emails come from @apple.com.',
 'today 05:58',
 'Your Apple ID was used to sign in on a new device in Poland',
 'Your Apple ID was just used to sign in on an iPhone 15 in Warsaw...',
 E'<div class="eml fam-tech" style="--brand:#000000;--cta:#000000"><div class="eml-top"><span class="eml-logo">Apple</span></div><div class="eml-body"><p>Your Apple ID (yourname@email.com) was used to sign in on a new iPhone 15 in Warsaw, Poland.</p><p>Date: today at 05:55</p><p>If this was you, no action is needed.</p><p>If this was not you, your account may be at risk. Secure your account immediately via {{link:0}}.</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 Apple</p></div></div>',
 '[{"label":"Secure your account","real_url":"http://apple-account-verify.com/secure","suspicious":true,"warning":"apple-account-verify.com is not Apple. Real Apple security alerts always link to appleid.apple.com — never to third-party domains."}]'::jsonb,
 TRUE,
 '["apple-account-verify.com is not Apple — real emails come from @apple.com","Mentions a foreign location to create alarm","Real Apple alerts link to appleid.apple.com, not external sites","Go directly to appleid.apple.com to review recent activity without clicking any link"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Apple security notifications always come from @apple.com and link to appleid.apple.com. Check your account directly at appleid.apple.com — never via a link in a suspicious email.',
 160, 'advanced'),

('en', 'both',
 'PayPal',
 'service@paypal-account.net',
 'paypal-account.net is not PayPal. All real PayPal emails come from @paypal.com.',
 'yesterday 11:34',
 'Your PayPal account has been temporarily limited',
 'We have noticed some unusual activity in your account. To restore full access...',
 E'<div class="eml fam-pay" style="--brand:#003087;--cta:#003087"><div class="eml-hero"><span class="eml-logo" style="font-style:italic;font-weight:800">PayPal</span></div><div class="eml-body"><p>Dear customer,</p><p>We have noticed some unusual activity in your PayPal account and have temporarily limited access as a precaution.</p><p>To restore full access, please confirm your identity via {{link:0}}. Failure to verify within 48 hours may result in permanent account suspension.</p><p>Kind regards,<br>PayPal Security Team</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 PayPal</p></div></div>',
 '[{"label":"Confirm your identity","real_url":"http://paypal-account.net/verify","suspicious":true,"warning":"paypal-account.net is not PayPal. All real PayPal emails come from @paypal.com. Log in directly at paypal.com."}]'::jsonb,
 TRUE,
 '["paypal-account.net is not PayPal — the real domain is paypal.com","Threat of permanent suspension creates urgency","PayPal never asks you to verify identity via an email link","Log in directly at paypal.com to check your account status"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. PayPal never asks you to verify your identity via an email link. All real PayPal communications come from @paypal.com. Check your account status by going directly to paypal.com.',
 170, 'advanced'),

('en', 'both',
 'Google',
 'no-reply@accounts.google.com',
 'The address ends in @accounts.google.com — Google official domain for security notifications.',
 'yesterday 19:42',
 'New sign-in on your Google account',
 'A new sign-in was detected on your Google account...',
 E'<div class="eml fam-tech" style="--brand:#4285f4;--cta:#4285f4;--logo:#3d7ae0"><div class="eml-top"><span class="eml-logo" style="font-weight:500">Google</span></div><div class="eml-body"><p>A new sign-in was detected on your Google account.</p><p>Device: Windows PC<br>Location: London, United Kingdom<br>Time: yesterday at 19:39</p><p>If this was you, no action is needed.</p><p>If this was not you, visit myaccount.google.com to change your password and review recent activity.</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 Google</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Sender @accounts.google.com is Google official domain for security alerts","No link to click — you are directed to myaccount.google.com directly","Location matches normal usage (UK)","Informational tone without panic or time pressure"]'::jsonb,
 'This is a genuine Google sign-in notification. Notice how Google does not include a link to click — it tells you to go to myaccount.google.com yourself. That is how legitimate security alerts work.',
 180, 'advanced'),

('en', 'both',
 'Amazon',
 'shipment-tracking@amazon.co.uk',
 'The address ends in @amazon.co.uk — Amazon UK official domain.',
 '2 days ago',
 'Your order has been dispatched — arriving tomorrow',
 'Great news! Your order is on its way and is expected to arrive tomorrow...',
 E'<div class="eml fam-retail" style="--brand:#232f3e;--cta:#232f3e"><div class="eml-hero"><span class="eml-logo" style="text-transform:lowercase;font-weight:800">amazon</span></div><div class="eml-body"><p>Great news! Your order is on its way.</p><p>📦 Order number: 203-1234567-8901234<br>Estimated delivery: tomorrow between 9am and 1pm<br>Carrier: Amazon Logistics</p><p>You can track your parcel in the Your Orders section of your Amazon account at amazon.co.uk.</p><p>Thank you for shopping with us.<br>Amazon</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 amazon</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Sender @amazon.co.uk is Amazon UK official domain","Concrete order number — verifiable in your account","No payment request or urgent action needed","Directs you to amazon.co.uk for tracking, not an external site"]'::jsonb,
 'This is a genuine Amazon dispatch notification. It contains a real order number and directs you to amazon.co.uk. No payment request, no urgent demands.',
 190, 'advanced'),

('en', 'both',
 'Microsoft',
 'microsoft-noreply@microsoft.com',
 'The address ends in @microsoft.com — Microsoft official domain.',
 '3 days ago',
 'Your Microsoft 365 subscription invoice for May',
 'Your monthly Microsoft 365 Personal invoice is now available...',
 E'<div class="eml fam-tech" style="--brand:#0067b8;--cta:#0067b8"><div class="eml-top"><span class="eml-logo">Microsoft</span></div><div class="eml-body"><p>Your monthly Microsoft 365 Personal invoice is now available.</p><p>Amount: £7.99<br>Date: 3 days ago<br>Payment method: Visa ending in 1234</p><p>You can view your full invoice and manage your subscription at account.microsoft.com.</p><p>Thank you,<br>Microsoft</p></div><div class="eml-foot"><p>This is an automated message — please do not reply.</p><p>© 2026 Microsoft</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Sender @microsoft.com is Microsoft official domain","Shows exact amount and last 4 digits of payment card","No urgent link to click — directs you to account.microsoft.com","Matches expected monthly subscription charge"]'::jsonb,
 'This is a genuine Microsoft subscription receipt. It shows the charge details and directs you to account.microsoft.com. No suspicious links, no urgent demands.',
 200, 'advanced'),

('fr', 'both',
 'Orange',
 'facture@orange-espace-client.fr',
 'orange-espace-client.fr nest pas Orange. Les mails officiels dOrange viennent de @orange.fr.',
 'hier 13:45',
 'Votre facture Orange de mai est impayée — réglez maintenant',
 'Votre facture de mai 2025 dun montant de 39,99 € na pas pu être prélevée...',
 E'<div class="eml fam-tech" style="--brand:#ff7900;--cta:#ff7900;--logo:#c75e00"><div class="eml-top"><span class="eml-logo" style="text-transform:lowercase">orange™</span></div><div class="eml-body"><p>Cher client,</p><p>Votre facture Orange de mai 2025 (39,99 €) na pas pu être prélevée sur votre compte. Pour éviter la suspension de votre ligne, réglez votre facture via {{link:0}} avant le 30 mai.</p><p>Cordialement,<br>Orange Service Facturation</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 orange™</p></div></div>',
 '[{"label":"Régler ma facture","real_url":"http://orange-espace-client.fr/paiement","suspicious":true,"warning":"orange-espace-client.fr nest pas Orange. Les mails dOrange viennent de @orange.fr. Connectez-vous directement sur orange.fr."}]'::jsonb,
 TRUE,
 '["Le domaine orange-espace-client.fr nest pas celui dOrange — le vrai est @orange.fr","La menace de suspension de ligne crée une pression artificielle","Orange ne demande jamais de régler une facture via un lien dans un e-mail","Connectez-vous directement sur orange.fr pour gérer votre facture"]'::jsonb,
 '[]'::jsonb,
 'Il sagit de phishing. Orange ne demande pas de régler des factures via un lien dans un e-mail. Les vrais e-mails dOrange viennent de @orange.fr. Gérez votre facture directement sur orange.fr.',
 150, 'advanced'),

('fr', 'both',
 'Apple',
 'noreply@apple-id-securite.com',
 'apple-id-securite.com nest pas Apple. Les vrais mails dApple viennent de @apple.com.',
 'aujourdhui 05:47',
 'Votre identifiant Apple a été utilisé depuis lAllemagne',
 'Votre identifiant Apple vient dêtre utilisé pour se connecter sur un iPhone à Berlin...',
 E'<div class="eml fam-tech" style="--brand:#000000;--cta:#000000"><div class="eml-top"><span class="eml-logo">Apple</span></div><div class="eml-body"><p>Votre identifiant Apple (votreprenom@email.fr) a été utilisé pour se connecter sur un nouvel iPhone 15 à Berlin, Allemagne.</p><p>Date : aujourdhui à 05:44</p><p>Était-ce vous ? Dans ce cas, aucune action nest requise.</p><p>Si ce nétait pas vous, sécurisez votre compte immédiatement via {{link:0}}.</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 Apple</p></div></div>',
 '[{"label":"Sécuriser mon compte","real_url":"http://apple-id-securite.com/securiser","suspicious":true,"warning":"apple-id-securite.com nest pas Apple. Les vraies alertes de sécurité Apple mènent toujours vers appleid.apple.com."}]'::jsonb,
 TRUE,
 '["apple-id-securite.com nest pas Apple — le vrai domaine est @apple.com","Mentionne une localisation étrangère pour provoquer la panique","Les vraies alertes Apple renvoient vers appleid.apple.com, pas vers des sites externes","Rendez-vous directement sur appleid.apple.com pour consulter les connexions récentes"]'::jsonb,
 '[]'::jsonb,
 'Il sagit de phishing. Les alertes de sécurité Apple viennent toujours de @apple.com et renvoient vers appleid.apple.com. Vérifiez votre compte directement sur appleid.apple.com.',
 160, 'advanced'),

('fr', 'both',
 'Assurance Maladie',
 'remboursement@ameli-sante.fr',
 'ameli-sante.fr nest pas lAssurance Maladie. Le vrai domaine est ameli.fr.',
 'avant-hier 09:21',
 'Votre remboursement de 58,40 € est disponible',
 'Suite à votre dernière consultation, vous avez droit à un remboursement de 58,40 €...',
 E'<div class="eml fam-gov" style="--brand:#0c419a;--cta:#0c419a"><div class="eml-top"><span class="eml-logo">l’Assurance Maladie</span></div><div class="eml-body"><p>Madame, Monsieur,</p><p>Suite à votre dernière consultation médicale, vous avez droit à un remboursement de 58,40 €.</p><p>Pour recevoir ce remboursement, veuillez mettre à jour votre RIB via {{link:0}}. Sans mise à jour, le remboursement ne pourra pas être versé.</p><p>Cordialement,<br>LAssurance Maladie</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 l’Assurance Maladie</p></div></div>',
 '[{"label":"Mettre à jour mon RIB","real_url":"http://ameli-sante.fr/rib","suspicious":true,"warning":"ameli-sante.fr nest pas lAssurance Maladie. Le vrai domaine est ameli.fr. LAssurance Maladie connaît déjà votre RIB et ne le demande jamais par e-mail."}]'::jsonb,
 TRUE,
 '["ameli-sante.fr nest pas lAssurance Maladie — le vrai domaine est ameli.fr","LAssurance Maladie connaît déjà votre RIB et rembourse automatiquement","Elle ne demande jamais de mettre à jour un RIB par e-mail","Vérifiez vos remboursements directement sur ameli.fr ou dans lappli Ameli"]'::jsonb,
 '[]'::jsonb,
 'Il sagit de phishing. LAssurance Maladie dispose déjà de votre RIB et effectue les remboursements automatiquement. Elle ne demande jamais de le mettre à jour par e-mail. Consultez vos remboursements sur ameli.fr.',
 170, 'advanced'),

('fr', 'both',
 'Google',
 'no-reply@accounts.google.com',
 'Ladresse se termine par @accounts.google.com — le domaine officiel de Google pour les alertes de sécurité.',
 'hier 20:07',
 'Nouvelle connexion sur votre compte Google',
 'Une nouvelle connexion a été détectée sur votre compte Google...',
 E'<div class="eml fam-tech" style="--brand:#4285f4;--cta:#4285f4;--logo:#3d7ae0"><div class="eml-top"><span class="eml-logo" style="font-weight:500">Google</span></div><div class="eml-body"><p>Une nouvelle connexion a été détectée sur votre compte Google.</p><p>Appareil : PC Windows<br>Localisation : Paris, France<br>Heure : hier à 20:04</p><p>Était-ce vous ? Dans ce cas, aucune action nest requise.</p><p>Si ce nétait pas vous, rendez-vous sur myaccount.google.com pour modifier votre mot de passe et consulter lactivité récente.</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 Google</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Lexpéditeur @accounts.google.com est le domaine officiel de Google pour les alertes","Pas de lien à cliquer — vous êtes renvoyé vers myaccount.google.com directement","Localisation cohérente (Paris, France)","Ton informatif, sans panique ni pression temporelle"]'::jsonb,
 'Il sagit dune vraie alerte de connexion Google. Notez que Google ninclut pas de lien à cliquer — il vous demande daller vous-même sur myaccount.google.com. Cest ainsi que fonctionnent les vraies alertes de sécurité.',
 180, 'advanced'),

('fr', 'both',
 'SNCF Connect',
 'noreply@sncf-connect.com',
 'Ladresse se termine par @sncf-connect.com — le domaine officiel de lapplication SNCF Connect.',
 '2 jours avant',
 'Votre billet Paris-Lyon du 22 mai est confirmé',
 'Votre billet pour le TGV Paris-Lyon du mercredi 22 mai est confirmé...',
 E'<div class="eml fam-parcel" style="--brand:#1f2940;--cta:#1f2940"><div class="eml-hero"><span class="eml-logo">SNCF CONNECT</span></div><div class="eml-body"><p>Bonjour,</p><p>Votre billet est confirmé :</p><p>🚄 TGV Paris-Lyon<br>Date : mercredi 22 mai<br>Départ : Paris Gare de Lyon à 09:22<br>Arrivée : Lyon Part-Dieu à 11:00<br>Voyageur : M. Dupont<br>Classe : 2e classe</p><p>Votre billet est disponible dans lapplication SNCF Connect.</p><p>Bon voyage !<br>SNCF Connect</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 SNCF CONNECT</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Lexpéditeur @sncf-connect.com est le domaine officiel de lapplication SNCF","Informations concrètes et attendues : trajet, date, heure, nom","Pas de lien de paiement ni de demande dinformations","Renvoie vers lapplication SNCF Connect pour accéder au billet"]'::jsonb,
 'Il sagit dun vrai billet de train SNCF. Toutes les informations sont concrètes et correspondent à une réservation attendue. Aucun lien de paiement ni demande dinformations personnelles.',
 190, 'advanced'),

('fr', 'both',
 'PayPal',
 'service@paypal.com',
 'Ladresse se termine par @paypal.com — le domaine officiel de PayPal.',
 '4 jours avant',
 'Confirmation de paiement : 24,99 €',
 'Vous avez effectué un paiement de 24,99 € à Netflix via PayPal...',
 E'<div class="eml fam-pay" style="--brand:#003087;--cta:#003087"><div class="eml-hero"><span class="eml-logo" style="font-style:italic;font-weight:800">PayPal</span></div><div class="eml-body"><p>Vous avez effectué un paiement.</p><p>Montant : 24,99 €<br>Destinataire : Netflix<br>Date : il y a 4 jours<br>Moyen de paiement : carte Visa se terminant par 4242</p><p>Pour consulter les détails de cette transaction ou signaler un problème, connectez-vous à votre compte sur paypal.com.</p><p>Merci dutiliser PayPal.<br>Léquipe PayPal</p></div><div class="eml-foot"><p>Ceci est un message automatique — merci de ne pas y répondre.</p><p>© 2026 PayPal</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Lexpéditeur @paypal.com est le domaine officiel de PayPal","Montant et destinataire concrets — vérifiables dans votre compte","Pas de lien urgent à cliquer — renvoie vers paypal.com","Correspond à un abonnement mensuel attendu (Netflix)"]'::jsonb,
 'Il sagit dune vraie confirmation de paiement PayPal. Elle montre les détails de la transaction et renvoie vers paypal.com. Aucune demande urgente ni lien suspect.',
 200, 'advanced'),

('de', 'both',
 'PayPal',
 'service@paypal-konto.de',
 'paypal-konto.de ist nicht PayPal. Alle echten PayPal-E-Mails kommen von @paypal.com.',
 'gestern 11:34',
 'Ihr PayPal-Konto wurde vorübergehend eingeschränkt',
 'Wir haben ungewöhnliche Aktivitäten auf Ihrem Konto festgestellt...',
 E'<div class="eml fam-pay" style="--brand:#003087;--cta:#003087"><div class="eml-hero"><span class="eml-logo" style="font-style:italic;font-weight:800">PayPal</span></div><div class="eml-body"><p>Sehr geehrte/r Kundin/Kunde,</p><p>Wir haben ungewöhnliche Aktivitäten auf Ihrem PayPal-Konto festgestellt und haben den Zugang vorübergehend eingeschränkt.</p><p>Um den vollen Zugang wiederherzustellen, bestätigen Sie bitte Ihre Identität über {{link:0}}. Ohne Bestätigung innerhalb von 48 Stunden kann Ihr Konto dauerhaft gesperrt werden.</p><p>Mit freundlichen Grüßen,<br>PayPal Sicherheitsteam</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 PayPal</p></div></div>',
 '[{"label":"Identität bestätigen","real_url":"http://paypal-konto.de/verifizieren","suspicious":true,"warning":"paypal-konto.de ist nicht PayPal. Alle echten PayPal-E-Mails kommen von @paypal.com. Loggen Sie sich direkt auf paypal.com ein."}]'::jsonb,
 TRUE,
 '["paypal-konto.de ist nicht PayPal — das echte Domain ist paypal.com","Drohung mit dauerhafter Sperrung nach 48 Stunden","PayPal bittet nie per E-Mail-Link um Identitätsbestätigung","Prüfen Sie Ihren Kontostatus direkt auf paypal.com"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing. PayPal bittet Sie nie, Ihre Identität über einen E-Mail-Link zu bestätigen. Alle echten PayPal-E-Mails kommen von @paypal.com. Prüfen Sie Ihren Status direkt auf paypal.com.',
 150, 'advanced'),

('de', 'both',
 'Apple',
 'noreply@apple-sicherheit.de',
 'apple-sicherheit.de ist nicht Apple. Echte Apple-E-Mails kommen von @apple.com.',
 'heute 05:51',
 'Ihre Apple-ID wurde in Polen auf einem neuen Gerät verwendet',
 'Ihre Apple-ID wurde soeben auf einem neuen iPhone in Warschau verwendet...',
 E'<div class="eml fam-tech" style="--brand:#000000;--cta:#000000"><div class="eml-top"><span class="eml-logo">Apple</span></div><div class="eml-body"><p>Ihre Apple-ID (ihrname@email.de) wurde verwendet, um sich auf einem neuen iPhone 15 in Warschau, Polen, anzumelden.</p><p>Datum: heute um 05:48</p><p>Waren Sie das? Dann müssen Sie nichts unternehmen.</p><p>Waren Sie das nicht? Sichern Sie Ihr Konto sofort über {{link:0}}, um einen Missbrauch zu verhindern.</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 Apple</p></div></div>',
 '[{"label":"Konto sichern","real_url":"http://apple-sicherheit.de/sichern","suspicious":true,"warning":"apple-sicherheit.de ist nicht Apple. Echte Apple-Sicherheitsmeldungen führen immer zu appleid.apple.com — nie zu externen Domains."}]'::jsonb,
 TRUE,
 '["apple-sicherheit.de ist nicht Apple — echte E-Mails kommen von @apple.com","Nennt einen ausländischen Ort, um Panik zu erzeugen","Echte Apple-Meldungen führen zu appleid.apple.com, nicht zu Drittseiten","Besuchen Sie direkt appleid.apple.com, um aktuelle Anmeldungen zu prüfen"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing. Apple-Sicherheitsmeldungen kommen immer von @apple.com und führen zu appleid.apple.com. Prüfen Sie Ihr Konto direkt auf appleid.apple.com.',
 160, 'advanced'),

('de', 'both',
 'Volksbank',
 'sicherheit@volksbank-online.de',
 'volksbank-online.de ist nicht Ihre Volksbank. Das echte Domain Ihrer Bank endet auf volksbank.de oder eine regionale Variante.',
 'vorgestern 16:08',
 'Sicherheitswarnung: Bitte bestätigen Sie Ihre Identität',
 'Wir haben eine verdächtige Anmeldung auf Ihrem Online-Banking-Konto festgestellt...',
 E'<div class="eml fam-bank" style="--brand:#0066b3;--cta:#0066b3"><div class="eml-top"><span class="eml-logo">Volksbank</span></div><div class="eml-body"><p>Sehr geehrte/r Kundin/Kunde,</p><p>Wir haben eine verdächtige Anmeldung auf Ihrem Online-Banking-Konto festgestellt. Als Sicherheitsmaßnahme wurde Ihr Zugang vorübergehend eingeschränkt.</p><p>Bitte bestätigen Sie Ihre Identität über {{link:0}}, um Ihren Zugang wiederherzustellen.</p><p>Mit freundlichen Grüßen,<br>Volksbank Sicherheitsdienst</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 Volksbank</p></div></div>',
 '[{"label":"Identität bestätigen","real_url":"http://volksbank-online.de/sicherheit","suspicious":true,"warning":"volksbank-online.de ist kein offizielles Domain einer Volksbank. Ihre echte Bank verwendet ihr eigenes Domain (z. B. volksbank-musterstadt.de). Loggen Sie sich immer direkt über die Website Ihrer Filiale ein."}]'::jsonb,
 TRUE,
 '["volksbank-online.de klingt offiziell, ist aber nicht das Domain Ihrer Volksbank","Jede Volksbank hat ihr eigenes regionales Domain — prüfen Sie es auf Ihrer Bankkarte","Keine Bank bittet per E-Mail um Identitätsbestätigung über einen Link","Loggen Sie sich direkt über die Website Ihrer Volksbank-Filiale ein"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing. Jede Volksbank hat ihr eigenes regionales Domain (z. B. volksbank-musterstadt.de). Kein Kreditinstitut bittet per E-Mail um Identitätsbestätigung. Loggen Sie sich direkt über die offizielle Website Ihrer Filiale ein.',
 170, 'advanced'),

('de', 'both',
 'Google',
 'no-reply@accounts.google.com',
 'Die Adresse endet auf @accounts.google.com — Googles offizielles Domain für Sicherheitsmeldungen.',
 'gestern 19:51',
 'Neue Anmeldung bei Ihrem Google-Konto',
 'Eine neue Anmeldung wurde bei Ihrem Google-Konto festgestellt...',
 E'<div class="eml fam-tech" style="--brand:#4285f4;--cta:#4285f4;--logo:#3d7ae0"><div class="eml-top"><span class="eml-logo" style="font-weight:500">Google</span></div><div class="eml-body"><p>Eine neue Anmeldung wurde bei Ihrem Google-Konto festgestellt.</p><p>Gerät: Windows-PC<br>Standort: Berlin, Deutschland<br>Uhrzeit: gestern um 19:48</p><p>Waren Sie das? Dann müssen Sie nichts unternehmen.</p><p>Waren Sie das nicht? Besuchen Sie myaccount.google.com, um Ihr Passwort zu ändern und aktuelle Aktivitäten einzusehen.</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 Google</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Absender @accounts.google.com ist Googles offizielles Domain für Sicherheitsmeldungen","Kein Link zum Klicken — Sie werden direkt zu myaccount.google.com weitergeleitet","Standort Deutschland — passt zu normalem Nutzungsverhalten","Informativer Ton ohne Panik oder Zeitdruck"]'::jsonb,
 'Dies ist eine echte Google-Anmeldebenachrichtigung. Beachten Sie, dass Google keinen Link zum Klicken enthält — Sie werden gebeten, myaccount.google.com selbst aufzurufen. So funktionieren legitime Sicherheitsmeldungen.',
 180, 'advanced'),

('de', 'both',
 'OTTO',
 'bestellung@otto.de',
 'Die Adresse endet auf @otto.de — das offizielle Domain von OTTO.',
 '2 Tage vor',
 'Ihre Bestellung bei OTTO wird morgen geliefert',
 'Ihre Bestellung (Bestellnummer 1234567890) wird morgen zwischen 10 und 12 Uhr geliefert...',
 E'<div class="eml fam-retail" style="--brand:#d4021d;--cta:#d4021d"><div class="eml-hero"><span class="eml-logo">OTTO</span></div><div class="eml-body"><p>Hallo,</p><p>Ihre Bestellung ist unterwegs!</p><p>📦 Bestellnummer: 1234567890<br>Voraussichtliche Lieferung: morgen zwischen 10:00 und 12:00 Uhr<br>Versanddienstleister: DHL</p><p>Sie können Ihre Sendung im Bereich „Meine Bestellungen" auf otto.de verfolgen.</p><p>Vielen Dank für Ihren Einkauf.<br>OTTO</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 OTTO</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Absender @otto.de ist das offizielle Domain von OTTO","Konkrete Bestellnummer — in Ihrem OTTO-Konto nachprüfbar","Keine Zahlungsaufforderung oder Anfrage nach persönlichen Daten","Verweist auf otto.de für die Sendungsverfolgung"]'::jsonb,
 'Dies ist eine echte Lieferbenachrichtigung von OTTO. Sie enthält eine nachprüfbare Bestellnummer und verweist auf otto.de. Keine verdächtigen Links, keine Zahlungsaufforderung.',
 190, 'advanced'),

('de', 'both',
 'Netflix',
 'info@mailer.netflix.com',
 'Die Adresse endet auf @mailer.netflix.com — ein offizielles Netflix-Versand-Domain.',
 '4 Tage vor',
 'Ihre monatliche Netflix-Zahlung wurde bestätigt',
 'Ihre monatliche Zahlung für Netflix wurde erfolgreich verarbeitet...',
 E'<div class="eml fam-retail" style="--brand:#000000;--cta:#000000;--cta-ink:#e50914"><div class="eml-hero"><span class="eml-logo" style="letter-spacing:1px;font-weight:800">NETFLIX</span></div><div class="eml-body"><p>Ihre monatliche Zahlung wurde verarbeitet.</p><p>Betrag: 17,99 €<br>Datum: vor 4 Tagen<br>Zahlungsmethode: Visa endend auf 5678</p><p>Sie können Ihr Abonnement und Ihre Zahlungshistorie unter netflix.com/YourAccount verwalten.</p><p>Danke, dass Sie Netflix nutzen.<br>Das Netflix-Team</p></div><div class="eml-foot"><p>Dies ist eine automatische Nachricht — bitte antworten Sie nicht darauf.</p><p>© 2026 NETFLIX</p></div></div>',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Absender @mailer.netflix.com ist ein offizielles Netflix-Domain für Rechnungen","Konkreter Betrag und letzte 4 Ziffern der Karte — entspricht Ihrer monatlichen Zahlung","Kein dringender Link — verweist auf netflix.com für die Kontoverwaltung","Entspricht der erwarteten monatlichen Abbuchung"]'::jsonb,
 'Dies ist eine echte Netflix-Zahlungsbestätigung. Sie zeigt den abgebuchten Betrag und verweist auf netflix.com. Keine verdächtigen Links, keine dringenden Forderungen.',
 200, 'advanced');

-- nl-BE en fr-BE: kopieën van nieuwe nl/fr advanced-berichten.
INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty)
SELECT 'nl-BE', audience, sender_name, sender_address, sender_note, received_label,
       subject, preview, body, links, is_phishing, red_flags, green_flags,
       explanation, sort_order, difficulty
FROM inbox_messages
WHERE locale = 'nl' AND difficulty = 'advanced' AND sort_order >= 150;

INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty)
SELECT 'fr-BE', audience, sender_name, sender_address, sender_note, received_label,
       subject, preview, body, links, is_phishing, red_flags, green_flags,
       explanation, sort_order, difficulty
FROM inbox_messages
WHERE locale = 'fr' AND difficulty = 'advanced' AND sort_order >= 150;

-- ── SharePoint-phishing (sort_order 210, business, advanced) ──────────────
INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty)
VALUES
('nl', 'business',
 'Microsoft SharePoint',
 'no-reply@sharepointonline-files.com',
 'Het domein is sharepointonline-files.com — niet sharepointonline.com. Microsoft verstuurt uitnodigingen altijd via @sharepointonline.com.',
 'vandaag 14:22',
 'Vandenberghe Koen heeft een bestand met u gedeeld',
 'Vandenberghe Koen heeft u uitgenodigd om ‘Salarisschalen_en_Bonussen_2026_NL’ te bewerken.',
 E'<div class="ol-share-card"><div class="ol-share-head"><div class="ol-share-icon">⤴</div><h2 class="ol-share-heading">Vandenberghe Koen heeft u uitgenodigd om een bestand te bewerken</h2></div><div class="ol-share-body"><p class="ol-share-msg">"Vertrouwelijk — ter review voor HR en management. Graag feedback voor maandag."</p><p class="ol-share-intro">Dit is het bestand dat Vandenberghe Koen met u heeft gedeeld.</p><div class="ol-share-file"><span class="ol-share-file-ico">📄</span><span class="ol-share-file-name">Salarisschalen_en_Bonussen_2026_NL.xlsx</span></div><p class="ol-share-protection">🔒 Deze uitnodiging werkt alleen voor u en personen met bestaande toegang.</p><div class="ol-share-actions">{{link:0}}</div></div></div>',
 '[{"label":"Bestand openen","real_url":"http://sharepointonline-files.com/share/view?id=a9f3c2","suspicious":true,"warning":"Dit is geen Microsoft-link. Het domein sharepointonline-files.com is nep. U wordt naar een valse inlogpagina geleid om uw Microsoft-wachtwoord te stelen."}]'::jsonb,
 TRUE,
 '["Het afzenderdomein sharepointonline-files.com is niet van Microsoft — het echte is @sharepointonline.com","Een echte SharePoint-uitnodiging opent het bestand direct — er wordt nooit om een nieuw wachtwoord gevraagd","De link gaat naar sharepointonline-files.com in plaats van sharepoint.com of microsoft.com","Controleer uitnodigingen altijd via Microsoft 365 zelf, niet via een e-maillink"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. Het afzenderdomein sharepointonline-files.com lijkt sterk op het echte Microsoft-domein, maar is nep. Via de link wordt u naar een valse Microsoft-inlogpagina geleid om uw werkwachtwoord te stelen. Echte SharePoint-uitnodigingen komen altijd van @sharepointonline.com en openen het bestand zonder opnieuw in te loggen.',
 210, 'advanced'),
('en', 'business',
 'Microsoft SharePoint',
 'no-reply@sharepointonline-files.com',
 'The domain is sharepointonline-files.com — not sharepointonline.com. Microsoft always sends sharing invitations from @sharepointonline.com.',
 'today 14:22',
 'Vandenberghe Koen has shared a file with you',
 'Vandenberghe Koen has invited you to edit ‘Salary_Scales_and_Bonuses_2026_EN’.',
 E'<div class="ol-share-card"><div class="ol-share-head"><div class="ol-share-icon">⤴</div><h2 class="ol-share-heading">Vandenberghe Koen has invited you to edit a file</h2></div><div class="ol-share-body"><p class="ol-share-msg">"Confidential — for review by HR and management. Feedback by Monday please."</p><p class="ol-share-intro">This is the file Vandenberghe Koen shared with you.</p><div class="ol-share-file"><span class="ol-share-file-ico">📄</span><span class="ol-share-file-name">Salary_Scales_and_Bonuses_2026_EN.xlsx</span></div><p class="ol-share-protection">🔒 This invitation only works for you and people with existing access.</p><div class="ol-share-actions">{{link:0}}</div></div></div>',
 '[{"label":"Open file","real_url":"http://sharepointonline-files.com/share/view?id=a9f3c2","suspicious":true,"warning":"This is not a Microsoft link. The domain sharepointonline-files.com is fake. You will be taken to a fake login page to steal your Microsoft password."}]'::jsonb,
 TRUE,
 '["The sender domain sharepointonline-files.com is not Microsoft — the real one is @sharepointonline.com","A genuine SharePoint invitation opens the file directly — you are never asked to log in again","The link points to sharepointonline-files.com rather than sharepoint.com or microsoft.com","Always check sharing invitations via Microsoft 365 directly, not through an email link"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. The sender domain sharepointonline-files.com closely resembles the real Microsoft domain but is fake. The link leads to a false Microsoft login page designed to steal your work password. Genuine SharePoint invitations always come from @sharepointonline.com and open the file without requiring you to log in again.',
 210, 'advanced'),
('fr', 'business',
 'Microsoft SharePoint',
 'no-reply@sharepointonline-files.com',
 'Le domaine est sharepointonline-files.com — pas sharepointonline.com. Microsoft envoie toujours les invitations depuis @sharepointonline.com.',
 'aujourd''hui 14:22',
 'Vandenberghe Koen a partagé un fichier avec vous',
 'Vandenberghe Koen vous a invité(e) à modifier ‘Grilles_Salaires_Primes_2026_FR’.',
 E'<div class="ol-share-card"><div class="ol-share-head"><div class="ol-share-icon">⤴</div><h2 class="ol-share-heading">Vandenberghe Koen vous a invité(e) à modifier un fichier</h2></div><div class="ol-share-body"><p class="ol-share-msg">« Confidentiel — à relire par les RH et la direction. Merci de me faire part de vos retours avant lundi. »</p><p class="ol-share-intro">Voici le fichier que Vandenberghe Koen a partagé avec vous.</p><div class="ol-share-file"><span class="ol-share-file-ico">📄</span><span class="ol-share-file-name">Grilles_Salaires_Primes_2026_FR.xlsx</span></div><p class="ol-share-protection">🔒 Cette invitation ne fonctionne que pour vous et les personnes ayant déjà accès.</p><div class="ol-share-actions">{{link:0}}</div></div></div>',
 '[{"label":"Ouvrir le fichier","real_url":"http://sharepointonline-files.com/share/view?id=a9f3c2","suspicious":true,"warning":"Ce lien ne provient pas de Microsoft. Le domaine sharepointonline-files.com est frauduleux. Vous serez redirigé(e) vers une fausse page de connexion Microsoft pour vous voler votre mot de passe."}]'::jsonb,
 TRUE,
 '["Le domaine expéditeur sharepointonline-files.com n''est pas Microsoft — le vrai est @sharepointonline.com","Une vraie invitation SharePoint ouvre directement le fichier — on ne vous demande jamais de vous reconnecter","Le lien pointe vers sharepointonline-files.com et non vers sharepoint.com ou microsoft.com","Vérifiez toujours les invitations de partage directement via Microsoft 365, pas via un lien e-mail"]'::jsonb,
 '[]'::jsonb,
 'Il s''agit de phishing. Le domaine sharepointonline-files.com ressemble fortement au vrai domaine Microsoft, mais il est frauduleux. Le lien mène vers une fausse page de connexion Microsoft conçue pour voler votre mot de passe professionnel. Les vraies invitations SharePoint viennent toujours de @sharepointonline.com et ouvrent le fichier sans nouvelle connexion.',
 210, 'advanced'),
('de', 'business',
 'Microsoft SharePoint',
 'no-reply@sharepointonline-files.com',
 'Die Domain lautet sharepointonline-files.com — nicht sharepointonline.com. Microsoft versendet Einladungen immer über @sharepointonline.com.',
 'heute 14:22',
 'Vandenberghe Koen hat eine Datei mit Ihnen geteilt',
 'Vandenberghe Koen hat Sie eingeladen, ‘Gehaltstabellen_und_Praemien_2026_DE’ zu bearbeiten.',
 E'<div class="ol-share-card"><div class="ol-share-head"><div class="ol-share-icon">⤴</div><h2 class="ol-share-heading">Vandenberghe Koen hat Sie eingeladen, eine Datei zu bearbeiten</h2></div><div class="ol-share-body"><p class="ol-share-msg">„Vertraulich — zur Durchsicht für HR und Management. Feedback bitte bis Montag."</p><p class="ol-share-intro">Dies ist die Datei, die Vandenberghe Koen mit Ihnen geteilt hat.</p><div class="ol-share-file"><span class="ol-share-file-ico">📄</span><span class="ol-share-file-name">Gehaltstabellen_und_Praemien_2026_DE.xlsx</span></div><p class="ol-share-protection">🔒 Diese Einladung funktioniert nur für Sie und Personen mit bestehendem Zugriff.</p><div class="ol-share-actions">{{link:0}}</div></div></div>',
 '[{"label":"Datei öffnen","real_url":"http://sharepointonline-files.com/share/view?id=a9f3c2","suspicious":true,"warning":"Dies ist kein Microsoft-Link. Die Domain sharepointonline-files.com ist gefälscht. Sie werden auf eine gefälschte Microsoft-Anmeldeseite weitergeleitet, um Ihr Passwort zu stehlen."}]'::jsonb,
 TRUE,
 '["Die Absender-Domain sharepointonline-files.com gehört nicht zu Microsoft — die echte ist @sharepointonline.com","Eine echte SharePoint-Einladung öffnet die Datei direkt — Sie werden nie aufgefordert, sich erneut anzumelden","Der Link zeigt auf sharepointonline-files.com statt auf sharepoint.com oder microsoft.com","Überprüfen Sie Freigabe-Einladungen immer direkt über Microsoft 365, nicht über einen E-Mail-Link"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing. Die Domain sharepointonline-files.com ähnelt der echten Microsoft-Domain stark, ist aber gefälscht. Der Link führt auf eine gefälschte Microsoft-Anmeldeseite, die Ihr Arbeitspasswort stehlen soll. Echte SharePoint-Einladungen kommen immer von @sharepointonline.com und öffnen die Datei ohne erneute Anmeldung.',
 210, 'advanced');

-- nl-BE copy
INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty)
SELECT 'nl-BE', audience, sender_name, sender_address, sender_note, received_label,
       subject, preview, body, links, is_phishing, red_flags, green_flags,
       explanation, sort_order, difficulty
FROM inbox_messages
WHERE locale = 'nl' AND difficulty = 'advanced' AND sort_order = 210;

-- fr-BE copy
INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty)
SELECT 'fr-BE', audience, sender_name, sender_address, sender_note, received_label,
       subject, preview, body, links, is_phishing, red_flags, green_flags,
       explanation, sort_order, difficulty
FROM inbox_messages
WHERE locale = 'fr' AND difficulty = 'advanced' AND sort_order = 210;

