-- ============================================================
-- FASE 1: SMISHING — sms- en WhatsApp-scenario's.
-- Eén INSERT met expliciete kolommen locale/channel/audience/difficulty.
-- channel = 'sms' of 'whatsapp'; audience 'both'; difficulty 'normal'.
-- WhatsApp "familie-in-nood"-oplichting heeft GEEN link: de actie is
-- antwoorden/geld overmaken, dus links = []. sort_order vanaf 300 zodat
-- het niet botst met de e-mailscenario's.
-- ============================================================
INSERT INTO inbox_messages
  (locale, channel, audience, difficulty, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- ---------- NL ----------
('nl','sms','both','normal',
 'PostNL','+31 6 21 34 55 78',
 'PostNL stuurt sms''jes nooit vanaf een 06-nummer en vraagt nooit om betaling van bezorgkosten.',
 'vandaag 14:02','PostNL',
 'Uw pakket kon niet bezorgd worden. Betaal € 0,69 verzendkosten...',
 E'PostNL: uw pakket kon niet worden bezorgd. Betaal de openstaande verzendkosten van € 0,69 om opnieuw te laten bezorgen: {{link:0}}',
 '[{"label":"postnl-herbezorging.com","real_url":"http://postnl-herbezorging.com/betaal","suspicious":true,"warning":"Het echte adres is postnl.nl. \"postnl-herbezorging.com\" is een nepsite. Een klein bedrag (€ 0,69) is een trucje zodat u zonder nadenken uw kaartgegevens invult."}]'::jsonb,
 TRUE,
 '["Onbekend 06-nummer als afzender","Heel klein bedrag — u twijfelt niet","Link gaat naar postnl-herbezorging.com, niet postnl.nl","Druk: \"betaal om opnieuw te laten bezorgen\""]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing (phishing via sms). PostNL vraagt nooit per sms om bezorgkosten te betalen. Verwacht u een pakket? Controleer het zelf in de PostNL-app of op postnl.nl — typ het adres zelf in.',
 300),

('nl','sms','both','normal',
 'ING','+31 97 01 02 88 31',
 'De echte ING sms''t alleen verificatiecodes en zet er nooit een link bij.',
 'vandaag 11:20','ING',
 'Er is ingelogd op een nieuw apparaat. Was u dit niet? Beveilig...',
 E'ING: er is zojuist ingelogd op een NIEUW apparaat. Was u dit niet? Beveilig direct uw rekening via {{link:0}}',
 '[{"label":"ing-veilig-inloggen.net","real_url":"http://ing-veilig-inloggen.net","suspicious":true,"warning":"De echte ING gebruikt ing.nl en de ING-app. \"ing-veilig-inloggen.net\" is nep en wil uw inloggegevens stelen."}]'::jsonb,
 TRUE,
 '["Speelt in op angst (\"vreemd apparaat\")","Link in een bank-sms — de ING doet dat nooit","Domein ing-veilig-inloggen.net is niet ing.nl","Drang om \"direct\" te handelen"]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. Uw bank stuurt nooit een sms met een link om in te loggen. Vertrouwt u het niet? Open zelf de ING-app of bel het nummer op uw bankpas.',
 301),

('nl','whatsapp','both','normal',
 'Onbekend nummer','+31 6 48 22 19 07',
 'Een "nieuw nummer"-bericht van familie dat meteen om geld vraagt en niet wil bellen, is bijna altijd oplichting.',
 'vandaag 18:45','Onbekend nummer',
 'Hoi mam, dit is mijn nieuwe nummer. Mijn telefoon is kapot...',
 E'Hoi mam 👋 Dit is mijn nieuwe nummer, mijn oude telefoon is kapot. Kun je me even helpen? Ik moet vandaag een rekening van € 850 betalen maar kom er met mijn bankapp niet in. Kun jij het voorschieten? Ik betaal je morgen terug. Bellen lukt nu niet, alleen appen. ❤️',
 '[]'::jsonb,
 TRUE,
 '["Onbekend nummer dat zegt familie te zijn","\"Nieuw nummer, oude telefoon kapot\" — klassieke smoes","Vraagt met spoed om geld over te maken","Wil NIET bellen — alleen appen, zodat u de stem niet hoort"]'::jsonb,
 '[]'::jsonb,
 'Dit is WhatsApp-fraude (de \"hallo mama/papa\"-oplichting). Bel altijd het ORIGINELE, bekende nummer van uw kind voordat u iets overmaakt. Een oplichter wil juist niet dat u belt.',
 302),

('nl','whatsapp','both','normal',
 'Marktplaats-koper','+31 6 12 90 33 41',
 'Een "koper" die u naar een betaallink stuurt om u 1 cent te laten "ontvangen", is een bekende oplichtingstruc.',
 'vandaag 16:10','Marktplaats-koper',
 'Hoi! Ik wil je bankstel kopen. Bevestig even via deze link...',
 E'Hoi! Ik wil graag je bankstel kopen via Marktplaats. Om te bevestigen dat jouw rekening werkt, stuur ik je € 0,01. Klik op deze link en log in met je bank om het te ontvangen: {{link:0}}',
 '[{"label":"marktplaats-betaalcheck.com","real_url":"http://marktplaats-betaalcheck.com/verify","suspicious":true,"warning":"Marktplaats/Tikkie laat u nooit \"inloggen om geld te ONTVANGEN\". Deze link leidt naar een nep-inlogpagina die uw bankgegevens steelt."}]'::jsonb,
 TRUE,
 '["Je hoeft nooit in te loggen om geld te ONTVANGEN","Verdacht klein bedrag (1 cent) als lokkertje","Link naar marktplaats-betaalcheck.com — niet de echte app","Buiten de officiële Marktplaats-chat om"]'::jsonb,
 '[]'::jsonb,
 'Dit is oplichting. Om geld te ontvangen hoeft u nooit ergens in te loggen. Houd betalingen altijd binnen de officiële app en klik niet op toegestuurde betaallinks.',
 303),

('nl','sms','both','normal',
 'Tandarts Hagedoorn','Tandarts','Een afspraakherinnering zonder link, met een nummer dat u zelf kunt bellen, is normaal.',
 'vandaag 09:30','Tandarts Hagedoorn',
 'Herinnering: uw controle morgen om 10:40. Afzeggen? Bel 020-1234567.',
 E'Tandartspraktijk Hagedoorn: herinnering aan uw controle morgen om 10:40. Verhinderd? Bel ons op 020-123 45 67. Tot morgen!',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Geen link en geen betaalverzoek","Concrete, verwachte afspraakinformatie","Telefoonnummer om zelf te bellen","Afzendernaam van uw eigen praktijk"]'::jsonb,
 'Dit is een gewone afspraakherinnering van uw tandarts. Geen link, geen gegevens gevraagd — u kunt gerust bellen als u wilt verzetten.',
 304),

('nl','sms','both','normal',
 'CJIB','3990','Het CJIB stuurt betalingsverzoeken per post (acceptgiro), nooit een sms met een link en spoed.',
 'gisteren 13:15','CJIB',
 'Openstaande boete € 49. Betaal binnen 24 uur om verhoging te...',
 E'CJIB: u heeft een openstaande verkeersboete van € 49. Betaal binnen 24 uur om een verhoging te voorkomen: {{link:0}}',
 '[{"label":"cjib-betalen.com","real_url":"http://cjib-betalen.com/boete","suspicious":true,"warning":"Het CJIB stuurt boetes per post en gebruikt cjib.nl. \"cjib-betalen.com\" is nep en mikt op uw betaalgegevens."}]'::jsonb,
 TRUE,
 '["Overheid stuurt boetes per post, niet per sms met link","Tijdsdruk: \"binnen 24 uur\"","Domein cjib-betalen.com is niet cjib.nl","Dreigt met verhoging om u te haasten"]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. Het CJIB int boetes via een acceptgiro per post, nooit via een sms-link onder tijdsdruk. Controleer bij twijfel op cjib.nl.',
 305),

-- ---------- nl-BE ----------
('nl-BE','sms','both','normal',
 'bpost','+32 460 21 34 55',
 'bpost stuurt sms''jes nooit vanaf een gsm-nummer en vraagt nooit om bezorgkosten via een link.',
 'vandaag 14:02','bpost',
 'Uw pakje kon niet geleverd worden. Betaal € 0,69 leveringskosten...',
 E'bpost: uw pakje kon niet geleverd worden. Betaal de openstaande leveringskosten van € 0,69 om opnieuw te laten leveren: {{link:0}}',
 '[{"label":"bpost-herlevering.com","real_url":"http://bpost-herlevering.com/betaal","suspicious":true,"warning":"Het echte adres is bpost.be. \"bpost-herlevering.com\" is een nepsite. Een klein bedrag is een trucje zodat u uw kaartgegevens invult."}]'::jsonb,
 TRUE,
 '["Onbekend gsm-nummer als afzender","Heel klein bedrag — u twijfelt niet","Link naar bpost-herlevering.com, niet bpost.be","Druk om snel te betalen"]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. bpost vraagt nooit per sms om leveringskosten. Verwacht u een pakje? Kijk zelf in de bpost-app of op bpost.be.',
 310),

('nl-BE','sms','both','normal',
 'Belfius','+32 471 88 31 02',
 'Belfius stuurt enkel verificatiecodes per sms en zet er nooit een link bij.',
 'vandaag 11:20','Belfius',
 'Er is aangemeld op een nieuw toestel. Was u dit niet? Beveilig...',
 E'Belfius: er werd zonet aangemeld op een NIEUW toestel. Was u dit niet? Beveilig meteen uw rekening via {{link:0}}',
 '[{"label":"belfius-veilig.net","real_url":"http://belfius-veilig.net","suspicious":true,"warning":"De echte Belfius gebruikt belfius.be en de app. \"belfius-veilig.net\" is nep en wil uw codes stelen."}]'::jsonb,
 TRUE,
 '["Speelt in op angst (\"vreemd toestel\")","Link in een bank-sms — Belfius doet dat nooit","Domein belfius-veilig.net is niet belfius.be","Drang om \"meteen\" te handelen"]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. Uw bank stuurt nooit een sms met een link om aan te melden. Open zelf de Belfius-app of bel het nummer op uw bankkaart.',
 311),

('nl-BE','whatsapp','both','normal',
 'Onbekend nummer','+32 470 22 19 07',
 'Een "nieuw nummer"-bericht van familie dat meteen om geld vraagt en niet wil bellen, is bijna altijd oplichting.',
 'vandaag 18:45','Onbekend nummer',
 'Dag mama, dit is mijn nieuw nummer. Mijn gsm is stuk...',
 E'Dag mama 👋 Dit is mijn nieuw nummer, mijn oude gsm is stuk. Kun je me even depanneren? Ik moet vandaag een factuur van € 850 betalen maar geraak niet in mijn bankapp. Kun jij het voorschieten? Ik stort het je morgen terug. Bellen lukt niet, enkel appen. ❤️',
 '[]'::jsonb,
 TRUE,
 '["Onbekend nummer dat zegt familie te zijn","\"Nieuw nummer, oude gsm stuk\" — klassieke smoes","Vraagt met spoed om geld te storten","Wil NIET bellen — enkel appen, zodat u de stem niet hoort"]'::jsonb,
 '[]'::jsonb,
 'Dit is WhatsApp-fraude (de \"hallo mama/papa\"-oplichting). Bel altijd het ORIGINELE, gekende nummer van uw kind voor u iets stort. Een oplichter wil net niet dat u belt.',
 312),

('nl-BE','whatsapp','both','normal',
 '2dehands-koper','+32 468 90 33 41',
 'Een "koper" die u naar een betaallink stuurt om u 1 cent te laten "ontvangen", is een gekende oplichtingstruc.',
 'vandaag 16:10','2dehands-koper',
 'Hallo! Ik wil je zetel kopen. Bevestig even via deze link...',
 E'Hallo! Ik wil graag je zetel kopen via 2dehands. Om te bevestigen dat je rekening werkt, stuur ik je € 0,01. Klik op deze link en meld je aan met je bank om het te ontvangen: {{link:0}}',
 '[{"label":"2dehands-betaalcheck.com","real_url":"http://2dehands-betaalcheck.com/verify","suspicious":true,"warning":"U hoeft nooit aan te melden om geld te ONTVANGEN. Deze link leidt naar een nep-aanmeldpagina die uw bankgegevens steelt."}]'::jsonb,
 TRUE,
 '["Je moet nooit aanmelden om geld te ONTVANGEN","Verdacht klein bedrag (1 cent) als lokaas","Link naar 2dehands-betaalcheck.com — niet de echte app","Buiten de officiële chat om"]'::jsonb,
 '[]'::jsonb,
 'Dit is oplichting. Om geld te ontvangen hoeft u zich nergens aan te melden. Houd betalingen binnen de officiële app en klik niet op toegestuurde betaallinks.',
 313),

('nl-BE','sms','both','normal',
 'Garage Verlinden','Garage','Een afspraakherinnering zonder link, met een nummer dat u zelf kunt bellen, is normaal.',
 'vandaag 09:30','Garage Verlinden',
 'Herinnering: onderhoud van uw wagen morgen om 08:30. Bel 03-1234567.',
 E'Garage Verlinden: herinnering aan het onderhoud van uw wagen morgen om 08:30. Verhinderd? Bel ons op 03-123 45 67. Tot morgen!',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Geen link en geen betaalverzoek","Concrete, verwachte afspraakinformatie","Telefoonnummer om zelf te bellen","Afzendernaam van uw eigen garage"]'::jsonb,
 'Dit is een gewone afspraakherinnering van uw garage. Geen link, geen gegevens gevraagd — u kunt gerust bellen als u wilt verzetten.',
 314),

('nl-BE','sms','both','normal',
 'FOD Financiën','8811','De FOD Financiën communiceert via MyMinfin en per post, nooit via een sms-link met spoed.',
 'gisteren 13:15','FOD Financiën',
 'U heeft recht op € 213 teruggave. Bevestig binnen 24u uw gegevens...',
 E'FOD Financiën: u heeft recht op een teruggave van € 213. Bevestig binnen 24u uw gegevens om de uitbetaling te ontvangen: {{link:0}}',
 '[{"label":"minfin-teruggave.com","real_url":"http://minfin-teruggave.com/claim","suspicious":true,"warning":"De FOD Financiën gebruikt MyMinfin (financien.belgium.be). \"minfin-teruggave.com\" is nep en mikt op uw gegevens."}]'::jsonb,
 TRUE,
 '["Overheid belooft geld om u op de link te krijgen","Tijdsdruk: \"binnen 24u\"","Domein minfin-teruggave.com is niet officieel","Vraagt om gegevens te \"bevestigen\""]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. De FOD Financiën regelt teruggaven via MyMinfin of per post, nooit via een sms-link onder tijdsdruk. Log zelf in op financien.belgium.be.',
 315),

-- ---------- en (UK) ----------
('en','sms','both','normal',
 'Royal Mail','+44 7700 900321',
 'Royal Mail does not text from a mobile number and never asks you to pay a redelivery fee via a link.',
 'today 14:02','Royal Mail',
 'Your parcel could not be delivered. Pay the £0.69 redelivery fee...',
 E'Royal Mail: your parcel could not be delivered. Please pay the outstanding £0.69 redelivery fee to rearrange delivery: {{link:0}}',
 '[{"label":"royalmail-redelivery.com","real_url":"http://royalmail-redelivery.com/pay","suspicious":true,"warning":"The real site is royalmail.com. \"royalmail-redelivery.com\" is a fake. A tiny fee (£0.69) is a trick so you enter your card details without thinking."}]'::jsonb,
 TRUE,
 '["Unknown mobile number as sender","Tiny amount — you do not stop to think","Link goes to royalmail-redelivery.com, not royalmail.com","Pressure: pay to rearrange delivery"]'::jsonb,
 '[]'::jsonb,
 'This is smishing (phishing by text). Royal Mail never texts you to pay a redelivery fee. Expecting a parcel? Check it yourself in the Royal Mail app or at royalmail.com — type the address yourself.',
 320),

('en','sms','both','normal',
 'HMRC','+44 7700 900812',
 'HMRC never texts you a link to claim a refund — refunds go through your online tax account.',
 'today 11:20','HMRC',
 'You are due a tax refund of £276.40. Claim within 24 hours...',
 E'HMRC: our records show you are due a tax refund of £276.40. Claim it within 24 hours here: {{link:0}}',
 '[{"label":"hmrc-refund-claim.com","real_url":"http://hmrc-refund-claim.com/claim","suspicious":true,"warning":"HMRC uses gov.uk. \"hmrc-refund-claim.com\" is a fake site built to steal your bank and tax details."}]'::jsonb,
 TRUE,
 '["Government does not text refund links","Time pressure: \"within 24 hours\"","Domain hmrc-refund-claim.com is not gov.uk","Promises money to make you click"]'::jsonb,
 '[]'::jsonb,
 'This is smishing. HMRC never notifies you of a refund by text with a link. If unsure, log in yourself at gov.uk through your Personal Tax Account.',
 321),

('en','whatsapp','both','normal',
 'Unknown number','+44 7456 221907',
 'A "new number" message from family that immediately asks for money and refuses to call is almost always a scam.',
 'today 18:45','Unknown number',
 'Hi mum, this is my new number. My phone broke...',
 E'Hi mum 👋 This is my new number, my old phone broke. Can you help me out? I need to pay a £850 bill today but I am locked out of my banking app. Could you cover it? I will pay you back tomorrow. Can not call right now, only text. ❤️',
 '[]'::jsonb,
 TRUE,
 '["Unknown number claiming to be family","\"New number, old phone broke\" — classic excuse","Urgently asks you to transfer money","Refuses to call — only text, so you never hear the voice"]'::jsonb,
 '[]'::jsonb,
 'This is a WhatsApp \"hi mum/dad\" scam. Always call your child on their ORIGINAL, known number before sending any money. A scammer specifically does not want you to call.',
 322),

('en','whatsapp','both','normal',
 'Delivery','+44 7456 903341',
 'A real 2FA login code is short, has no link, and you only ever enter it in the app you logged into yourself.',
 'today 16:10','Delivery',
 'WhatsApp code 472-913. Forward it to verify your account...',
 E'Hi, sorry! I accidentally sent my WhatsApp verification code to your number. It is 472-913. Could you forward it back to me? I really need to get back into my account, thanks so much! 🙏',
 '[]'::jsonb,
 TRUE,
 '["No one legitimately needs YOUR verification code","A code sent to you unlocks YOUR account, not theirs","Friendly, apologetic tone to lower your guard","Pressure to act quickly and \"help\""]'::jsonb,
 '[]'::jsonb,
 'This is an account-takeover scam. The code was sent to you because someone is trying to hijack YOUR WhatsApp. Never share a verification code with anyone — not even a \"friend\".',
 323),

('en','sms','both','normal',
 'Brightsmile Dental','Dental','An appointment reminder with no link and a number you can call yourself is normal.',
 'today 09:30','Brightsmile Dental',
 'Reminder: your check-up tomorrow at 10:40. To cancel call 020 7946 0123.',
 E'Brightsmile Dental: a reminder of your check-up tomorrow at 10:40. Need to cancel or rearrange? Call us on 020 7946 0123. See you then!',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["No link and no payment request","Concrete, expected appointment details","A phone number you can call yourself","Sender name of your own practice"]'::jsonb,
 'This is an ordinary appointment reminder from your dentist. No link, no details requested — feel free to call if you want to change it.',
 324),

('en','sms','both','normal',
 'Verify','782244',
 'A genuine 2FA code is sent only when YOU just tried to log in, contains no link, and tells you not to share it.',
 'today 08:05','Verify',
 'Your verification code is 558019. Do not share it with anyone.',
 E'558019 is your verification code. Do not share this code with anyone. If you did not request it, ignore this message.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["No link to tap","Tells you NOT to share the code","Sent because you just tried to sign in yourself","Short code from a recognised short number"]'::jsonb,
 'This is a genuine two-factor (2FA) code. It is safe as long as YOU just requested it — enter it only in the app or site you logged into. Never read it out or forward it to anyone.',
 325),

-- ---------- fr ----------
('fr','sms','both','normal',
 'Chronopost','+33 6 21 34 55 78',
 'Chronopost n''envoie pas de SMS depuis un numéro de portable et ne demande jamais de payer des frais via un lien.',
 'aujourd''hui 14:02','Chronopost',
 'Votre colis n''a pas pu être livré. Réglez 0,69 € de frais...',
 E'Chronopost : votre colis n''a pas pu être livré. Réglez les frais de réexpédition de 0,69 € pour planifier une nouvelle livraison : {{link:0}}',
 '[{"label":"chronopost-relivraison.com","real_url":"http://chronopost-relivraison.com/payer","suspicious":true,"warning":"Le vrai site est chronopost.fr. « chronopost-relivraison.com » est un faux. Un petit montant (0,69 €) est une ruse pour que vous saisissiez votre carte sans réfléchir."}]'::jsonb,
 TRUE,
 '["Numéro de portable inconnu comme expéditeur","Montant minuscule — vous ne vous méfiez pas","Le lien mène à chronopost-relivraison.com, pas chronopost.fr","Pression : payez pour relivrer"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing (hameçonnage par SMS). Chronopost ne demande jamais de frais par SMS. Vous attendez un colis ? Vérifiez vous-même dans l''appli ou sur chronopost.fr en tapant l''adresse.',
 330),

('fr','sms','both','normal',
 'Banque','+33 6 70 10 28 83',
 'Votre banque envoie uniquement des codes de vérification par SMS et n''y joint jamais de lien.',
 'aujourd''hui 11:20','Banque',
 'Connexion depuis un nouvel appareil. Ce n''était pas vous ?...',
 E'Votre banque : une connexion vient d''avoir lieu depuis un NOUVEL appareil. Ce n''était pas vous ? Sécurisez votre compte immédiatement : {{link:0}}',
 '[{"label":"securite-banque-acces.net","real_url":"http://securite-banque-acces.net","suspicious":true,"warning":"Votre vraie banque utilise son propre site et son appli. « securite-banque-acces.net » est un faux qui veut voler vos identifiants."}]'::jsonb,
 TRUE,
 '["Joue sur la peur (« appareil inconnu »)","Un lien dans un SMS bancaire — la banque ne fait jamais ça","Domaine securite-banque-acces.net non officiel","Incite à agir « immédiatement »"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing. Votre banque n''envoie jamais de SMS avec un lien de connexion. En cas de doute, ouvrez vous-même l''appli ou appelez le numéro figurant sur votre carte.',
 331),

('fr','whatsapp','both','normal',
 'Numéro inconnu','+33 6 48 22 19 07',
 'Un message « nouveau numéro » d''un proche qui réclame aussitôt de l''argent et refuse d''appeler est presque toujours une arnaque.',
 'aujourd''hui 18:45','Numéro inconnu',
 'Coucou maman, c''est mon nouveau numéro. Mon téléphone est cassé...',
 E'Coucou maman 👋 C''est mon nouveau numéro, mon ancien téléphone est cassé. Tu peux m''aider ? Je dois régler une facture de 850 € aujourd''hui mais je n''arrive plus à accéder à mon appli bancaire. Tu peux avancer ? Je te rembourse demain. Je ne peux pas appeler, seulement écrire. ❤️',
 '[]'::jsonb,
 TRUE,
 '["Numéro inconnu se faisant passer pour un proche","« Nouveau numéro, ancien téléphone cassé » — prétexte classique","Demande en urgence un virement","Refuse d''appeler — seulement écrire, pour que vous n''entendiez pas la voix"]'::jsonb,
 '[]'::jsonb,
 'C''est l''arnaque WhatsApp « bonjour maman/papa ». Appelez toujours votre enfant sur son numéro D''ORIGINE connu avant d''envoyer le moindre euro. L''escroc, justement, ne veut pas que vous appeliez.',
 332),

('fr','whatsapp','both','normal',
 'Acheteur Leboncoin','+33 6 12 90 33 41',
 'Un « acheteur » qui vous envoie un lien de paiement pour vous faire « recevoir » 1 centime est une arnaque connue.',
 'aujourd''hui 16:10','Acheteur Leboncoin',
 'Bonjour ! Je veux acheter votre canapé. Confirmez via ce lien...',
 E'Bonjour ! Je souhaite acheter votre canapé sur Leboncoin. Pour vérifier que votre compte fonctionne, je vous envoie 0,01 €. Cliquez sur ce lien et connectez-vous avec votre banque pour le recevoir : {{link:0}}',
 '[{"label":"leboncoin-paiement-verif.com","real_url":"http://leboncoin-paiement-verif.com/verify","suspicious":true,"warning":"On ne se connecte jamais pour RECEVOIR de l''argent. Ce lien mène à une fausse page de connexion qui vole vos données bancaires."}]'::jsonb,
 TRUE,
 '["On ne se connecte jamais pour RECEVOIR de l''argent","Montant minuscule (1 centime) comme appât","Lien vers leboncoin-paiement-verif.com — pas la vraie appli","En dehors de la messagerie officielle"]'::jsonb,
 '[]'::jsonb,
 'C''est une arnaque. Pour recevoir de l''argent, vous n''avez jamais à vous connecter quelque part. Restez dans l''appli officielle et ne cliquez pas sur les liens de paiement envoyés.',
 333),

('fr','sms','both','normal',
 'Cabinet Dr Martin','Cabinet','Un rappel de rendez-vous sans lien, avec un numéro que vous pouvez appeler, est normal.',
 'aujourd''hui 09:30','Cabinet Dr Martin',
 'Rappel : votre rendez-vous demain à 10h40. Pour annuler : 01 23 45 67 89.',
 E'Cabinet du Dr Martin : rappel de votre rendez-vous demain à 10h40. Empêché(e) ? Appelez-nous au 01 23 45 67 89. À demain !',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Aucun lien ni demande de paiement","Informations de rendez-vous concrètes et attendues","Un numéro que vous pouvez appeler vous-même","Nom de votre propre cabinet"]'::jsonb,
 'C''est un simple rappel de rendez-vous de votre médecin. Aucun lien, aucune donnée demandée — appelez librement si vous voulez le déplacer.',
 334),

('fr','sms','both','normal',
 'CodeAcces','32100','Un vrai code de vérification ne contient pas de lien et vous demande de ne pas le partager.',
 'aujourd''hui 08:05','CodeAcces',
 'Votre code de vérification est 558019. Ne le partagez avec personne.',
 E'558019 est votre code de vérification. Ne le communiquez à personne. Si vous n''êtes pas à l''origine de cette demande, ignorez ce message.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Aucun lien à cliquer","Vous demande de NE PAS partager le code","Envoyé parce que vous venez de vous connecter vous-même","Code court depuis un numéro court reconnu"]'::jsonb,
 'C''est un vrai code à deux facteurs (2FA). Il est sûr tant que c''est VOUS qui venez de le demander — saisissez-le uniquement dans l''appli ou le site où vous vous connectez. Ne le communiquez jamais à personne.',
 335),

-- ---------- fr-BE ----------
('fr-BE','sms','both','normal',
 'bpost','+32 460 21 34 55',
 'bpost n''envoie pas de SMS depuis un numéro de GSM et ne demande jamais de payer des frais via un lien.',
 'aujourd''hui 14:02','bpost',
 'Votre colis n''a pas pu être livré. Réglez 0,69 € de frais...',
 E'bpost : votre colis n''a pas pu être livré. Réglez les frais de relivraison de 0,69 € pour planifier une nouvelle livraison : {{link:0}}',
 '[{"label":"bpost-relivraison.com","real_url":"http://bpost-relivraison.com/payer","suspicious":true,"warning":"Le vrai site est bpost.be. « bpost-relivraison.com » est un faux. Un petit montant (0,69 €) est une ruse pour que vous saisissiez votre carte sans réfléchir."}]'::jsonb,
 TRUE,
 '["Numéro de GSM inconnu comme expéditeur","Montant minuscule — vous ne vous méfiez pas","Le lien mène à bpost-relivraison.com, pas bpost.be","Pression : payez pour relivrer"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing. bpost ne demande jamais de frais par SMS. Vous attendez un colis ? Vérifiez vous-même dans l''appli ou sur bpost.be en tapant l''adresse.',
 340),

('fr-BE','sms','both','normal',
 'Banque','+32 471 10 28 83',
 'Votre banque envoie uniquement des codes de vérification par SMS et n''y joint jamais de lien.',
 'aujourd''hui 11:20','Banque',
 'Connexion depuis un nouvel appareil. Ce n''était pas vous ?...',
 E'Votre banque : une connexion vient d''avoir lieu depuis un NOUVEL appareil. Ce n''était pas vous ? Sécurisez votre compte tout de suite : {{link:0}}',
 '[{"label":"securite-banque-acces.net","real_url":"http://securite-banque-acces.net","suspicious":true,"warning":"Votre vraie banque utilise son propre site et son appli. « securite-banque-acces.net » est un faux qui veut voler vos identifiants."}]'::jsonb,
 TRUE,
 '["Joue sur la peur (« appareil inconnu »)","Un lien dans un SMS bancaire — la banque ne fait jamais ça","Domaine securite-banque-acces.net non officiel","Incite à agir « tout de suite »"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing. Votre banque n''envoie jamais de SMS avec un lien de connexion. En cas de doute, ouvrez vous-même l''appli ou appelez le numéro figurant sur votre carte.',
 341),

('fr-BE','whatsapp','both','normal',
 'Numéro inconnu','+32 470 22 19 07',
 'Un message « nouveau numéro » d''un proche qui réclame aussitôt de l''argent et refuse d''appeler est presque toujours une arnaque.',
 'aujourd''hui 18:45','Numéro inconnu',
 'Coucou maman, c''est mon nouveau numéro. Mon GSM est cassé...',
 E'Coucou maman 👋 C''est mon nouveau numéro, mon ancien GSM est cassé. Tu peux m''aider ? Je dois payer une facture de 850 € aujourd''hui mais je n''arrive plus à accéder à mon appli bancaire. Tu peux avancer ? Je te rembourse demain. Je ne sais pas appeler, seulement écrire. ❤️',
 '[]'::jsonb,
 TRUE,
 '["Numéro inconnu se faisant passer pour un proche","« Nouveau numéro, ancien GSM cassé » — prétexte classique","Demande en urgence un virement","Refuse d''appeler — seulement écrire, pour que vous n''entendiez pas la voix"]'::jsonb,
 '[]'::jsonb,
 'C''est l''arnaque WhatsApp « bonjour maman/papa ». Appelez toujours votre enfant sur son numéro D''ORIGINE connu avant d''envoyer le moindre euro. L''escroc, justement, ne veut pas que vous appeliez.',
 342),

('fr-BE','whatsapp','both','normal',
 'Acheteur 2ememain','+32 468 90 33 41',
 'Un « acheteur » qui vous envoie un lien de paiement pour vous faire « recevoir » 1 centime est une arnaque connue.',
 'aujourd''hui 16:10','Acheteur 2ememain',
 'Bonjour ! Je veux acheter votre divan. Confirmez via ce lien...',
 E'Bonjour ! Je souhaite acheter votre divan sur 2ememain. Pour vérifier que votre compte fonctionne, je vous envoie 0,01 €. Cliquez sur ce lien et connectez-vous avec votre banque pour le recevoir : {{link:0}}',
 '[{"label":"2ememain-paiement-verif.com","real_url":"http://2ememain-paiement-verif.com/verify","suspicious":true,"warning":"On ne se connecte jamais pour RECEVOIR de l''argent. Ce lien mène à une fausse page de connexion qui vole vos données bancaires."}]'::jsonb,
 TRUE,
 '["On ne se connecte jamais pour RECEVOIR de l''argent","Montant minuscule (1 centime) comme appât","Lien vers 2ememain-paiement-verif.com — pas la vraie appli","En dehors de la messagerie officielle"]'::jsonb,
 '[]'::jsonb,
 'C''est une arnaque. Pour recevoir de l''argent, vous n''avez jamais à vous connecter quelque part. Restez dans l''appli officielle et ne cliquez pas sur les liens de paiement envoyés.',
 343),

('fr-BE','sms','both','normal',
 'Cabinet Dr Dubois','Cabinet','Un rappel de rendez-vous sans lien, avec un numéro que vous pouvez appeler, est normal.',
 'aujourd''hui 09:30','Cabinet Dr Dubois',
 'Rappel : votre rendez-vous demain à 10h40. Pour annuler : 02 345 67 89.',
 E'Cabinet du Dr Dubois : rappel de votre rendez-vous demain à 10h40. Empêché(e) ? Appelez-nous au 02 345 67 89. À demain !',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Aucun lien ni demande de paiement","Informations de rendez-vous concrètes et attendues","Un numéro que vous pouvez appeler vous-même","Nom de votre propre cabinet"]'::jsonb,
 'C''est un simple rappel de rendez-vous de votre médecin. Aucun lien, aucune donnée demandée — appelez librement si vous voulez le déplacer.',
 344),

('fr-BE','sms','both','normal',
 'CodeAcces','32100','Un vrai code de vérification ne contient pas de lien et vous demande de ne pas le partager.',
 'aujourd''hui 08:05','CodeAcces',
 'Votre code de vérification est 558019. Ne le partagez avec personne.',
 E'558019 est votre code de vérification. Ne le communiquez à personne. Si vous n''êtes pas à l''origine de cette demande, ignorez ce message.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Aucun lien à cliquer","Vous demande de NE PAS partager le code","Envoyé parce que vous venez de vous connecter vous-même","Code court depuis un numéro court reconnu"]'::jsonb,
 'C''est un vrai code à deux facteurs (2FA). Il est sûr tant que c''est VOUS qui venez de le demander — saisissez-le uniquement dans l''appli ou le site où vous vous connectez. Ne le communiquez jamais à personne.',
 345),

-- ---------- de ----------
('de','sms','both','normal',
 'DHL','+49 151 21 34 55 78',
 'DHL versendet keine SMS von einer Handynummer und verlangt nie eine Zahlung über einen Link.',
 'heute 14:02','DHL',
 'Ihr Paket konnte nicht zugestellt werden. Zahlen Sie 0,69 € Gebühr...',
 E'DHL: Ihr Paket konnte nicht zugestellt werden. Bitte zahlen Sie die offene Zustellgebühr von 0,69 €, um die erneute Zustellung zu veranlassen: {{link:0}}',
 '[{"label":"dhl-zustellung-neu.com","real_url":"http://dhl-zustellung-neu.com/zahlen","suspicious":true,"warning":"Die echte Seite ist dhl.de. „dhl-zustellung-neu.com\" ist gefälscht. Ein winziger Betrag (0,69 €) ist ein Trick, damit Sie Ihre Kartendaten unüberlegt eingeben."}]'::jsonb,
 TRUE,
 '["Unbekannte Handynummer als Absender","Winziger Betrag — man zögert nicht","Link führt zu dhl-zustellung-neu.com, nicht dhl.de","Druck: zahlen, um neu zustellen zu lassen"]'::jsonb,
 '[]'::jsonb,
 'Das ist Smishing (Phishing per SMS). DHL verlangt nie per SMS eine Zustellgebühr. Erwarten Sie ein Paket? Prüfen Sie es selbst in der DHL-App oder auf dhl.de — Adresse selbst eintippen.',
 350),

('de','sms','both','normal',
 'Sparkasse','+49 171 88 31 02',
 'Die Sparkasse sendet per SMS nur Bestätigungscodes und nie einen Link dazu.',
 'heute 11:20','Sparkasse',
 'Anmeldung von einem neuen Gerät. Waren Sie das nicht?...',
 E'Sparkasse: soeben erfolgte eine Anmeldung von einem NEUEN Gerät. Waren Sie das nicht? Sichern Sie Ihr Konto sofort: {{link:0}}',
 '[{"label":"sparkasse-sicher-login.net","real_url":"http://sparkasse-sicher-login.net","suspicious":true,"warning":"Die echte Sparkasse nutzt sparkasse.de und die App. „sparkasse-sicher-login.net\" ist gefälscht und will Ihre Zugangsdaten stehlen."}]'::jsonb,
 TRUE,
 '["Spielt mit der Angst (\"fremdes Gerät\")","Ein Link in einer Bank-SMS — das macht die Bank nie","Domain sparkasse-sicher-login.net ist nicht sparkasse.de","Drängt zum \"sofortigen\" Handeln"]'::jsonb,
 '[]'::jsonb,
 'Das ist Smishing. Ihre Bank sendet nie eine SMS mit Anmelde-Link. Im Zweifel öffnen Sie selbst die App oder rufen die Nummer auf Ihrer Bankkarte an.',
 351),

('de','whatsapp','both','normal',
 'Unbekannte Nummer','+49 152 22 19 07',
 'Eine „neue Nummer“-Nachricht von Angehörigen, die sofort um Geld bittet und nicht telefonieren will, ist fast immer Betrug.',
 'heute 18:45','Unbekannte Nummer',
 'Hallo Mama, das ist meine neue Nummer. Mein Handy ist kaputt...',
 E'Hallo Mama 👋 Das ist meine neue Nummer, mein altes Handy ist kaputt. Kannst du mir helfen? Ich muss heute eine Rechnung über 850 € bezahlen, komme aber nicht in meine Banking-App. Kannst du es auslegen? Ich zahle es dir morgen zurück. Anrufen geht gerade nicht, nur schreiben. ❤️',
 '[]'::jsonb,
 TRUE,
 '["Unbekannte Nummer gibt sich als Angehörige aus","„Neue Nummer, altes Handy kaputt“ — klassische Ausrede","Bittet dringend um eine Überweisung","Will NICHT telefonieren — nur schreiben, damit Sie die Stimme nicht hören"]'::jsonb,
 '[]'::jsonb,
 'Das ist der WhatsApp-Betrug „Hallo Mama/Papa“. Rufen Sie Ihr Kind immer unter der URSPRÜNGLICHEN, bekannten Nummer an, bevor Sie Geld senden. Ein Betrüger will gerade nicht, dass Sie anrufen.',
 352),

('de','whatsapp','both','normal',
 'Käufer Kleinanzeigen','+49 152 90 33 41',
 'Ein „Käufer“, der Ihnen einen Zahlungslink schickt, damit Sie 1 Cent „erhalten“, ist eine bekannte Masche.',
 'heute 16:10','Käufer Kleinanzeigen',
 'Hallo! Ich möchte Ihr Sofa kaufen. Bestätigen Sie über diesen Link...',
 E'Hallo! Ich möchte Ihr Sofa über Kleinanzeigen kaufen. Um zu prüfen, dass Ihr Konto funktioniert, sende ich Ihnen 0,01 €. Klicken Sie auf diesen Link und melden Sie sich mit Ihrer Bank an, um es zu erhalten: {{link:0}}',
 '[{"label":"kleinanzeigen-zahlcheck.com","real_url":"http://kleinanzeigen-zahlcheck.com/verify","suspicious":true,"warning":"Um Geld zu ERHALTEN, meldet man sich nie an. Dieser Link führt zu einer gefälschten Login-Seite, die Ihre Bankdaten stiehlt."}]'::jsonb,
 TRUE,
 '["Um Geld zu ERHALTEN, meldet man sich nie an","Verdächtig kleiner Betrag (1 Cent) als Köder","Link zu kleinanzeigen-zahlcheck.com — nicht die echte App","Außerhalb des offiziellen Chats"]'::jsonb,
 '[]'::jsonb,
 'Das ist Betrug. Um Geld zu erhalten, müssen Sie sich nirgends anmelden. Bleiben Sie in der offiziellen App und klicken Sie nicht auf zugesandte Zahlungslinks.',
 353),

('de','sms','both','normal',
 'Praxis Dr. Becker','Praxis','Eine Terminerinnerung ohne Link, mit einer Nummer, die Sie selbst anrufen können, ist normal.',
 'heute 09:30','Praxis Dr. Becker',
 'Erinnerung: Ihr Termin morgen um 10:40 Uhr. Absagen? 030 1234567.',
 E'Praxis Dr. Becker: Erinnerung an Ihren Termin morgen um 10:40 Uhr. Verhindert? Rufen Sie uns an unter 030 123 45 67. Bis morgen!',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Kein Link und keine Zahlungsaufforderung","Konkrete, erwartete Terminangaben","Eine Nummer, die Sie selbst anrufen können","Absendername Ihrer eigenen Praxis"]'::jsonb,
 'Das ist eine ganz normale Terminerinnerung Ihrer Praxis. Kein Link, keine Daten verlangt — rufen Sie ruhig an, wenn Sie verschieben möchten.',
 354),

('de','sms','both','normal',
 'Zugangscode','82200','Ein echter Bestätigungscode enthält keinen Link und fordert Sie auf, ihn nicht weiterzugeben.',
 'heute 08:05','Zugangscode',
 'Ihr Bestätigungscode lautet 558019. Geben Sie ihn niemandem weiter.',
 E'558019 ist Ihr Bestätigungscode. Geben Sie diesen Code an niemanden weiter. Falls Sie ihn nicht angefordert haben, ignorieren Sie diese Nachricht.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Kein Link zum Antippen","Fordert auf, den Code NICHT weiterzugeben","Gesendet, weil Sie sich gerade selbst anmelden wollten","Kurzer Code von einer erkennbaren Kurznummer"]'::jsonb,
 'Das ist ein echter Zwei-Faktor-Code (2FA). Er ist sicher, solange SIE ihn gerade angefordert haben — geben Sie ihn nur in der App oder auf der Seite ein, bei der Sie sich anmelden. Niemals an andere weitergeben.',
 355);

