-- ============================================================
-- FASE 1b: GEVORDERD smishing — subtiele sms/WhatsApp (difficulty='advanced').
-- Geen grove verraders (geen kapitalen, geen 1-cent-trucs). De tells zijn
-- procesmatig: een bank-sms met inloglink, een net-niet-domein, of een
-- 'baas' die rapport opbouwt vóór het verzoek. Eén legitiem bericht per
-- taal leert het verschil. sort_order vanaf 360.
-- ============================================================
INSERT INTO inbox_messages
  (locale, channel, audience, difficulty, category, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- ---------- NL ----------
('nl','sms','both','advanced','bank',
 'ING','ING',
 'Een echte fraudemelding van de bank zet er nooit een inloglink bij — ook niet als het bericht rustig en behulpzaam klinkt.',
 'vandaag 13:48','ING',
 'Betaling van € 329,00 aan Zalando gezien. Herkent u dit niet?...',
 E'ING: wij zagen zojuist een betaling van € 329,00 aan Zalando. Herkent u dit? Dan hoeft u niets te doen. Zo niet, blokkeer de betaling hier: {{link:0}}',
 '[{"label":"mijn-ing.veilig-controle.nl","real_url":"http://veilig-controle.nl/ing/login","suspicious":true,"warning":"Het lijkt op ing.nl, maar het echte domein is het deel net vóór .nl: hier veilig-controle.nl, niet ing.nl. De ING zet nooit een inloglink in een sms."}]'::jsonb,
 TRUE,
 '["Bank-sms met een inloglink — de ING doet dat nooit","Het echte domein is veilig-controle.nl, niet ing.nl","Geeft u een geruststelling (niets doen als het klopt) zodat het echt lijkt","Een herkenbaar bedrag en winkel maken het geloofwaardig"]'::jsonb,
 '[]'::jsonb,
 'Dit is geavanceerde smishing. Het bericht klinkt rustig en geeft u een uitweg, juist om vertrouwen te wekken. Een bank meldt fraude nooit met een inloglink in een sms. Controleer altijd zelf in de ING-app of bel het nummer op uw pas.',
 360),

('nl','sms','both','advanced','bezorger',
 'PostNL','PostNL',
 'Een verwacht pakket, een link naar het echte postnl.nl en géén vraag om te betalen of in te loggen: dat hoort bij een gewone bezorgmelding.',
 'vandaag 10:12','PostNL',
 'Uw pakket wordt vandaag bezorgd tussen 14:00 en 16:00. Volg het hier...',
 E'PostNL: uw pakket wordt vandaag bezorgd tussen 14:00 en 16:00. Volg de bezorging via {{link:0}}',
 '[{"label":"postnl.nl/tracktrace","real_url":"https://postnl.nl/tracktrace","suspicious":false,"warning":"Dit is het echte adres van PostNL (postnl.nl). Er wordt niet om betaling of inloggegevens gevraagd."}]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Link gaat naar het echte postnl.nl","Geen betaling of inloggegevens gevraagd","Past bij een pakket dat u verwacht","Concrete, normale bezorginformatie"]'::jsonb,
 'Dit is een echte bezorgmelding. De link wijst naar postnl.nl en er wordt niets gevraagd wat een oplichter wil (geld, inloggen). Twijfelt u? Open de PostNL-app zelf in plaats van op de link te tikken.',
 361),

('nl','whatsapp','business','advanced','ceo',
 'Onbekend nummer','+31 6 18 44 92 03',
 'Een baas die vanaf een onbekend nummer appt, haast maakt en liever niet laat bellen, is CEO-fraude — ook zonder dat er meteen om geld wordt gevraagd.',
 'vandaag 09:52','Onbekend nummer',
 'Hoi, met Marieke (directie). Nieuw werknummer. Ben je bereikbaar?...',
 E'Hoi, met Marieke van de directie 👋 Ik heb een nieuw werktoestel, vandaar dit nummer. Ben je even bereikbaar? Ik zit in een vergadering en moet zo iets geregeld krijgen met een leverancier. Bellen lukt niet, app me even of je achter je computer zit.',
 '[]'::jsonb,
 TRUE,
 '["Onbekend nummer dat zegt een leidinggevende te zijn","Nieuw werktoestel verklaart het vreemde nummer — klassieke truc","Bouwt eerst vertrouwen op vóór er een verzoek komt","Wil niet bellen en maakt subtiel haast (vergadering)"]'::jsonb,
 '[]'::jsonb,
 'Dit is CEO-fraude via WhatsApp. De oplichter doet zich voor als uw leidinggevende en bouwt eerst rapport op; pas daarna komt het verzoek (een spoedbetaling of cadeaubonnen). Verifieer altijd via een bekend, intern kanaal — bel het echte nummer of loop even langs.',
 362),

-- ---------- nl-BE ----------
('nl-BE','sms','both','advanced','bank',
 'KBC','KBC',
 'Een echte fraudemelding van de bank zet er nooit een aanmeldlink bij — ook niet als het bericht rustig en behulpzaam klinkt.',
 'vandaag 13:48','KBC',
 'Betaling van € 329,00 aan Coolblue gezien. Herkent u dit niet?...',
 E'KBC: wij zagen zonet een betaling van € 329,00 aan Coolblue. Herkent u dit? Dan hoeft u niets te doen. Zo niet, blokkeer de betaling hier: {{link:0}}',
 '[{"label":"mijn-kbc.veilig-controle.be","real_url":"http://veilig-controle.be/kbc/login","suspicious":true,"warning":"Het lijkt op kbc.be, maar het echte domein is het deel net vóór .be: hier veilig-controle.be, niet kbc.be. KBC zet nooit een aanmeldlink in een sms."}]'::jsonb,
 TRUE,
 '["Bank-sms met een aanmeldlink — KBC doet dat nooit","Het echte domein is veilig-controle.be, niet kbc.be","Geeft u een geruststelling (niets doen als het klopt) zodat het echt lijkt","Een herkenbaar bedrag en winkel maken het geloofwaardig"]'::jsonb,
 '[]'::jsonb,
 'Dit is geavanceerde smishing. Het bericht klinkt rustig en geeft u een uitweg, net om vertrouwen te wekken. Een bank meldt fraude nooit met een aanmeldlink in een sms. Controleer altijd zelf in de KBC-app of bel het nummer op uw kaart.',
 365),

('nl-BE','sms','both','advanced','bezorger',
 'bpost','bpost',
 'Een verwacht pakje, een link naar het echte bpost.be en géén vraag om te betalen of aan te melden: dat hoort bij een gewone leveringsmelding.',
 'vandaag 10:12','bpost',
 'Uw pakje wordt vandaag geleverd tussen 14:00 en 16:00. Volg het hier...',
 E'bpost: uw pakje wordt vandaag geleverd tussen 14:00 en 16:00. Volg de levering via {{link:0}}',
 '[{"label":"bpost.be/tracking","real_url":"https://bpost.be/tracking","suspicious":false,"warning":"Dit is het echte adres van bpost (bpost.be). Er wordt niet om betaling of aanmeldgegevens gevraagd."}]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Link gaat naar het echte bpost.be","Geen betaling of aanmeldgegevens gevraagd","Past bij een pakje dat u verwacht","Concrete, normale leveringsinformatie"]'::jsonb,
 'Dit is een echte leveringsmelding. De link wijst naar bpost.be en er wordt niets gevraagd wat een oplichter wil (geld, aanmelden). Twijfelt u? Open de bpost-app zelf in plaats van op de link te tikken.',
 366),

('nl-BE','whatsapp','business','advanced','ceo',
 'Onbekend nummer','+32 470 18 44 92',
 'Een baas die vanaf een onbekend nummer appt, haast maakt en liever niet laat bellen, is CEO-fraude — ook zonder dat er meteen om geld wordt gevraagd.',
 'vandaag 09:52','Onbekend nummer',
 'Dag, met An (directie). Nieuw werknummer. Ben je bereikbaar?...',
 E'Dag, met An van de directie 👋 Ik heb een nieuw werktoestel, vandaar dit nummer. Ben je even bereikbaar? Ik zit in een vergadering en moet zo iets geregeld krijgen met een leverancier. Bellen lukt niet, app me even of je achter je computer zit.',
 '[]'::jsonb,
 TRUE,
 '["Onbekend nummer dat zegt een leidinggevende te zijn","Nieuw werktoestel verklaart het vreemde nummer — klassieke truc","Bouwt eerst vertrouwen op vóór er een verzoek komt","Wil niet bellen en maakt subtiel haast (vergadering)"]'::jsonb,
 '[]'::jsonb,
 'Dit is CEO-fraude via WhatsApp. De oplichter doet zich voor als uw leidinggevende en bouwt eerst rapport op; pas daarna komt het verzoek (een spoedbetaling of cadeaubonnen). Verifieer altijd via een bekend, intern kanaal — bel het echte nummer of ga even langs.',
 367),

-- ---------- en (UK) ----------
('en','sms','both','advanced','bank',
 'Barclays','Barclays',
 'A genuine fraud alert from your bank never includes a login link — even when the message sounds calm and helpful.',
 'today 13:48','Barclays',
 'Payment of £329.00 to Amazon seen. Do not recognise it?...',
 E'Barclays: we have just seen a payment of £329.00 to Amazon. Recognise it? Then you need do nothing. If not, block the payment here: {{link:0}}',
 '[{"label":"my-barclays.secure-review.co.uk","real_url":"http://secure-review.co.uk/barclays/login","suspicious":true,"warning":"It looks like barclays.co.uk, but the real domain is the part just before .co.uk: here secure-review.co.uk, not barclays.co.uk. Barclays never puts a login link in a text."}]'::jsonb,
 TRUE,
 '["Bank text with a login link — Barclays never does this","The real domain is secure-review.co.uk, not barclays.co.uk","Offers reassurance (do nothing if it was you) to seem genuine","A believable amount and shop make it convincing"]'::jsonb,
 '[]'::jsonb,
 'This is advanced smishing. The message sounds calm and gives you an easy out, precisely to earn your trust. A bank never reports fraud with a login link in a text. Always check yourself in the Barclays app or call the number on your card.',
 370),

('en','sms','both','advanced','bezorger',
 'Royal Mail','Royal Mail',
 'An expected parcel, a link to the real royalmail.com and no request to pay or log in: that is what a normal delivery update looks like.',
 'today 10:12','Royal Mail',
 'Your parcel will be delivered today between 2pm and 4pm. Track it here...',
 E'Royal Mail: your parcel will be delivered today between 2pm and 4pm. Track the delivery here: {{link:0}}',
 '[{"label":"royalmail.com/track","real_url":"https://royalmail.com/track","suspicious":false,"warning":"This is the real Royal Mail address (royalmail.com). No payment or login details are requested."}]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Link goes to the real royalmail.com","No payment or login details requested","Matches a parcel you are expecting","Concrete, ordinary delivery information"]'::jsonb,
 'This is a genuine delivery update. The link points to royalmail.com and nothing a scammer wants (money, login) is asked. Unsure? Open the Royal Mail app yourself instead of tapping the link.',
 371),

('en','whatsapp','business','advanced','ceo',
 'Unknown number','+44 7700 184492',
 'A boss who messages from an unknown number, creates urgency and would rather you did not call is CEO fraud — even when no money is asked for yet.',
 'today 09:52','Unknown number',
 'Hi, it is Sarah (management). New work number. Are you around?...',
 E'Hi, it is Sarah from management 👋 I have a new work phone, hence this number. Are you around for a moment? I am in a meeting and need something sorted with a supplier shortly. Can not call, just text me whether you are at your computer.',
 '[]'::jsonb,
 TRUE,
 '["Unknown number claiming to be a manager","A new work phone explains the odd number — classic trick","Builds trust first, before any request comes","Will not call and subtly creates urgency (a meeting)"]'::jsonb,
 '[]'::jsonb,
 'This is CEO fraud over WhatsApp. The scammer poses as your manager and builds rapport first; the request (an urgent payment or gift cards) comes only afterwards. Always verify through a known, internal channel — call the real number or walk over.',
 372),

-- ---------- fr ----------
('fr','sms','both','advanced','bank',
 'Crédit Agricole','Credit Agricole',
 'Une vraie alerte fraude de votre banque ne contient jamais de lien de connexion — même si le message paraît calme et serviable.',
 'aujourd''hui 13:48','Crédit Agricole',
 'Paiement de 329,00 € chez Amazon constaté. Vous ne le reconnaissez pas ?...',
 E'Crédit Agricole : nous venons de constater un paiement de 329,00 € chez Amazon. Vous le reconnaissez ? Alors rien à faire. Sinon, bloquez le paiement ici : {{link:0}}',
 '[{"label":"mon-ca.securite-verif.fr","real_url":"http://securite-verif.fr/ca/login","suspicious":true,"warning":"Cela ressemble à credit-agricole.fr, mais le vrai domaine est la partie juste avant .fr : ici securite-verif.fr, pas credit-agricole.fr. La banque ne met jamais de lien de connexion dans un SMS."}]'::jsonb,
 TRUE,
 '["SMS bancaire avec un lien de connexion — la banque ne fait jamais ça","Le vrai domaine est securite-verif.fr, pas credit-agricole.fr","Offre une réassurance (rien à faire si c''est vous) pour paraître authentique","Un montant et une enseigne crédibles renforcent l''illusion"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing avancé. Le message est calme et vous offre une sortie facile, justement pour gagner votre confiance. Une banque ne signale jamais une fraude avec un lien de connexion par SMS. Vérifiez toujours vous-même dans l''appli ou appelez le numéro figurant sur votre carte.',
 375),

('fr','sms','both','advanced','bezorger',
 'Colissimo','Colissimo',
 'Un colis attendu, un lien vers le vrai laposte.fr et aucune demande de paiement ou de connexion : c''est à cela que ressemble un avis de livraison normal.',
 'aujourd''hui 10:12','Colissimo',
 'Votre colis sera livré aujourd''hui entre 14h et 16h. Suivez-le ici...',
 E'Colissimo : votre colis sera livré aujourd''hui entre 14h et 16h. Suivez la livraison ici : {{link:0}}',
 '[{"label":"laposte.fr/suivi","real_url":"https://laposte.fr/outils/suivre-vos-envois","suspicious":false,"warning":"C''est la vraie adresse de La Poste (laposte.fr). Aucun paiement ni identifiant n''est demandé."}]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Le lien mène au vrai laposte.fr","Aucun paiement ni identifiant demandé","Correspond à un colis que vous attendez","Informations de livraison concrètes et normales"]'::jsonb,
 'C''est un vrai avis de livraison. Le lien pointe vers laposte.fr et rien de ce qu''un escroc recherche (argent, connexion) n''est demandé. Un doute ? Ouvrez l''appli vous-même au lieu de cliquer sur le lien.',
 376),

('fr','whatsapp','business','advanced','ceo',
 'Numéro inconnu','+33 6 18 44 92 03',
 'Un patron qui écrit depuis un numéro inconnu, crée de l''urgence et préfère que vous n''appeliez pas, c''est de la fraude au président — même sans demande d''argent immédiate.',
 'aujourd''hui 09:52','Numéro inconnu',
 'Bonjour, c''est Sophie (direction). Nouveau numéro pro. Vous êtes là ?...',
 E'Bonjour, c''est Sophie de la direction 👋 J''ai un nouveau téléphone pro, d''où ce numéro. Vous êtes disponible un instant ? Je suis en réunion et je dois faire régler quelque chose avec un fournisseur sous peu. Je ne peux pas appeler, écrivez-moi juste si vous êtes devant votre ordinateur.',
 '[]'::jsonb,
 TRUE,
 '["Numéro inconnu se faisant passer pour un dirigeant","Un nouveau téléphone pro explique le numéro étrange — ruse classique","Installe d''abord la confiance, avant toute demande","Refuse d''appeler et crée subtilement l''urgence (une réunion)"]'::jsonb,
 '[]'::jsonb,
 'C''est la fraude au président via WhatsApp. L''escroc se fait passer pour votre dirigeant et crée d''abord un climat de confiance ; la demande (un virement urgent ou des cartes cadeaux) ne vient qu''ensuite. Vérifiez toujours par un canal interne connu — appelez le vrai numéro ou passez le voir.',
 377),

-- ---------- fr-BE ----------
('fr-BE','sms','both','advanced','bank',
 'Belfius','Belfius',
 'Une vraie alerte fraude de votre banque ne contient jamais de lien de connexion — même si le message paraît calme et serviable.',
 'aujourd''hui 13:48','Belfius',
 'Paiement de 329,00 € chez Coolblue constaté. Vous ne le reconnaissez pas ?...',
 E'Belfius : nous venons de constater un paiement de 329,00 € chez Coolblue. Vous le reconnaissez ? Alors rien à faire. Sinon, bloquez le paiement ici : {{link:0}}',
 '[{"label":"mon-belfius.securite-verif.be","real_url":"http://securite-verif.be/belfius/login","suspicious":true,"warning":"Cela ressemble à belfius.be, mais le vrai domaine est la partie juste avant .be : ici securite-verif.be, pas belfius.be. La banque ne met jamais de lien de connexion dans un SMS."}]'::jsonb,
 TRUE,
 '["SMS bancaire avec un lien de connexion — la banque ne fait jamais ça","Le vrai domaine est securite-verif.be, pas belfius.be","Offre une réassurance (rien à faire si c''est vous) pour paraître authentique","Un montant et une enseigne crédibles renforcent l''illusion"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing avancé. Le message est calme et vous offre une sortie facile, justement pour gagner votre confiance. Une banque ne signale jamais une fraude avec un lien de connexion par SMS. Vérifiez toujours vous-même dans l''appli ou appelez le numéro figurant sur votre carte.',
 380),

('fr-BE','sms','both','advanced','bezorger',
 'bpost','bpost',
 'Un colis attendu, un lien vers le vrai bpost.be et aucune demande de paiement ou de connexion : c''est à cela que ressemble un avis de livraison normal.',
 'aujourd''hui 10:12','bpost',
 'Votre colis sera livré aujourd''hui entre 14h et 16h. Suivez-le ici...',
 E'bpost : votre colis sera livré aujourd''hui entre 14h et 16h. Suivez la livraison ici : {{link:0}}',
 '[{"label":"bpost.be/suivi","real_url":"https://bpost.be/fr/suivi-colis","suspicious":false,"warning":"C''est la vraie adresse de bpost (bpost.be). Aucun paiement ni identifiant n''est demandé."}]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Le lien mène au vrai bpost.be","Aucun paiement ni identifiant demandé","Correspond à un colis que vous attendez","Informations de livraison concrètes et normales"]'::jsonb,
 'C''est un vrai avis de livraison. Le lien pointe vers bpost.be et rien de ce qu''un escroc recherche (argent, connexion) n''est demandé. Un doute ? Ouvrez l''appli vous-même au lieu de cliquer sur le lien.',
 381),

('fr-BE','whatsapp','business','advanced','ceo',
 'Numéro inconnu','+32 470 18 44 92',
 'Un patron qui écrit depuis un numéro inconnu, crée de l''urgence et préfère que vous n''appeliez pas, c''est de la fraude au président — même sans demande d''argent immédiate.',
 'aujourd''hui 09:52','Numéro inconnu',
 'Bonjour, c''est Sophie (direction). Nouveau numéro pro. Vous êtes là ?...',
 E'Bonjour, c''est Sophie de la direction 👋 J''ai un nouveau téléphone pro, d''où ce numéro. Vous êtes disponible un instant ? Je suis en réunion et je dois faire régler quelque chose avec un fournisseur sous peu. Je ne sais pas appeler, écrivez-moi juste si vous êtes devant votre ordinateur.',
 '[]'::jsonb,
 TRUE,
 '["Numéro inconnu se faisant passer pour un dirigeant","Un nouveau téléphone pro explique le numéro étrange — ruse classique","Installe d''abord la confiance, avant toute demande","Refuse d''appeler et crée subtilement l''urgence (une réunion)"]'::jsonb,
 '[]'::jsonb,
 'C''est la fraude au président via WhatsApp. L''escroc se fait passer pour votre dirigeant et crée d''abord un climat de confiance ; la demande (un virement urgent ou des cartes cadeaux) ne vient qu''ensuite. Vérifiez toujours par un canal interne connu — appelez le vrai numéro ou passez le voir.',
 382),

-- ---------- de ----------
('de','sms','both','advanced','bank',
 'Sparkasse','Sparkasse',
 'Eine echte Betrugswarnung Ihrer Bank enthält nie einen Login-Link — auch wenn die Nachricht ruhig und hilfsbereit klingt.',
 'heute 13:48','Sparkasse',
 'Zahlung über 329,00 € an Amazon bemerkt. Erkennen Sie das nicht?...',
 E'Sparkasse: wir haben soeben eine Zahlung über 329,00 € an Amazon bemerkt. Erkennen Sie sie? Dann brauchen Sie nichts zu tun. Falls nicht, sperren Sie die Zahlung hier: {{link:0}}',
 '[{"label":"meine-sparkasse.sicher-pruefung.de","real_url":"http://sicher-pruefung.de/sparkasse/login","suspicious":true,"warning":"Es sieht aus wie sparkasse.de, aber die echte Domain ist der Teil direkt vor .de: hier sicher-pruefung.de, nicht sparkasse.de. Die Bank setzt nie einen Login-Link in eine SMS."}]'::jsonb,
 TRUE,
 '["Bank-SMS mit Login-Link — die Sparkasse macht das nie","Die echte Domain ist sicher-pruefung.de, nicht sparkasse.de","Bietet eine Beruhigung (nichts tun, wenn es Sie waren), um echt zu wirken","Ein glaubhafter Betrag und Händler machen es überzeugend"]'::jsonb,
 '[]'::jsonb,
 'Das ist fortgeschrittenes Smishing. Die Nachricht klingt ruhig und bietet einen einfachen Ausweg, gerade um Vertrauen zu gewinnen. Eine Bank meldet Betrug nie mit einem Login-Link per SMS. Prüfen Sie immer selbst in der App oder rufen Sie die Nummer auf Ihrer Karte an.',
 385),

('de','sms','both','advanced','bezorger',
 'DHL','DHL',
 'Ein erwartetes Paket, ein Link zur echten dhl.de und keine Aufforderung zu zahlen oder sich anzumelden: So sieht eine normale Zustellinfo aus.',
 'heute 10:12','DHL',
 'Ihr Paket wird heute zwischen 14 und 16 Uhr zugestellt. Verfolgen Sie es hier...',
 E'DHL: Ihr Paket wird heute zwischen 14 und 16 Uhr zugestellt. Verfolgen Sie die Zustellung hier: {{link:0}}',
 '[{"label":"dhl.de/sendungsverfolgung","real_url":"https://dhl.de/sendungsverfolgung","suspicious":false,"warning":"Das ist die echte DHL-Adresse (dhl.de). Es werden weder Zahlung noch Anmeldedaten verlangt."}]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Link führt zur echten dhl.de","Keine Zahlung oder Anmeldedaten verlangt","Passt zu einem Paket, das Sie erwarten","Konkrete, normale Zustellinformation"]'::jsonb,
 'Das ist eine echte Zustellinfo. Der Link führt zu dhl.de und es wird nichts verlangt, was ein Betrüger will (Geld, Anmeldung). Unsicher? Öffnen Sie die DHL-App selbst, statt auf den Link zu tippen.',
 386),

('de','whatsapp','business','advanced','ceo',
 'Unbekannte Nummer','+49 152 18 44 92',
 'Eine Chefin, die von einer unbekannten Nummer schreibt, Druck aufbaut und lieber nicht telefonieren möchte, ist CEO-Betrug — auch wenn noch kein Geld verlangt wird.',
 'heute 09:52','Unbekannte Nummer',
 'Hallo, hier Andrea (Geschäftsführung). Neue Dienstnummer. Erreichbar?...',
 E'Hallo, hier Andrea aus der Geschäftsführung 👋 Ich habe ein neues Diensthandy, daher diese Nummer. Sind Sie kurz erreichbar? Ich bin in einer Besprechung und muss gleich etwas mit einem Lieferanten klären. Anrufen geht nicht, schreiben Sie mir kurz, ob Sie am Rechner sind.',
 '[]'::jsonb,
 TRUE,
 '["Unbekannte Nummer gibt sich als Führungskraft aus","Ein neues Diensthandy erklärt die fremde Nummer — klassische Masche","Baut erst Vertrauen auf, bevor eine Bitte kommt","Will nicht telefonieren und baut subtil Druck auf (Besprechung)"]'::jsonb,
 '[]'::jsonb,
 'Das ist CEO-Betrug über WhatsApp. Der Betrüger gibt sich als Ihre Führungskraft aus und baut zuerst eine Beziehung auf; die Bitte (eine dringende Zahlung oder Gutscheinkarten) kommt erst danach. Prüfen Sie immer über einen bekannten, internen Weg — rufen Sie die echte Nummer an oder gehen Sie kurz vorbei.',
 387);


