-- ============================================================
-- PHASE 4 — AI-grade phishing (advanced, e-mail)
-- Foutloze, hyper-gepersonaliseerde berichten zonder klassieke
-- verraders. De enige signalen zijn proces-/verificatie-rode
-- vlaggen: ongebruikelijk verzoek, geen tweede kanaal, lichte
-- domeinafwijking, urgentie. Per locale: (1) CEO-fraude,
-- AI-gepolijst; (2) deepfake-voicemail-vervolg.
-- ============================================================

INSERT INTO inbox_messages
  (locale, audience, sender_name, sender_address, sender_note, received_label,
   subject, preview, body, links, is_phishing, red_flags, green_flags,
   explanation, sort_order, difficulty) VALUES

-- ---------------- nl ----------------
('nl', 'both',
 'Mark de Vries',
 'mark.devries@kestrel-finance.nl',
 'Let op het domein: kestrel-finance.nl. Uw organisatie gebruikt kestrel.nl. Eén bijgevoegd woord maakt het een ander, vreemd domein.',
 'vandaag 08:42',
 'Even kort: goedkeuring factuur project Zonnewende',
 'Beste Sanne, goed je gisteren te spreken over Zonnewende. De leverancier heeft...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Beste Sanne,</p><p>Goed je gisteren te spreken over de oplevering van project Zonnewende. Onze leverancier heeft net laten weten dat hun rekeningnummer is gewijzigd, en de openstaande factuur kan helaas niet wachten tot maandag.</p><p>Zou je de betaling vandaag nog willen goedkeuren via {{link:0}}? Ik zit de rest van de dag in vergaderingen, dus bel me liever niet — een kort bericht is genoeg.</p><p>Alvast bedankt voor het snel oppakken.</p><p>Hartelijke groet,<br>Mark de Vries<br>Financieel manager</p></div></div>',
 '[{"label":"Betaling goedkeuren","real_url":"http://kestrel-finance.nl/portal/approve?inv=ZW-2026-0418","suspicious":true,"warning":"Deze link gaat naar kestrel-finance.nl, niet naar uw eigen kestrel.nl. Keur nooit een betaling goed via een link uit een e-mail — log in op het bekende portaal of bel uw collega op een nummer dat u zelf kent."}]'::jsonb,
 TRUE,
 '["Het domein kestrel-finance.nl lijkt op uw organisatie, maar wijkt subtiel af van kestrel.nl","Ongebruikelijk verzoek: een betaling spoedig goedkeuren via een link","Urgentie rond geld (kan niet wachten tot maandag) zet u onder druk","De afzender vraagt u uitdrukkelijk om NIET te bellen — precies het tweede kanaal dat de truc zou ontmaskeren","Een gewijzigd rekeningnummer is een klassiek teken van factuurfraude"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing (CEO-fraude). De taal is foutloos en persoonlijk — uw naam, een echt klinkend project, de stijl van een collega. Juist daarom is het gevaarlijk: u kunt het niet aan spelfouten herkennen. Vertrouw op het proces, niet op de verzorgdheid. Verifieer elk spoedverzoek rond geld via een tweede, onafhankelijk kanaal: bel Mark op een nummer dat u zelf kent of loop even langs. Klik nooit op een goedkeuringslink uit een e-mail.',
 400, 'advanced'),

('nl', 'both',
 'Mark de Vries',
 'm.devries@kestrel.nl',
 'Een bekende naam of stem is geen bewijs. Een ingesproken bericht kan zijn nagemaakt met AI (deepfake-voice).',
 'vandaag 09:18',
 'Vervolg op mijn voicemail van zojuist',
 'Beste Sanne, zoals ik net in mijn voicemail zei: kun je dit vandaag nog regelen...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Beste Sanne,</p><p>Zoals ik zojuist in mijn voicemail al zei: we moeten dit vandaag nog rondkrijgen. Ik ben onderweg en heb slecht bereik, dus mailen is makkelijker.</p><p>Wil je voor de nieuwe leverancier vier cadeaubonnen van elk 100 euro aanschaffen en de codes hier naar mij terugsturen? Ik leg straks uit waarvoor het is — het is voor een attentie die vandaag de deur uit moet.</p><p>Reken maar op mij voor de afhandeling. Dank je!</p><p>Groet,<br>Mark</p></div></div>',
 '[]'::jsonb,
 TRUE,
 '["Een verwijzing naar een voicemail van een bekende stem is geen bewijs — stemmen zijn met AI na te maken","Het verzoek om cadeaubonnen te kopen en codes door te sturen is een klassiek fraudepatroon","Urgentie (vandaag nog) en een reden om niet te kunnen bellen (slecht bereik) blokkeren juist het tweede kanaal","De uitleg over het waarom komt steeds later — een afleidingstactiek","Verifieer nooit op basis van de e-mail zelf; gebruik een onafhankelijk kanaal"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. De verwijzing naar een ingesproken bericht van een bekende stem voelt overtuigend, maar een stem is met AI na te maken — een bekende stem of naam is geen bewijs meer. Een echte leidinggevende vraagt niet om cadeauboncodes per e-mail. Verifieer dit via een tweede, onafhankelijk kanaal: bel Mark terug op een nummer dat u zelf kent. Doe nooit een aankoop op basis van alleen een mail of voicemail.',
 410, 'advanced'),

-- ---------------- nl-BE ----------------
('nl-BE', 'both',
 'Mark de Vries',
 'mark.devries@kestrel-finance.be',
 'Let op het domein: kestrel-finance.be. Uw organisatie gebruikt kestrel.be. Eén bijgevoegd woord maakt het een ander, vreemd domein.',
 'vandaag 08:42',
 'Even kort: goedkeuring factuur project Zonnewende',
 'Dag Sanne, fijn je gisteren te spreken over Zonnewende. De leverancier heeft...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Dag Sanne,</p><p>Fijn je gisteren te spreken over de oplevering van project Zonnewende. Onze leverancier heeft net laten weten dat hun rekeningnummer is gewijzigd, en de openstaande factuur kan jammer genoeg niet wachten tot maandag.</p><p>Zou je de betaling vandaag nog willen goedkeuren via {{link:0}}? Ik zit de rest van de dag in vergaderingen, dus bel me liever niet — een kort bericht volstaat.</p><p>Alvast bedankt om dit snel op te nemen.</p><p>Vriendelijke groeten,<br>Mark de Vries<br>Financieel manager</p></div></div>',
 '[{"label":"Betaling goedkeuren","real_url":"http://kestrel-finance.be/portal/approve?inv=ZW-2026-0418","suspicious":true,"warning":"Deze link gaat naar kestrel-finance.be, niet naar uw eigen kestrel.be. Keur nooit een betaling goed via een link uit een e-mail — log in op het bekende portaal of bel uw collega op een nummer dat u zelf kent."}]'::jsonb,
 TRUE,
 '["Het domein kestrel-finance.be lijkt op uw organisatie, maar wijkt subtiel af van kestrel.be","Ongewone vraag: een betaling spoedig goedkeuren via een link","Urgentie rond geld (kan niet wachten tot maandag) zet u onder druk","De afzender vraagt u uitdrukkelijk om NIET te bellen — net het tweede kanaal dat de truc zou ontmaskeren","Een gewijzigd rekeningnummer is een klassiek teken van factuurfraude"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing (CEO-fraude). De taal is foutloos en persoonlijk — uw naam, een echt klinkend project, de stijl van een collega. Net daarom is het gevaarlijk: u kunt het niet aan spelfouten herkennen. Vertrouw op het proces, niet op de verzorgdheid. Verifieer elke dringende vraag rond geld via een tweede, onafhankelijk kanaal: bel Mark op een nummer dat u zelf kent of ga even langs. Klik nooit op een goedkeuringslink uit een e-mail.',
 400, 'advanced'),

('nl-BE', 'both',
 'Mark de Vries',
 'm.devries@kestrel.be',
 'Een bekende naam of stem is geen bewijs. Een ingesproken bericht kan nagemaakt zijn met AI (deepfake-voice).',
 'vandaag 09:18',
 'Vervolg op mijn voicemail van daarnet',
 'Dag Sanne, zoals ik daarnet in mijn voicemail zei: kun je dit vandaag nog regelen...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Dag Sanne,</p><p>Zoals ik daarnet in mijn voicemail al zei: we moeten dit vandaag nog rond krijgen. Ik ben onderweg en heb slecht bereik, dus mailen is makkelijker.</p><p>Wil je voor de nieuwe leverancier vier cadeaubonnen van elk 100 euro aankopen en de codes hier naar mij terugsturen? Ik leg straks uit waarvoor het dient — het is voor een attentie die vandaag nog weg moet.</p><p>Reken maar op mij voor de afhandeling. Dank je!</p><p>Groeten,<br>Mark</p></div></div>',
 '[]'::jsonb,
 TRUE,
 '["Een verwijzing naar een voicemail van een bekende stem is geen bewijs — stemmen zijn met AI na te maken","De vraag om cadeaubonnen te kopen en codes door te sturen is een klassiek fraudepatroon","Urgentie (vandaag nog) en een reden om niet te kunnen bellen (slecht bereik) blokkeren net het tweede kanaal","De uitleg over het waarom komt steeds later — een afleidingstactiek","Verifieer nooit op basis van de e-mail zelf; gebruik een onafhankelijk kanaal"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. De verwijzing naar een ingesproken bericht van een bekende stem voelt overtuigend, maar een stem is met AI na te maken — een bekende stem of naam is geen bewijs meer. Een echte leidinggevende vraagt niet om cadeauboncodes per e-mail. Verifieer dit via een tweede, onafhankelijk kanaal: bel Mark terug op een nummer dat u zelf kent. Doe nooit een aankoop op basis van enkel een mail of voicemail.',
 410, 'advanced'),

-- ---------------- en ----------------
('en', 'both',
 'Mark de Vries',
 'mark.devries@kestrel-finance.com',
 'Note the domain: kestrel-finance.com. Your organisation uses kestrel.com. One extra word makes it a different, foreign domain.',
 'today 08:42',
 'Quick one: approval for Solstice project invoice',
 'Hi Sanne, good to catch up yesterday about Solstice. The supplier has just...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Hi Sanne,</p><p>Good to catch up yesterday about the Solstice project delivery. Our supplier has just let us know their account number has changed, and unfortunately the outstanding invoice can’t wait until Monday.</p><p>Could you approve the payment today via {{link:0}}? I’m in meetings for the rest of the day, so please don’t call — a quick message is fine.</p><p>Thanks for picking this up quickly.</p><p>Best regards,<br>Mark de Vries<br>Finance Manager</p></div></div>',
 '[{"label":"Approve payment","real_url":"http://kestrel-finance.com/portal/approve?inv=SOL-2026-0418","suspicious":true,"warning":"This link goes to kestrel-finance.com, not your own kestrel.com. Never approve a payment from an email link — log in to the known portal or call your colleague on a number you already have."}]'::jsonb,
 TRUE,
 '["The domain kestrel-finance.com looks like your organisation but differs subtly from kestrel.com","Unusual request: approve a payment urgently via a link","Urgency around money (can not wait until Monday) puts you under pressure","The sender explicitly asks you NOT to call — exactly the second channel that would expose the trick","A changed account number is a classic sign of invoice fraud"]'::jsonb,
 '[]'::jsonb,
 'This is phishing (CEO fraud). The language is flawless and personal — your name, a real-sounding project, a colleague’s style. That is precisely why it is dangerous: you can not catch it by spelling mistakes. Trust the process, not the polish. Verify any urgent money request through a second, independent channel: call Mark on a number you already have, or walk over. Never click an approval link from an email.',
 400, 'advanced'),

('en', 'both',
 'Mark de Vries',
 'm.devries@kestrel.com',
 'A familiar name or voice is not proof. A voicemail can be faked with AI (deepfake voice).',
 'today 09:18',
 'Following up on my voicemail just now',
 'Hi Sanne, as I mentioned in my voicemail just now, can you sort this today...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Hi Sanne,</p><p>As I mentioned in my voicemail just now, we need to get this done today. I’m on the road with poor signal, so email is easier.</p><p>Could you buy four gift cards of 100 euros each for our new supplier and send me the codes here? I’ll explain what it’s for shortly — it’s a thank-you gift that has to go out today.</p><p>Count on me to handle the rest. Thanks!</p><p>Mark</p></div></div>',
 '[]'::jsonb,
 TRUE,
 '["A reference to a voicemail from a familiar voice is not proof — voices can be cloned with AI","The request to buy gift cards and send the codes is a classic fraud pattern","Urgency (today) and a reason not to call (poor signal) block the very second channel that would help","The reason “why” keeps being deferred — a distraction tactic","Never verify based on the email itself; use an independent channel"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. The reference to a voicemail from a familiar voice feels convincing, but a voice can be cloned with AI — a familiar voice or name is no longer proof. A real manager does not ask for gift card codes by email. Verify through a second, independent channel: call Mark back on a number you already have. Never make a purchase based on an email or voicemail alone.',
 410, 'advanced'),

-- ---------------- fr ----------------
('fr', 'both',
 'Marc Dupont',
 'marc.dupont@kestrel-finance.fr',
 'Attention au domaine : kestrel-finance.fr. Votre organisation utilise kestrel.fr. Un mot ajouté en fait un domaine différent et étranger.',
 'aujourd’hui 08:42',
 'Rapide : validation de la facture du projet Solstice',
 'Bonjour Sanne, content d’avoir échangé hier au sujet de Solstice. Le fournisseur...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Bonjour Sanne,</p><p>Content d’avoir échangé hier au sujet de la livraison du projet Solstice. Notre fournisseur vient de nous informer que son numéro de compte a changé, et la facture en attente ne peut malheureusement pas attendre lundi.</p><p>Pourrais-tu valider le paiement aujourd’hui via {{link:0}} ? Je suis en réunion le reste de la journée, alors évite de m’appeler — un petit message suffit.</p><p>Merci de prendre cela en charge rapidement.</p><p>Bien cordialement,<br>Marc Dupont<br>Directeur financier</p></div></div>',
 '[{"label":"Valider le paiement","real_url":"http://kestrel-finance.fr/portal/approve?inv=SOL-2026-0418","suspicious":true,"warning":"Ce lien mène vers kestrel-finance.fr, pas vers votre propre kestrel.fr. Ne validez jamais un paiement depuis un lien d’e-mail — connectez-vous au portail connu ou appelez votre collègue sur un numéro que vous avez déjà."}]'::jsonb,
 TRUE,
 '["Le domaine kestrel-finance.fr ressemble à votre organisation mais diffère subtilement de kestrel.fr","Demande inhabituelle : valider un paiement en urgence via un lien","L’urgence autour de l’argent (ne peut pas attendre lundi) vous met sous pression","L’expéditeur vous demande explicitement de NE PAS appeler — précisément le second canal qui démasquerait l’arnaque","Un changement de numéro de compte est un signe classique de fraude à la facture"]'::jsonb,
 '[]'::jsonb,
 'Il s’agit de phishing (fraude au président). La langue est impeccable et personnelle — votre nom, un projet crédible, le style d’un collègue. C’est précisément ce qui la rend dangereuse : vous ne pouvez pas la repérer aux fautes d’orthographe. Fiez-vous au processus, pas à la qualité de la rédaction. Vérifiez toute demande urgente d’argent par un second canal indépendant : appelez Marc sur un numéro que vous avez déjà, ou allez le voir. Ne cliquez jamais sur un lien de validation reçu par e-mail.',
 400, 'advanced'),

('fr', 'both',
 'Marc Dupont',
 'm.dupont@kestrel.fr',
 'Un nom ou une voix connue n’est pas une preuve. Un message vocal peut être imité avec l’IA (voix deepfake).',
 'aujourd’hui 09:18',
 'Suite à mon message vocal de tout à l’heure',
 'Bonjour Sanne, comme je l’ai dit dans mon message vocal, peux-tu régler cela...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Bonjour Sanne,</p><p>Comme je l’ai dit dans mon message vocal de tout à l’heure, il faut boucler cela aujourd’hui. Je suis sur la route avec un mauvais réseau, donc l’e-mail est plus simple.</p><p>Peux-tu acheter quatre cartes-cadeaux de 100 euros chacune pour notre nouveau fournisseur et m’envoyer les codes ici ? Je t’expliquerai à quoi cela sert plus tard — c’est un cadeau de remerciement qui doit partir aujourd’hui.</p><p>Compte sur moi pour la suite. Merci !</p><p>Marc</p></div></div>',
 '[]'::jsonb,
 TRUE,
 '["Une référence à un message vocal d’une voix connue n’est pas une preuve — les voix peuvent être clonées avec l’IA","La demande d’acheter des cartes-cadeaux et d’envoyer les codes est un schéma de fraude classique","L’urgence (aujourd’hui) et une raison de ne pas appeler (mauvais réseau) bloquent justement le second canal","La raison « pourquoi » est sans cesse reportée — une tactique de diversion","Ne vérifiez jamais à partir de l’e-mail lui-même ; utilisez un canal indépendant"]'::jsonb,
 '[]'::jsonb,
 'Il s’agit de phishing. La référence à un message vocal d’une voix connue paraît convaincante, mais une voix peut être clonée avec l’IA — une voix ou un nom connu n’est plus une preuve. Un vrai responsable ne demande pas des codes de cartes-cadeaux par e-mail. Vérifiez par un second canal indépendant : rappelez Marc sur un numéro que vous avez déjà. N’effectuez jamais un achat sur la seule base d’un e-mail ou d’un message vocal.',
 410, 'advanced'),

-- ---------------- fr-BE ----------------
('fr-BE', 'both',
 'Marc Dupont',
 'marc.dupont@kestrel-finance.be',
 'Attention au domaine : kestrel-finance.be. Votre organisation utilise kestrel.be. Un mot ajouté en fait un domaine différent et étranger.',
 'aujourd’hui 08:42',
 'Rapide : validation de la facture du projet Solstice',
 'Bonjour Sanne, content d’avoir échangé hier au sujet de Solstice. Le fournisseur...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Bonjour Sanne,</p><p>Content d’avoir échangé hier au sujet de la livraison du projet Solstice. Notre fournisseur vient de nous informer que son numéro de compte a changé, et la facture en attente ne peut malheureusement pas attendre lundi.</p><p>Pourrais-tu valider le paiement aujourd’hui via {{link:0}} ? Je suis en réunion le reste de la journée, alors évite de m’appeler — un petit message suffit.</p><p>Merci de prendre cela en charge rapidement.</p><p>Bien à toi,<br>Marc Dupont<br>Directeur financier</p></div></div>',
 '[{"label":"Valider le paiement","real_url":"http://kestrel-finance.be/portal/approve?inv=SOL-2026-0418","suspicious":true,"warning":"Ce lien mène vers kestrel-finance.be, pas vers votre propre kestrel.be. Ne validez jamais un paiement depuis un lien d’e-mail — connectez-vous au portail connu ou appelez votre collègue sur un numéro que vous avez déjà."}]'::jsonb,
 TRUE,
 '["Le domaine kestrel-finance.be ressemble à votre organisation mais diffère subtilement de kestrel.be","Demande inhabituelle : valider un paiement en urgence via un lien","L’urgence autour de l’argent (ne peut pas attendre lundi) vous met sous pression","L’expéditeur vous demande explicitement de NE PAS appeler — précisément le second canal qui démasquerait l’arnaque","Un changement de numéro de compte est un signe classique de fraude à la facture"]'::jsonb,
 '[]'::jsonb,
 'Il s’agit de phishing (fraude au président). La langue est impeccable et personnelle — votre nom, un projet crédible, le style d’un collègue. C’est précisément ce qui la rend dangereuse : vous ne pouvez pas la repérer aux fautes d’orthographe. Fiez-vous au processus, pas à la qualité de la rédaction. Vérifiez toute demande urgente d’argent par un second canal indépendant : appelez Marc sur un numéro que vous avez déjà, ou allez le voir. Ne cliquez jamais sur un lien de validation reçu par e-mail.',
 400, 'advanced'),

('fr-BE', 'both',
 'Marc Dupont',
 'm.dupont@kestrel.be',
 'Un nom ou une voix connue n’est pas une preuve. Un message vocal peut être imité avec l’IA (voix deepfake).',
 'aujourd’hui 09:18',
 'Suite à mon message vocal de tout à l’heure',
 'Bonjour Sanne, comme je l’ai dit dans mon message vocal, peux-tu régler cela...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Bonjour Sanne,</p><p>Comme je l’ai dit dans mon message vocal de tout à l’heure, il faut boucler cela aujourd’hui. Je suis sur la route avec un mauvais réseau, donc l’e-mail est plus simple.</p><p>Peux-tu acheter quatre cartes-cadeaux de 100 euros chacune pour notre nouveau fournisseur et m’envoyer les codes ici ? Je t’expliquerai à quoi cela sert plus tard — c’est un cadeau de remerciement qui doit partir aujourd’hui.</p><p>Compte sur moi pour la suite. Merci !</p><p>Marc</p></div></div>',
 '[]'::jsonb,
 TRUE,
 '["Une référence à un message vocal d’une voix connue n’est pas une preuve — les voix peuvent être clonées avec l’IA","La demande d’acheter des cartes-cadeaux et d’envoyer les codes est un schéma de fraude classique","L’urgence (aujourd’hui) et une raison de ne pas appeler (mauvais réseau) bloquent justement le second canal","La raison « pourquoi » est sans cesse reportée — une tactique de diversion","Ne vérifiez jamais à partir de l’e-mail lui-même ; utilisez un canal indépendant"]'::jsonb,
 '[]'::jsonb,
 'Il s’agit de phishing. La référence à un message vocal d’une voix connue paraît convaincante, mais une voix peut être clonée avec l’IA — une voix ou un nom connu n’est plus une preuve. Un vrai responsable ne demande pas des codes de cartes-cadeaux par e-mail. Vérifiez par un second canal indépendant : rappelez Marc sur un numéro que vous avez déjà. N’effectuez jamais un achat sur la seule base d’un e-mail ou d’un message vocal.',
 410, 'advanced'),

-- ---------------- de ----------------
('de', 'both',
 'Mark de Vries',
 'mark.devries@kestrel-finance.de',
 'Achten Sie auf die Domain: kestrel-finance.de. Ihre Organisation nutzt kestrel.de. Ein zusätzliches Wort macht daraus eine andere, fremde Domain.',
 'heute 08:42',
 'Kurz: Freigabe der Rechnung für Projekt Sonnenwende',
 'Hallo Sanne, schön, dass wir uns gestern zu Sonnenwende austauschen konnten...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Hallo Sanne,</p><p>schön, dass wir uns gestern zur Abnahme des Projekts Sonnenwende austauschen konnten. Unser Lieferant hat uns gerade mitgeteilt, dass sich seine Kontonummer geändert hat, und die offene Rechnung kann leider nicht bis Montag warten.</p><p>Könntest du die Zahlung heute noch über {{link:0}} freigeben? Ich bin den Rest des Tages in Besprechungen, ruf mich also bitte nicht an — eine kurze Nachricht genügt.</p><p>Danke, dass du das schnell übernimmst.</p><p>Herzliche Grüße,<br>Mark de Vries<br>Leiter Finanzen</p></div></div>',
 '[{"label":"Zahlung freigeben","real_url":"http://kestrel-finance.de/portal/approve?inv=SW-2026-0418","suspicious":true,"warning":"Dieser Link führt zu kestrel-finance.de, nicht zu Ihrem eigenen kestrel.de. Geben Sie eine Zahlung niemals über einen E-Mail-Link frei — melden Sie sich im bekannten Portal an oder rufen Sie Ihren Kollegen unter einer Nummer an, die Sie bereits haben."}]'::jsonb,
 TRUE,
 '["Die Domain kestrel-finance.de ähnelt Ihrer Organisation, weicht aber subtil von kestrel.de ab","Ungewöhnliche Bitte: eine Zahlung dringend über einen Link freigeben","Druck durch Eile rund ums Geld (kann nicht bis Montag warten)","Der Absender bittet Sie ausdrücklich, NICHT anzurufen — genau der zweite Kanal, der den Trick entlarven würde","Eine geänderte Kontonummer ist ein klassisches Zeichen für Rechnungsbetrug"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing (CEO-Betrug). Die Sprache ist fehlerfrei und persönlich — Ihr Name, ein echt klingendes Projekt, der Stil eines Kollegen. Genau das macht es gefährlich: Sie erkennen es nicht an Rechtschreibfehlern. Vertrauen Sie auf den Prozess, nicht auf die sprachliche Sorgfalt. Prüfen Sie jede dringende Geldforderung über einen zweiten, unabhängigen Kanal: Rufen Sie Mark unter einer Nummer an, die Sie bereits haben, oder gehen Sie vorbei. Klicken Sie nie auf einen Freigabe-Link aus einer E-Mail.',
 400, 'advanced'),

('de', 'both',
 'Mark de Vries',
 'm.devries@kestrel.de',
 'Ein bekannter Name oder eine bekannte Stimme ist kein Beweis. Eine Sprachnachricht kann mit KI nachgeahmt werden (Deepfake-Voice).',
 'heute 09:18',
 'Nachgang zu meiner Sprachnachricht von gerade eben',
 'Hallo Sanne, wie ich gerade in meiner Sprachnachricht sagte, kannst du das heute...',
 E'<div class="eml fam-tech" style="--brand:#2f5597;--cta:#2f5597"><div class="eml-body"><p>Hallo Sanne,</p><p>wie ich gerade in meiner Sprachnachricht sagte, müssen wir das heute noch abschließen. Ich bin unterwegs und habe schlechten Empfang, daher ist E-Mail einfacher.</p><p>Könntest du für unseren neuen Lieferanten vier Gutscheinkarten zu je 100 Euro kaufen und mir die Codes hier zurückschicken? Wofür es ist, erkläre ich dir gleich — es ist ein Dankeschön, das heute noch raus muss.</p><p>Verlass dich auf mich für den Rest. Danke!</p><p>Mark</p></div></div>',
 '[]'::jsonb,
 TRUE,
 '["Ein Verweis auf eine Sprachnachricht einer bekannten Stimme ist kein Beweis — Stimmen lassen sich mit KI klonen","Die Bitte, Gutscheinkarten zu kaufen und die Codes zu schicken, ist ein klassisches Betrugsmuster","Eile (heute noch) und ein Grund, nicht anzurufen (schlechter Empfang), blockieren genau den zweiten Kanal","Der Grund „wofür“ wird immer wieder verschoben — ein Ablenkungsmanöver","Prüfen Sie nie anhand der E-Mail selbst; nutzen Sie einen unabhängigen Kanal"]'::jsonb,
 '[]'::jsonb,
 'Dies ist Phishing. Der Verweis auf eine Sprachnachricht einer bekannten Stimme wirkt überzeugend, aber eine Stimme lässt sich mit KI klonen — eine bekannte Stimme oder ein bekannter Name ist kein Beweis mehr. Eine echte Führungskraft bittet nicht per E-Mail um Gutschein-Codes. Prüfen Sie über einen zweiten, unabhängigen Kanal: Rufen Sie Mark unter einer Nummer zurück, die Sie bereits haben. Tätigen Sie nie einen Kauf allein aufgrund einer E-Mail oder Sprachnachricht.',
 410, 'advanced');


