-- ===========================================================================
-- Fase 8 — Jongeren-scenario's (doelgroepvariant: jeugd).
-- Realistische, regiogerichte oplichting die jongeren raakt: gestolen
-- game-accounts en nep "gratis V-Bucks/Robux", "je Instagram/TikTok wordt
-- verwijderd", nep-winacties ("je hebt een iPhone gewonnen") en doorverkoop
-- van concert-/festivaltickets. Plus per taal één ECHTE (te vertrouwen)
-- 2FA-code, zodat het niet allemaal phishing is.
--
-- audience = 'personal' (privé-pool), difficulty 'normal', mix van kanalen
-- (email/sms/whatsapp). Categorie expliciet meegegeven (gaming/social =
-- 'account' want het is account-overname; ticketdoorverkoop = 'marktplaats';
-- winactie = 'overig'). Deze INSERT staat NA de Fase-6 categorie-UPDATEs,
-- zodat de hier gezette categorieën niet worden overschreven.
-- sort_order vanaf 500 zodat het niet botst met eerdere scenario's.
-- ===========================================================================

INSERT INTO inbox_messages
  (locale, channel, audience, difficulty, category, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- ---------- NL ----------
('nl','email','personal','normal','account',
 'Fortnite Rewards','rewards@free-vbucks-claim.com',
 'Epic Games gebruikt @epicgames.com. "free-vbucks-claim.com" is nep — gratis V-Bucks via een externe site bestaan niet.',
 'vandaag 16:40','🎁 Je 13.500 GRATIS V-Bucks staan klaar!',
 'Gefeliciteerd! Je account is geselecteerd voor 13.500 gratis V-Bucks. Claim ze nu...',
 E'<div class="eml fam-tech" style="--brand:#7b2ff7;--cta:#7b2ff7"><div class="eml-body"><p>Gefeliciteerd!</p><p>Jouw account is geselecteerd voor <strong>13.500 GRATIS V-Bucks</strong>. Log in om ze te claimen voordat de actie vervalt:</p><p>{{link:0}}</p><p>Let op: deze actie verloopt over 30 minuten. Mis het niet!</p><p>— Het Fortnite Rewards-team</p></div></div>',
 '[{"label":"Claim mijn V-Bucks","real_url":"http://free-vbucks-claim.com/login","suspicious":true,"warning":"Het echte domein is epicgames.com. Een externe site die naar je login vraagt om \"gratis V-Bucks\" te geven, steelt je Fortnite-account."}]'::jsonb,
 TRUE,
 '["Gratis in-game valuta bestaat niet — het is altijd lokaas","Afzenderdomein free-vbucks-claim.com is niet epicgames.com","Tijdsdruk: \"verloopt over 30 minuten\"","De link vraagt je om in te loggen op een vreemde site"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing om je game-account te stelen. Niemand geeft gratis V-Bucks weg via een link. Wie inlogt op zo''n nepsite, geeft zijn Epic Games-account weg. Koop V-Bucks alleen in de game zelf en zet tweestapsverificatie aan.',
 500),

('nl','sms','personal','normal','account',
 'Instagram','+31 6 48 22 19 03',
 'Instagram stuurt geen sms vanaf een 06-nummer en dreigt niet met verwijdering via een link.',
 'vandaag 19:12','Instagram',
 'Je account wordt binnen 24 uur verwijderd wegens een copyrightmelding...',
 E'Instagram: we hebben een copyrightklacht over jouw account ontvangen. Je account wordt binnen 24 uur VERWIJDERD tenzij je bezwaar maakt: {{link:0}}',
 '[{"label":"instagram-help-center.com","real_url":"http://instagram-help-center.com/appeal","suspicious":true,"warning":"Instagram gebruikt instagram.com en de app zelf. \"instagram-help-center.com\" is nep en wil je wachtwoord stelen."}]'::jsonb,
 TRUE,
 '["Dreigen met verwijdering binnen 24 uur = paniek zaaien","Afzender is een 06-nummer, geen officieel kanaal","Link gaat naar instagram-help-center.com, niet instagram.com","Echte meldingen staan in de app, niet in een sms"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. Oplichters dreigen met verwijdering om je in paniek te laten klikken. Controleer meldingen altijd in de Instagram-app zelf (Instellingen). Klik nooit op een link uit zo''n bericht.',
 501),

('nl','whatsapp','personal','normal','overig',
 'Onbekend nummer','+31 6 12 90 34 77',
 'Een "win-actie" die je nooit hebt meegedaan, is altijd nep. Bekende merken loten geen winnaars uit via WhatsApp.',
 'vandaag 13:05','WhatsApp',
 'GEFELICITEERD! Jouw nummer is getrokken: je hebt een iPhone 16 Pro gewonnen...',
 E'🎉 GEFELICITEERD! 🎉 Jouw telefoonnummer is getrokken in onze actie. Je hebt een *iPhone 16 Pro* gewonnen! Betaal alleen € 1,95 verzendkosten en vul je gegevens in: {{link:0}}',
 '[{"label":"apple-winactie-nl.com","real_url":"http://apple-winactie-nl.com/claim","suspicious":true,"warning":"Apple verloot geen telefoons via WhatsApp. De site vraagt om betaalgegevens — die worden misbruikt."}]'::jsonb,
 TRUE,
 '["Je hebt nooit aan een win-actie meegedaan","Klein bedrag (€ 1,95) om je kaartgegevens te ontfutselen","Onbekend nummer via WhatsApp","Link naar apple-winactie-nl.com, niet apple.com"]'::jsonb,
 '[]'::jsonb,
 'Dit is een prijs-scam. Als je niets hebt gewonnen omdat je nergens aan meedeed, klopt het niet. Het kleine bedrag is een truc om je kaartgegevens te krijgen. Negeren en blokkeren.',
 502),

('nl','sms','personal','normal','account',
 'Steam','Steam',
 'Dit is een ECHTE Steam Guard-code. Steam stuurt zo''n code alleen als JIJ zelf probeert in te loggen, en zet er nooit een link bij.',
 'vandaag 20:31','Steam',
 'Je Steam Guard-code is 5KQ7T. Deel deze code met niemand.',
 E'Steam Guard: je inlogcode is <strong>5KQ7T</strong>.\n\nDeze code is bedoeld om in te loggen op je eigen account. Deel hem met niemand — Steam-medewerkers vragen er nooit naar.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Geen link in het bericht — alleen een code","Je probeerde zelf zojuist in te loggen","De afzender is Steam, geen vreemd nummer","Het bericht vraagt niets, maar waarschuwt juist om de code geheim te houden"]'::jsonb,
 'Dit is een echte tweestapsverificatie-code (Steam Guard). Die krijg je als je zelf inlogt. Belangrijk: deel zo''n code NOOIT met iemand anders — wie je code vraagt (in een chat, telefoongesprek of "support") wil je account stelen. Typ hem alleen zelf in het officiële inlogscherm.',
 503),

-- ---------- nl-BE ----------
('nl-BE','email','personal','normal','account',
 'Roblox Prijzen','support@robux-gratis-claim.com',
 'Roblox gebruikt @roblox.com. "robux-gratis-claim.com" is nep — gratis Robux via een externe site bestaan niet.',
 'vandaag 16:40','🎁 Je 10.000 GRATIS Robux staan klaar!',
 'Proficiat! Je account is geselecteerd voor 10.000 gratis Robux. Claim ze nu...',
 E'<div class="eml fam-tech" style="--brand:#e2231a;--cta:#e2231a"><div class="eml-body"><p>Proficiat!</p><p>Jouw account werd geselecteerd voor <strong>10.000 GRATIS Robux</strong>. Meld je aan om ze te claimen voor de actie afloopt:</p><p>{{link:0}}</p><p>Opgelet: deze actie verloopt over 30 minuten!</p><p>— Het Roblox-prijzenteam</p></div></div>',
 '[{"label":"Claim mijn Robux","real_url":"http://robux-gratis-claim.com/login","suspicious":true,"warning":"Het echte domein is roblox.com. Een externe site die naar je login vraagt om \"gratis Robux\" te geven, steelt je Roblox-account."}]'::jsonb,
 TRUE,
 '["Gratis in-game valuta bestaat niet — het is altijd lokaas","Afzenderdomein robux-gratis-claim.com is niet roblox.com","Tijdsdruk: \"verloopt over 30 minuten\"","De link vraagt je om aan te melden op een vreemde site"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing om je game-account te stelen. Niemand geeft gratis Robux weg via een link. Wie aanmeldt op zo''n nepsite, geeft zijn Roblox-account weg. Koop Robux alleen in de app zelf en zet tweestapsverificatie aan.',
 500),

('nl-BE','sms','personal','normal','account',
 'TikTok','+32 470 88 21 09',
 'TikTok stuurt geen sms vanaf een gsm-nummer en dreigt niet met verwijdering via een link.',
 'vandaag 19:12','TikTok',
 'Je account wordt binnen 24 uur verwijderd wegens schending van de regels...',
 E'TikTok: we ontvingen een klacht over jouw account. Het wordt binnen 24 uur VERWIJDERD tenzij je bezwaar aantekent: {{link:0}}',
 '[{"label":"tiktok-beroep.com","real_url":"http://tiktok-beroep.com/appeal","suspicious":true,"warning":"TikTok gebruikt tiktok.com en de app zelf. \"tiktok-beroep.com\" is nep en wil je wachtwoord stelen."}]'::jsonb,
 TRUE,
 '["Dreigen met verwijdering binnen 24 uur = paniek zaaien","Afzender is een gsm-nummer, geen officieel kanaal","Link gaat naar tiktok-beroep.com, niet tiktok.com","Echte meldingen staan in de app, niet in een sms"]'::jsonb,
 '[]'::jsonb,
 'Dit is phishing. Oplichters dreigen met verwijdering om je in paniek te laten klikken. Controleer meldingen altijd in de TikTok-app zelf. Klik nooit op een link uit zo''n bericht.',
 501),

('nl-BE','whatsapp','personal','normal','marktplaats',
 'Onbekend nummer','+32 489 33 70 12',
 'Een ticketverkoper die alleen vooraf wil betaald worden en buiten het officiële kanaal blijft, is bijna altijd een oplichter.',
 'vandaag 13:05','WhatsApp',
 'Nog 2 tickets voor Tomorrowland! Betaal via overschrijving en ik stuur ze door...',
 E'Hey! Ik heb nog 2 tickets voor *Tomorrowland* die ik niet meer kan gebruiken. 150 euro per stuk. Betaal via overschrijving, dan stuur ik de pdf-tickets meteen door. Eerst betalen want er is veel interesse! 👍',
 '[]'::jsonb,
 TRUE,
 '["Vooraf betalen via overschrijving = geen enkele bescherming","Druk: \"eerst betalen want veel interesse\"","Onbekend nummer buiten het officiële verkoopkanaal","Pdf-tickets kunnen meermaals worden doorverkocht"]'::jsonb,
 '[]'::jsonb,
 'Dit is ticketfraude. Wie vooraf via overschrijving laat betalen en buiten een officieel platform blijft, verdwijnt vaak met je geld. Koop tickets enkel via de officiële verkoper of een platform met doorverkoopgarantie (bv. Ticketswap).',
 502),

('nl-BE','sms','personal','normal','account',
 'itsme','itsme',
 'Dit is een ECHTE itsme-melding. itsme vraagt je om de actie in de app zelf te bevestigen en zet nooit een link in de sms.',
 'vandaag 20:31','itsme',
 'Bevestig je aanmelding in de itsme-app. Heb jij dit niet gestart? Weiger dan.',
 E'itsme: er is een aanmelding gestart. Open de <strong>itsme-app</strong> om te bevestigen.\n\nHeb jij dit zelf niet gestart? Weiger de aanvraag in de app en wijzig je code.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Geen link in het bericht — je bevestigt in de app zelf","Je startte zelf zojuist een aanmelding","De sms vraagt geen wachtwoord of code","Het bericht zegt expliciet: weiger als jij het niet was"]'::jsonb,
 'Dit is een echte tweestapsmelding van itsme. Je bevestigt zo''n actie altijd in de itsme-app zelf, nooit via een link. Was jij het niet? Dan weiger je de aanvraag — iemand probeert dan met jouw gegevens in te loggen.',
 503),

-- ---------- EN (UK) ----------
('en','email','personal','normal','account',
 'Fortnite Rewards','rewards@free-vbucks-claim.com',
 'Epic Games uses @epicgames.com. "free-vbucks-claim.com" is fake — free V-Bucks from an outside site do not exist.',
 'today 16:40','🎁 Your 13,500 FREE V-Bucks are waiting!',
 'Congratulations! Your account has been selected for 13,500 free V-Bucks. Claim them now...',
 E'<div class="eml fam-tech" style="--brand:#7b2ff7;--cta:#7b2ff7"><div class="eml-body"><p>Congratulations!</p><p>Your account has been selected for <strong>13,500 FREE V-Bucks</strong>. Sign in to claim them before the offer expires:</p><p>{{link:0}}</p><p>Hurry — this offer expires in 30 minutes!</p><p>— The Fortnite Rewards team</p></div></div>',
 '[{"label":"Claim my V-Bucks","real_url":"http://free-vbucks-claim.com/login","suspicious":true,"warning":"The real domain is epicgames.com. A site that asks you to sign in to give you \"free V-Bucks\" steals your Fortnite account."}]'::jsonb,
 TRUE,
 '["Free in-game currency does not exist — it is always bait","Sender domain free-vbucks-claim.com is not epicgames.com","Time pressure: \"expires in 30 minutes\"","The link asks you to sign in on a strange site"]'::jsonb,
 '[]'::jsonb,
 'This is phishing to steal your game account. Nobody gives away free V-Bucks via a link. Signing in on that fake site hands over your Epic Games account. Buy V-Bucks only inside the game and turn on two-factor authentication.',
 500),

('en','sms','personal','normal','account',
 'Instagram','+44 7700 900482',
 'Instagram does not text from a mobile number and does not threaten deletion via a link.',
 'today 19:12','Instagram',
 'Your account will be deleted within 24 hours due to a copyright report...',
 E'Instagram: we received a copyright complaint about your account. It will be DELETED within 24 hours unless you appeal: {{link:0}}',
 '[{"label":"instagram-help-center.com","real_url":"http://instagram-help-center.com/appeal","suspicious":true,"warning":"Instagram uses instagram.com and the app itself. \"instagram-help-center.com\" is fake and wants to steal your password."}]'::jsonb,
 TRUE,
 '["Threatening deletion within 24 hours is panic-mongering","Sender is a mobile number, not an official channel","Link goes to instagram-help-center.com, not instagram.com","Real notices appear in the app, not in a text"]'::jsonb,
 '[]'::jsonb,
 'This is phishing. Scammers threaten deletion to make you click in a panic. Always check notices inside the Instagram app (Settings). Never tap a link from a message like this.',
 501),

('en','whatsapp','personal','normal','overig',
 'Unknown number','+44 7700 900913',
 'A "prize draw" you never entered is always fake. Real brands do not pick winners over WhatsApp.',
 'today 13:05','WhatsApp',
 'CONGRATULATIONS! Your number was drawn — you have won an iPhone 16 Pro...',
 E'🎉 CONGRATULATIONS! 🎉 Your phone number was drawn in our giveaway. You have won an *iPhone 16 Pro*! Just pay £1.95 for postage and enter your details: {{link:0}}',
 '[{"label":"apple-giveaway-uk.com","real_url":"http://apple-giveaway-uk.com/claim","suspicious":true,"warning":"Apple does not give away phones over WhatsApp. The site asks for payment details, which are then misused."}]'::jsonb,
 TRUE,
 '["You never entered any prize draw","Small fee (£1.95) to harvest your card details","Unknown number over WhatsApp","Link to apple-giveaway-uk.com, not apple.com"]'::jsonb,
 '[]'::jsonb,
 'This is a prize scam. If you won something you never entered, it is fake. The tiny fee is a trick to capture your card details. Ignore and block.',
 502),

('en','sms','personal','normal','account',
 'Steam','Steam',
 'This is a GENUINE Steam Guard code. Steam only sends it when YOU try to log in, and never adds a link.',
 'today 20:31','Steam',
 'Your Steam Guard code is 5KQ7T. Do not share this code with anyone.',
 E'Steam Guard: your sign-in code is <strong>5KQ7T</strong>.\n\nThis code is for signing in to your own account. Do not share it with anyone — Steam staff will never ask for it.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["No link in the message — just a code","You tried to sign in yourself just now","The sender is Steam, not a strange number","The message asks for nothing; it warns you to keep the code secret"]'::jsonb,
 'This is a genuine two-factor code (Steam Guard). You receive it when you sign in yourself. Important: NEVER share such a code with anyone — whoever asks for your code (in a chat, a call or "support") wants to steal your account. Only type it into the official sign-in screen.',
 503),

-- ---------- FR ----------
('fr','email','personal','normal','account',
 'Fortnite Récompenses','rewards@free-vbucks-claim.com',
 'Epic Games utilise @epicgames.com. « free-vbucks-claim.com » est faux — des V-Bucks gratuits via un site externe, ça n''existe pas.',
 'aujourd''hui 16:40','🎁 Vos 13 500 V-Bucks GRATUITS vous attendent !',
 'Félicitations ! Votre compte a été sélectionné pour 13 500 V-Bucks gratuits. Réclamez-les...',
 E'<div class="eml fam-tech" style="--brand:#7b2ff7;--cta:#7b2ff7"><div class="eml-body"><p>Félicitations !</p><p>Votre compte a été sélectionné pour <strong>13 500 V-Bucks GRATUITS</strong>. Connectez-vous pour les réclamer avant la fin de l’offre :</p><p>{{link:0}}</p><p>Dépêchez-vous — l’offre expire dans 30 minutes !</p><p>— L’équipe Fortnite Récompenses</p></div></div>',
 '[{"label":"Réclamer mes V-Bucks","real_url":"http://free-vbucks-claim.com/login","suspicious":true,"warning":"Le vrai domaine est epicgames.com. Un site qui vous demande de vous connecter pour offrir des « V-Bucks gratuits » vole votre compte Fortnite."}]'::jsonb,
 TRUE,
 '["La monnaie de jeu gratuite n’existe pas — c’est toujours un appât","Le domaine free-vbucks-claim.com n’est pas epicgames.com","Pression du temps : « expire dans 30 minutes »","Le lien vous demande de vous connecter sur un site inconnu"]'::jsonb,
 '[]'::jsonb,
 'C’est de l’hameçonnage pour voler votre compte de jeu. Personne n’offre de V-Bucks gratuits par un lien. Se connecter sur ce faux site revient à donner son compte Epic Games. Achetez des V-Bucks uniquement dans le jeu et activez la double authentification.',
 500),

('fr','sms','personal','normal','account',
 'Instagram','+33 6 12 48 75 03',
 'Instagram n’envoie pas de SMS depuis un numéro de portable et ne menace pas de suppression via un lien.',
 'aujourd''hui 19:12','Instagram',
 'Votre compte sera supprimé dans 24 heures à la suite d''un signalement...',
 E'Instagram : nous avons reçu une plainte pour droits d’auteur concernant votre compte. Il sera SUPPRIMÉ sous 24 heures sauf si vous contestez : {{link:0}}',
 '[{"label":"instagram-help-center.com","real_url":"http://instagram-help-center.com/appeal","suspicious":true,"warning":"Instagram utilise instagram.com et l’application. « instagram-help-center.com » est faux et veut voler votre mot de passe."}]'::jsonb,
 TRUE,
 '["Menacer d’une suppression sous 24 h, c’est semer la panique","L’expéditeur est un numéro de portable, pas un canal officiel","Le lien mène à instagram-help-center.com, pas instagram.com","Les vrais avis apparaissent dans l’app, pas dans un SMS"]'::jsonb,
 '[]'::jsonb,
 'C’est de l’hameçonnage. Les escrocs menacent de suppression pour vous faire cliquer dans la panique. Vérifiez toujours les avis dans l’application Instagram (Réglages). Ne cliquez jamais sur un lien d’un tel message.',
 501),

('fr','whatsapp','personal','normal','overig',
 'Numéro inconnu','+33 6 99 30 41 77',
 'Un « tirage au sort » auquel vous n’avez jamais participé est toujours faux. Les vraies marques ne désignent pas de gagnants par WhatsApp.',
 'aujourd''hui 13:05','WhatsApp',
 'FÉLICITATIONS ! Votre numéro a été tiré au sort : vous avez gagné un iPhone 16 Pro...',
 E'🎉 FÉLICITATIONS ! 🎉 Votre numéro a été tiré au sort dans notre jeu-concours. Vous avez gagné un *iPhone 16 Pro* ! Payez seulement 1,95 € de frais de port et indiquez vos coordonnées : {{link:0}}',
 '[{"label":"apple-jeu-concours-fr.com","real_url":"http://apple-jeu-concours-fr.com/claim","suspicious":true,"warning":"Apple n’organise pas de tirage par WhatsApp. Le site demande vos données de paiement, qui sont ensuite détournées."}]'::jsonb,
 TRUE,
 '["Vous n’avez jamais participé à un concours","Petit montant (1,95 €) pour récupérer vos données bancaires","Numéro inconnu via WhatsApp","Lien vers apple-jeu-concours-fr.com, pas apple.com"]'::jsonb,
 '[]'::jsonb,
 'C’est une arnaque au prix. Si vous avez « gagné » sans avoir participé, c’est faux. Le petit montant est une ruse pour capter vos données bancaires. Ignorez et bloquez.',
 502),

('fr','sms','personal','normal','account',
 'Steam','Steam',
 'C’est un VRAI code Steam Guard. Steam ne l’envoie que lorsque VOUS tentez de vous connecter, et n’ajoute jamais de lien.',
 'aujourd''hui 20:31','Steam',
 'Votre code Steam Guard est 5KQ7T. Ne le communiquez à personne.',
 E'Steam Guard : votre code de connexion est <strong>5KQ7T</strong>.\n\nCe code sert à vous connecter à votre propre compte. Ne le communiquez à personne — le personnel de Steam ne le demande jamais.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Aucun lien dans le message — juste un code","Vous venez de tenter de vous connecter vous-même","L’expéditeur est Steam, pas un numéro inconnu","Le message ne demande rien ; il vous invite à garder le code secret"]'::jsonb,
 'C’est un vrai code de double authentification (Steam Guard). Vous le recevez quand vous vous connectez vous-même. Important : ne communiquez JAMAIS un tel code — quiconque vous le demande (dans un chat, par téléphone ou via un « support ») veut voler votre compte. Saisissez-le uniquement dans l’écran de connexion officiel.',
 503),

-- ---------- fr-BE ----------
('fr-BE','email','personal','normal','account',
 'Roblox Récompenses','support@robux-gratuit-claim.com',
 'Roblox utilise @roblox.com. « robux-gratuit-claim.com » est faux — des Robux gratuits via un site externe, ça n''existe pas.',
 'aujourd''hui 16:40','🎁 Vos 10 000 Robux GRATUITS vous attendent !',
 'Félicitations ! Votre compte a été sélectionné pour 10 000 Robux gratuits. Réclamez-les...',
 E'<div class="eml fam-tech" style="--brand:#e2231a;--cta:#e2231a"><div class="eml-body"><p>Félicitations !</p><p>Votre compte a été sélectionné pour <strong>10 000 Robux GRATUITS</strong>. Connectez-vous pour les réclamer avant la fin de l’offre :</p><p>{{link:0}}</p><p>Dépêchez-vous — l’offre expire dans 30 minutes !</p><p>— L’équipe Roblox Récompenses</p></div></div>',
 '[{"label":"Réclamer mes Robux","real_url":"http://robux-gratuit-claim.com/login","suspicious":true,"warning":"Le vrai domaine est roblox.com. Un site qui vous demande de vous connecter pour offrir des « Robux gratuits » vole votre compte Roblox."}]'::jsonb,
 TRUE,
 '["La monnaie de jeu gratuite n’existe pas — c’est toujours un appât","Le domaine robux-gratuit-claim.com n’est pas roblox.com","Pression du temps : « expire dans 30 minutes »","Le lien vous demande de vous connecter sur un site inconnu"]'::jsonb,
 '[]'::jsonb,
 'C’est de l’hameçonnage pour voler votre compte de jeu. Personne n’offre de Robux gratuits par un lien. Se connecter sur ce faux site revient à donner son compte Roblox. Achetez des Robux uniquement dans l’application et activez la double authentification.',
 500),

('fr-BE','sms','personal','normal','account',
 'TikTok','+32 470 12 88 41',
 'TikTok n’envoie pas de SMS depuis un numéro de GSM et ne menace pas de suppression via un lien.',
 'aujourd''hui 19:12','TikTok',
 'Votre compte sera supprimé dans 24 heures pour non-respect des règles...',
 E'TikTok : nous avons reçu une plainte concernant votre compte. Il sera SUPPRIMÉ sous 24 heures sauf si vous introduisez un recours : {{link:0}}',
 '[{"label":"tiktok-recours.com","real_url":"http://tiktok-recours.com/appeal","suspicious":true,"warning":"TikTok utilise tiktok.com et l’application. « tiktok-recours.com » est faux et veut voler votre mot de passe."}]'::jsonb,
 TRUE,
 '["Menacer d’une suppression sous 24 h, c’est semer la panique","L’expéditeur est un numéro de GSM, pas un canal officiel","Le lien mène à tiktok-recours.com, pas tiktok.com","Les vrais avis apparaissent dans l’app, pas dans un SMS"]'::jsonb,
 '[]'::jsonb,
 'C’est de l’hameçonnage. Les escrocs menacent de suppression pour vous faire cliquer dans la panique. Vérifiez toujours les avis dans l’application TikTok. Ne cliquez jamais sur un lien d’un tel message.',
 501),

('fr-BE','whatsapp','personal','normal','marktplaats',
 'Numéro inconnu','+32 489 70 33 12',
 'Un vendeur de tickets qui exige un paiement à l’avance et reste hors du canal officiel est presque toujours un escroc.',
 'aujourd''hui 13:05','WhatsApp',
 'Encore 2 tickets pour les Ardentes ! Paiement par virement et je les envoie...',
 E'Salut ! J’ai encore 2 tickets pour *Les Ardentes* que je ne peux plus utiliser. 120 € pièce. Paie par virement et je t’envoie les PDF tout de suite. Paie d’abord car il y a beaucoup de demandes ! 👍',
 '[]'::jsonb,
 TRUE,
 '["Payer à l’avance par virement = aucune protection","Pression : « paie d’abord car beaucoup de demandes »","Numéro inconnu hors du canal de vente officiel","Des tickets PDF peuvent être revendus plusieurs fois"]'::jsonb,
 '[]'::jsonb,
 'C’est une arnaque aux tickets. Celui qui exige un paiement à l’avance par virement et reste hors d’une plateforme officielle disparaît souvent avec votre argent. Achetez vos tickets uniquement via le vendeur officiel ou une plateforme avec garantie de revente (par ex. Ticketswap).',
 502),

('fr-BE','sms','personal','normal','account',
 'itsme','itsme',
 'Ceci est une VRAIE notification itsme. itsme vous demande de confirmer dans l’app elle-même et n’ajoute jamais de lien dans le SMS.',
 'aujourd''hui 20:31','itsme',
 'Confirmez votre connexion dans l’app itsme. Ce n’est pas vous ? Refusez.',
 E'itsme : une connexion a été lancée. Ouvrez l’<strong>application itsme</strong> pour confirmer.\n\nCe n’est pas vous ? Refusez la demande dans l’app et modifiez votre code.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Aucun lien dans le message — vous confirmez dans l’app","Vous venez de lancer une connexion vous-même","Le SMS ne demande ni mot de passe ni code","Le message dit explicitement : refusez si ce n’est pas vous"]'::jsonb,
 'Ceci est une vraie notification de double authentification d’itsme. Vous confirmez toujours ce type d’action dans l’app itsme, jamais via un lien. Ce n’était pas vous ? Refusez la demande — quelqu’un tente alors de se connecter avec vos données.',
 503),

-- ---------- DE ----------
('de','email','personal','normal','account',
 'Fortnite Belohnungen','rewards@free-vbucks-claim.com',
 'Epic Games nutzt @epicgames.com. „free-vbucks-claim.com“ ist gefälscht — kostenlose V-Bucks über eine externe Seite gibt es nicht.',
 'heute 16:40','🎁 Deine 13.500 GRATIS V-Bucks warten!',
 'Glückwunsch! Dein Konto wurde für 13.500 kostenlose V-Bucks ausgewählt. Hol sie dir...',
 E'<div class="eml fam-tech" style="--brand:#7b2ff7;--cta:#7b2ff7"><div class="eml-body"><p>Glückwunsch!</p><p>Dein Konto wurde für <strong>13.500 GRATIS V-Bucks</strong> ausgewählt. Melde dich an, um sie vor Ablauf des Angebots einzulösen:</p><p>{{link:0}}</p><p>Beeil dich — das Angebot läuft in 30 Minuten ab!</p><p>— Das Fortnite-Belohnungsteam</p></div></div>',
 '[{"label":"Meine V-Bucks einlösen","real_url":"http://free-vbucks-claim.com/login","suspicious":true,"warning":"Die echte Domain ist epicgames.com. Eine Seite, die dich zum Anmelden auffordert, um „kostenlose V-Bucks“ zu geben, stiehlt dein Fortnite-Konto."}]'::jsonb,
 TRUE,
 '["Kostenlose Spielwährung gibt es nicht — es ist immer ein Köder","Absenderdomain free-vbucks-claim.com ist nicht epicgames.com","Zeitdruck: „läuft in 30 Minuten ab“","Der Link verlangt eine Anmeldung auf einer fremden Seite"]'::jsonb,
 '[]'::jsonb,
 'Das ist Phishing, um dein Spielkonto zu stehlen. Niemand verschenkt V-Bucks über einen Link. Wer sich auf dieser gefälschten Seite anmeldet, gibt sein Epic-Games-Konto her. Kaufe V-Bucks nur im Spiel selbst und aktiviere die Zwei-Faktor-Authentifizierung.',
 500),

('de','sms','personal','normal','account',
 'Instagram','+49 151 23456789',
 'Instagram schickt keine SMS von einer Handynummer und droht nicht per Link mit Löschung.',
 'heute 19:12','Instagram',
 'Dein Konto wird innerhalb von 24 Stunden gelöscht wegen einer Beschwerde...',
 E'Instagram: Wir haben eine Urheberrechtsbeschwerde zu deinem Konto erhalten. Es wird innerhalb von 24 Stunden GELÖSCHT, sofern du keinen Einspruch einlegst: {{link:0}}',
 '[{"label":"instagram-help-center.com","real_url":"http://instagram-help-center.com/appeal","suspicious":true,"warning":"Instagram nutzt instagram.com und die App selbst. „instagram-help-center.com“ ist gefälscht und will dein Passwort stehlen."}]'::jsonb,
 TRUE,
 '["Drohung mit Löschung in 24 Stunden ist Panikmache","Absender ist eine Handynummer, kein offizieller Kanal","Link führt zu instagram-help-center.com, nicht instagram.com","Echte Hinweise erscheinen in der App, nicht in einer SMS"]'::jsonb,
 '[]'::jsonb,
 'Das ist Phishing. Betrüger drohen mit Löschung, damit du in Panik klickst. Prüfe Hinweise immer in der Instagram-App selbst (Einstellungen). Tippe nie auf einen Link aus so einer Nachricht.',
 501),

('de','whatsapp','personal','normal','overig',
 'Unbekannte Nummer','+49 160 98765432',
 'Eine „Verlosung“, an der du nie teilgenommen hast, ist immer gefälscht. Echte Marken küren keine Gewinner über WhatsApp.',
 'heute 13:05','WhatsApp',
 'GLÜCKWUNSCH! Deine Nummer wurde gezogen — du hast ein iPhone 16 Pro gewonnen...',
 E'🎉 GLÜCKWUNSCH! 🎉 Deine Telefonnummer wurde bei unserer Verlosung gezogen. Du hast ein *iPhone 16 Pro* gewonnen! Zahl nur 1,95 € Versand und gib deine Daten ein: {{link:0}}',
 '[{"label":"apple-gewinnspiel-de.com","real_url":"http://apple-gewinnspiel-de.com/claim","suspicious":true,"warning":"Apple verlost keine Telefone über WhatsApp. Die Seite verlangt Zahlungsdaten, die dann missbraucht werden."}]'::jsonb,
 TRUE,
 '["Du hast nie an einem Gewinnspiel teilgenommen","Kleiner Betrag (1,95 €), um deine Kartendaten abzugreifen","Unbekannte Nummer über WhatsApp","Link zu apple-gewinnspiel-de.com, nicht apple.com"]'::jsonb,
 '[]'::jsonb,
 'Das ist ein Gewinn-Betrug. Wenn du etwas „gewonnen“ hast, ohne teilgenommen zu haben, stimmt etwas nicht. Der kleine Betrag ist ein Trick, um an deine Kartendaten zu kommen. Ignorieren und blockieren.',
 502),

('de','sms','personal','normal','account',
 'Steam','Steam',
 'Das ist ein ECHTER Steam-Guard-Code. Steam sendet ihn nur, wenn DU dich anmeldest, und fügt nie einen Link hinzu.',
 'heute 20:31','Steam',
 'Dein Steam-Guard-Code lautet 5KQ7T. Teile diesen Code mit niemandem.',
 E'Steam Guard: Dein Anmeldecode lautet <strong>5KQ7T</strong>.\n\nDieser Code dient zur Anmeldung in deinem eigenen Konto. Teile ihn mit niemandem — Steam-Mitarbeiter fragen nie danach.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Kein Link in der Nachricht — nur ein Code","Du hast dich gerade selbst anmelden wollen","Der Absender ist Steam, keine fremde Nummer","Die Nachricht verlangt nichts; sie warnt, den Code geheim zu halten"]'::jsonb,
 'Das ist ein echter Zwei-Faktor-Code (Steam Guard). Du erhältst ihn, wenn du dich selbst anmeldest. Wichtig: Teile so einen Code NIEMALS — wer nach deinem Code fragt (im Chat, am Telefon oder als „Support“), will dein Konto stehlen. Gib ihn nur selbst im offiziellen Anmeldebildschirm ein.',
 503);


