-- ============================================================
-- GEVORDERD SMS/WHATSAPP (advanced difficulty)
-- 7 scenario's × 6 locales = 42 rijen.
-- SMS A–D (sort 362–365), WhatsApp E–G (sort 370–372).
-- ============================================================
INSERT INTO inbox_messages
  (locale, channel, audience, difficulty, sender_name, sender_address, sender_note, received_label, subject, preview, body, links, is_phishing, red_flags, green_flags, explanation, sort_order) VALUES

-- ==================== NL ====================

-- NL / SMS A — Rabobank phishing (sort 362)
('nl','sms','both','advanced',
 'Rabobank','+31 6 19 83 44 72',
 'Een bank stuurt nooit een link om in te loggen via sms — ook niet als het bericht rustig en professioneel klinkt.',
 'vandaag 09:18','Rabobank',
 'Rabobank: wij zagen een onbekende inlogpoging...',
 E'Rabobank: wij signaleerden een inlogpoging op uw rekening vanuit een onbekend apparaat. Klopt dit niet? Blokkeer uw toegang tijdelijk via {{link:0}}',
 '[{"label":"Toegang blokkeren","real_url":"https://rabo-accountcheck.nl/blokkeer","suspicious":true,"warning":"Link gaat naar rabo-accountcheck.nl, niet rabobank.nl. Dit is een nepsite."}]'::jsonb,
 TRUE,
 '["Link naar rabo-accountcheck.nl in plaats van rabobank.nl","Banken sturen nooit een inloglink via sms","Bericht klinkt rustig en officieel — extra verdacht","Onbekend apparaat-melding is een klassiek smishing-trucje"]'::jsonb,
 '[]'::jsonb,
 'Dit is geavanceerde smishing. De domeinnaam rabo-accountcheck.nl lijkt op Rabobank maar is het niet. De Rabobank stuurt nooit inloglinks via sms. Open altijd zelf de Rabo-app of bel het nummer op uw bankpas.',
 362),

-- NL / SMS B — DHL customs phishing (sort 363)
('nl','sms','both','advanced',
 'DHL','+31 97 01 55 38 21',
 'Echte douanekosten komen per brief van de Douane zelf — nooit via een sms-link van de bezorger.',
 'vandaag 14:33','DHL',
 'DHL: uw zending is aangehouden bij de douane. Vrijgave...',
 E'DHL: uw zending (JD014600007030174950) is aangehouden bij de douane. Vrijgave vereist €2,10 aan douanekosten. Betaal op {{link:0}} — bezorging volgt morgen.',
 '[{"label":"Douanekosten betalen","real_url":"https://dhl-bezorging.com/douane/vrijgave","suspicious":true,"warning":"Link naar dhl-bezorging.com, niet dhl.nl of dhl.com. Dit is een nepsite die uw betaalgegevens steelt."}]'::jsonb,
 TRUE,
 '["Link naar dhl-bezorging.com in plaats van dhl.nl","Echte douanekosten komen per brief, nooit via sms","Klein bedrag (€2,10) laat u snel betalen zonder na te denken","Specifiek trackingnummer wekt onterecht vertrouwen"]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. Echte douanekosten worden gemeld via een brief van de Douane zelf — niet via een sms-link van de bezorger. Controleer zendingen altijd via dhl.nl of de DHL-app.',
 363),

-- NL / SMS C — KPN phishing (sort 364)
('nl','sms','both','advanced',
 'KPN','+31 97 01 02 19 74',
 'KPN stuurt factuurmeldingen via e-mail of Mijn KPN — nooit als betaallink in een sms.',
 'vandaag 10:05','KPN',
 'KPN: uw factuur van € 49,95 staat klaar. Betaal vóór...',
 E'KPN: uw factuur van €49,95 (mei) staat klaar. Betaal vóór 30 mei via {{link:0}} om afsluiting van uw abonnement te voorkomen.',
 '[{"label":"Factuur betalen","real_url":"https://kpn-betalen.com/factuur/mei","suspicious":true,"warning":"Link naar kpn-betalen.com, niet mijn.kpn.com. Dit is een nepsite."}]'::jsonb,
 TRUE,
 '["Link naar kpn-betalen.com in plaats van mijn.kpn.com","KPN verstuurt facturen via e-mail, niet als sms-betaallink","Dreigt met afsluiting om druk te zetten","Geloofwaardig bedrag (€49,95) maakt het moeilijker te herkennen"]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. KPN verstuurt factuurmeldingen via e-mail of de Mijn KPN-app — nooit als betaallink in een sms. Log altijd zelf in via mijn.kpn.com als u uw factuur wil bekijken.',
 364),

-- NL / SMS D — Albert Heijn legitimate (sort 365)
('nl','sms','both','advanced',
 'Albert Heijn','Albert Heijn',
 'Albert Heijn stuurt bonusbevestigingen via sms als u daarvoor toestemming heeft gegeven. Geen link, geen betaling.',
 'vandaag 08:03','Albert Heijn',
 'AH: uw bonus-actualisatie is verwerkt. Uw nieuwe saldo...',
 E'AH: uw Bonuskaart is bijgewerkt. Uw huidige statuszegel-saldo: 28 zegels. Bekijk uw bonus-aanbiedingen in de AH-app of op ah.nl.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Geen link in het bericht — doorverwijzing naar de officiële app of website","Geen verzoek om te betalen of in te loggen","Alleen informatie over uw eigen saldo","Past bij informatie die u bij aanmelding heeft opgegeven"]'::jsonb,
 'Dit is een echt sms-bericht van Albert Heijn. Let op het verschil: géén link, géén betaling gevraagd — alleen een statusupdate. Twijfelt u? Open de AH-app zelf in plaats van te reageren op het sms-bericht.',
 365),

-- NL / WhatsApp E — "is dit jij?" phishing (sort 370)
('nl','whatsapp','both','advanced',
 'Onbekend nummer','+31 6 77 03 94 21',
 'Een "is dit jij?"-link van een onbekend nummer leidt altijd naar account-overname via QR-code of verificatiecode.',
 'vandaag 21:09','Onbekend nummer',
 'Haha, is dit jij?? 😂😂 Moet je écht even kijken...',
 E'Haha, is dit jij?? 😂😂 Moet je écht even kijken:\n\n{{link:0}}\n\nIk schrok me wild toen ik het zag lol',
 '[{"label":"Filmpje bekijken","real_url":"https://wa-video-check.com/kijk?id=NL-447","suspicious":true,"warning":"Link naar wa-video-check.com, geen officieel WhatsApp-domein. Klikken kan leiden tot account-overname."}]'::jsonb,
 TRUE,
 '["Onbekend nummer — geen bekende contactnaam","\"Is dit jij?\" is een bekende phishingzin op WhatsApp","Link naar wa-video-check.com, niet whatsapp.com","Klikken leidt vaak naar QR-scan of verificatiecode waarmee uw account wordt overgenomen"]'::jsonb,
 '[]'::jsonb,
 'Dit is een klassieke WhatsApp-phishinglink. Wie erop klikt, wordt gevraagd een QR-code te scannen of een verificatiecode in te voeren. Daarna nemen oplichters uw account over en sturen hetzelfde bericht naar al uw contacten.',
 370),

-- NL / WhatsApp F — fake Tikkie (sort 371)
('nl','whatsapp','both','advanced',
 'Onbekend nummer','+31 6 58 14 77 03',
 'Tikkie-links kunnen nep zijn. Het echte domein is tikkie.me. Een toegestuurde link is nooit nodig om geld te ontvangen.',
 'vandaag 15:22','Onbekend nummer',
 'Hé! Ik moet nog een bedragje naar je sturen van vorige week...',
 E'Hé! Ik moet nog een bedragje naar je sturen van vorige week, maar mijn app doet raar. Kun jij even bevestigen via {{link:0}}? Dan schrijf ik het direct over. 🙏',
 '[{"label":"Tikkie bevestigen","real_url":"https://tikkie-betaalverzoek.nl/pay?t=5f8a2","suspicious":true,"warning":"Link naar tikkie-betaalverzoek.nl, niet het echte tikkie.me. Dit is een nep-betaallink die uw bankgegevens steelt."}]'::jsonb,
 TRUE,
 '["Link naar tikkie-betaalverzoek.nl in plaats van tikkie.me","Om geld te ONTVANGEN hoeft u nooit ergens op te klikken of in te loggen","Onbekend nummer — geen naam van afzender","Sociale druk (\"van vorige week\") om snel te klikken"]'::jsonb,
 '[]'::jsonb,
 'Dit is Tikkie-fraude. De link gaat naar een nepsite die uw bankgegevens steelt. Een echt Tikkie-verzoek ontvangen werkt via de officiële app — u hoeft nooit op een toegestuurde link te klikken om geld te ontvangen.',
 371),

-- NL / WhatsApp G — DHL real (sort 372)
('nl','whatsapp','both','advanced',
 'DHL Express','DHL Express',
 'DHL gebruikt WhatsApp Business voor bezorgmeldingen. Geen link naar extern domein, geen betaling — alleen statusinformatie.',
 'vandaag 11:48','DHL Express',
 'DHL Express: uw zending 1234567890 is onderweg...',
 E'DHL Express 📦\n\nUw zending 1234567890 is onderweg en wordt vandaag bezorgd.\n\nGeschatte levertijd: 14:00–16:00\nBestemming: Amsterdam\n\nVraag? Beantwoord dit bericht of ga naar dhl.nl',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Geen externe link — doorverwijzing naar het officiële dhl.nl","Geen betaling of inloggegevens gevraagd","Concrete bezorginformatie met trackingnummer en tijdvak","Zakelijke, neutrale toon zonder druk"]'::jsonb,
 'Dit is een echt WhatsApp Business-bericht van DHL. Er wordt niets gevraagd — alleen een statusmelding. Wil u het zeker weten? Zoek het trackingnummer zelf op via dhl.nl of de DHL-app.',
 372),

-- ==================== NL-BE ====================

-- NL-BE / SMS A — ING bank phishing (sort 362)
('nl-BE','sms','both','advanced',
 'ING','+32 4 97 18 33 56',
 'ING stuurt nooit een sms-link om uw rekening te beveiligen. Open altijd de officiële ING-app.',
 'vandaag 09:18','ING',
 'ING: wij detecteerden een inlogpoging op een onbekend...',
 E'ING: wij detecteerden een inlogpoging op een onbekend apparaat. Niet u? Beveilig uw rekening tijdelijk via {{link:0}}',
 '[{"label":"Rekening beveiligen","real_url":"https://ing-card-verify.be/beveilig","suspicious":true,"warning":"Link naar ing-card-verify.be, niet ing.be. Dit is een nepsite."}]'::jsonb,
 TRUE,
 '["Link naar ing-card-verify.be in plaats van ing.be","ING stuurt nooit een inloglink via sms","Melding van onbekend apparaat creëert onterecht paniek","Bericht klinkt professioneel — net als een echte bankmelding"]'::jsonb,
 '[]'::jsonb,
 'Dit is geavanceerde smishing. ing-card-verify.be is geen ING-domein. ING stuurt nooit links via sms om in te loggen. Open altijd de officiële ING-app of bel het nummer op uw bankkaart.',
 362),

-- NL-BE / SMS B — bpost customs phishing (sort 363)
('nl-BE','sms','both','advanced',
 'bpost','+32 4 56 88 12 37',
 'Echte douanekosten komen via een officieel aanslagbiljet — nooit als betaallink in een sms van de bezorger.',
 'vandaag 14:33','bpost',
 'bpost: uw pakket is aangehouden aan de douane...',
 E'bpost: uw pakket (BE201234567890) wordt aangehouden aan de douane. Vrijgave vereist €2,35 invoerrechten. Betaal nu via {{link:0}}',
 '[{"label":"Invoerrechten betalen","real_url":"https://bpost-douane.be/vrijgave","suspicious":true,"warning":"Link naar bpost-douane.be, niet bpost.be. Dit is een nepsite."}]'::jsonb,
 TRUE,
 '["Link naar bpost-douane.be in plaats van bpost.be","Douanekosten komen als officieel aanslagbiljet, niet als sms","Klein bedrag (€2,35) laat u snel betalen","Valse trackingnummer wekt vertrouwen"]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. Echte invoerrechten worden opgelegd via een officieel aanslagbiljet — nooit via een sms-link. Controleer pakketten altijd via bpost.be of de bpost-app.',
 363),

-- NL-BE / SMS C — Proximus phishing (sort 364)
('nl-BE','sms','both','advanced',
 'Proximus','+32 4 99 07 44 81',
 'Proximus stuurt facturen via e-mail of Mijn Proximus — nooit als betaallink in een sms.',
 'vandaag 10:05','Proximus',
 'Proximus: uw factuur van € 52,00 staat open. Betaal...',
 E'Proximus: uw maandfactuur van €52,00 staat nog open. Betaal vóór 28 mei via {{link:0}} om onderbreking van uw verbinding te vermijden.',
 '[{"label":"Factuur betalen","real_url":"https://proximus-betalen.com/factuur","suspicious":true,"warning":"Link naar proximus-betalen.com, niet mijnproximus.be. Dit is een nepsite."}]'::jsonb,
 TRUE,
 '["Link naar proximus-betalen.com in plaats van mijnproximus.be","Proximus stuurt facturen via e-mail, niet als sms-betaallink","Dreigt met onderbreking om druk te zetten","Geloofwaardig bedrag maakt het lastiger te herkennen"]'::jsonb,
 '[]'::jsonb,
 'Dit is smishing. Proximus verstuurt factuurmeldingen via e-mail of Mijn Proximus — nooit als betaallink in een sms. Log altijd zelf in via mijnproximus.be.',
 364),

-- NL-BE / SMS D — Colruyt legitimate (sort 367; 365/366 waren al bezet)
('nl-BE','sms','both','advanced',
 'Colruyt','Colruyt',
 'Colruyt stuurt loyaliteitsberichten als u daarvoor toestemming gaf. Geen link, geen betaling.',
 'vandaag 08:03','Colruyt',
 'Colruyt: uw Xtra-punten zijn bijgewerkt. Uw saldo...',
 E'Colruyt: uw Xtra-saldo is bijgewerkt naar 340 punten. Bekijk uw voordelen in de Xtra-app of op xtra.be.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Geen link in het bericht — doorverwijzing naar de officiële app of website","Geen verzoek om te betalen of in te loggen","Alleen informatie over uw eigen puntensaldo","Consistent met wat u bij aanmelding heeft opgegeven"]'::jsonb,
 'Dit is een echt sms-bericht van Colruyt. Géén link, géén betaling gevraagd — alleen een saldo-update. Twijfelt u? Open de Xtra-app zelf.',
 367),

-- NL-BE / WhatsApp E — "ben jij dit?" phishing (sort 370)
('nl-BE','whatsapp','both','advanced',
 'Onbekend nummer','+32 4 89 33 57 12',
 'Een "is dit jij?"-link van een onbekend nummer leidt altijd naar account-overname via QR-code of verificatiecode.',
 'vandaag 21:09','Onbekend nummer',
 'Haha, ben jij dit?? 😂😂 Moet je echt eens kijken...',
 E'Haha, ben jij dit?? 😂😂 Moet je echt eens kijken:\n\n{{link:0}}\n\nIk was echt geschrokken haha',
 '[{"label":"Filmpje bekijken","real_url":"https://wa-video-check.com/kijk?id=BE-497","suspicious":true,"warning":"Link naar wa-video-check.com, geen officieel WhatsApp-domein. Klikken kan leiden tot account-overname."}]'::jsonb,
 TRUE,
 '["Onbekend nummer — geen bekende contactnaam","\"Ben jij dit?\" is een bekende phishingzin op WhatsApp","Link naar wa-video-check.com, niet whatsapp.com","Klikken leidt vaak naar QR-scan of code waarmee uw account wordt overgenomen"]'::jsonb,
 '[]'::jsonb,
 'Dit is een klassieke WhatsApp-phishinglink. Wie erop klikt, wordt gevraagd een QR-code te scannen of een verificatiecode in te voeren. Daarna nemen oplichters uw account over en sturen hetzelfde bericht naar al uw contacten.',
 370),

-- NL-BE / WhatsApp F — fake Payconiq (sort 371)
('nl-BE','whatsapp','both','advanced',
 'Onbekend nummer','+32 4 77 14 58 03',
 'Payconiq-links die u "moet bevestigen" zijn nep. Om geld te ontvangen hoeft u nooit op een link te klikken.',
 'vandaag 15:22','Onbekend nummer',
 'Hey! Ik wil je nog een bedragje doorsturen maar mijn app doet raar...',
 E'Hey! Ik wil je nog een bedragje doorsturen maar mijn Payconiq doet moeilijk. Kun je even bevestigen via {{link:0}}? Dan stuur ik het zo door. 🙏',
 '[{"label":"Payconiq bevestigen","real_url":"https://payconiq-bevestig.be/pay?ref=bc447","suspicious":true,"warning":"Link naar payconiq-bevestig.be, niet het echte payconiq.be. Dit is een nep-betaallink."}]'::jsonb,
 TRUE,
 '["Link naar payconiq-bevestig.be in plaats van payconiq.be","Om geld te ONTVANGEN hoeft u nooit op een link te klikken","Onbekend nummer — geen naam van afzender","Informele urgentie (\"doet moeilijk\") om snel te klikken"]'::jsonb,
 '[]'::jsonb,
 'Dit is Payconiq-fraude. De link gaat naar een nepsite. Om geld te ontvangen hoeft u nooit een link te bevestigen — dat werkt via de officiële Payconiq-app. Klik nooit op betaallinks van onbekende nummers.',
 371),

-- NL-BE / WhatsApp G — bpost real (sort 372)
('nl-BE','whatsapp','both','advanced',
 'bpost','bpost',
 'bpost gebruikt WhatsApp Business voor pakketmeldingen. Geen externe link, geen betaling.',
 'vandaag 11:48','bpost',
 'bpost: uw pakket BA987654321BE is onderweg...',
 E'bpost 📦\n\nUw pakket BA987654321BE is onderweg en wordt vandaag geleverd.\n\nGeschat tijdvak: 13:00–15:00\n\nOpvolgen via bpost.be of de bpost-app.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Geen externe link — doorverwijzing naar het officiële bpost.be","Geen betaling of inloggegevens gevraagd","Concrete bezorginformatie met trackingnummer en tijdvak","Zakelijke toon zonder urgentie of druk"]'::jsonb,
 'Dit is een echt WhatsApp Business-bericht van bpost. Geen link, geen betaling — alleen een statusmelding. Wil u het zeker weten? Zoek het trackingnummer op via bpost.be of de bpost-app.',
 372),

-- ==================== EN (British English) ====================

-- EN / SMS A — Barclays phishing (sort 362)
('en','sms','both','advanced',
 'Barclays','+44 7700 900 183',
 'Banks never send a link to log in via text message, even if the message sounds calm and professional.',
 'today 09:18','Barclays',
 'Barclays: we detected a sign-in attempt from an unknown...',
 E'Barclays: we detected a sign-in attempt from an unknown device. Not you? Temporarily lock your account at {{link:0}}',
 '[{"label":"Lock my account","real_url":"https://barclays-verify.net/lock","suspicious":true,"warning":"Link goes to barclays-verify.net, not barclays.co.uk. This is a fake site designed to steal your details."}]'::jsonb,
 TRUE,
 '["Link to barclays-verify.net instead of barclays.co.uk","Banks never send login links via text","Calm, professional tone is designed to lower your guard","Unknown-device alert is a classic smishing technique"]'::jsonb,
 '[]'::jsonb,
 'This is advanced smishing. barclays-verify.net is not a Barclays domain. Banks never send login links by text. Open the official Barclays app yourself or call the number on your card.',
 362),

-- EN / SMS B — Royal Mail customs phishing (sort 363)
('en','sms','both','advanced',
 'Royal Mail','+44 7700 900 374',
 'Royal Mail does not charge customs fees by text link. Any genuine customs charges are notified by post.',
 'today 14:33','Royal Mail',
 'Royal Mail: your parcel is held at customs. Pay £1.99...',
 E'Royal Mail: your parcel (GB006281234567) is held at customs. Release requires a customs fee of £1.99. Pay at {{link:0}} — delivery follows within 24 hours.',
 '[{"label":"Pay customs fee","real_url":"https://royalmail-parcel.co.uk/customs/release","suspicious":true,"warning":"Link to royalmail-parcel.co.uk, not royalmail.com. This is a fake site."}]'::jsonb,
 TRUE,
 '["Link to royalmail-parcel.co.uk instead of royalmail.com","Royal Mail notifies customs charges by post, not text","Small amount (£1.99) makes you pay without thinking","Specific tracking number gives a false sense of legitimacy"]'::jsonb,
 '[]'::jsonb,
 'This is smishing. Genuine customs charges are notified by a letter from HMRC or CITES — not a text link from the courier. Always check parcels at royalmail.com or in the Royal Mail app.',
 363),

-- EN / SMS C — O2 invoice phishing (sort 364)
('en','sms','both','advanced',
 'O2','+44 7700 900 892',
 'O2 sends bills by email or through the My O2 app — never as a payment link in a text.',
 'today 10:05','O2',
 'O2: your March bill of £35.00 is ready. Pay before...',
 E'O2: your March bill of £35.00 is ready. Pay before 31 March via {{link:0}} to avoid suspension of your service.',
 '[{"label":"Pay bill","real_url":"https://o2-invoices.com/pay/march","suspicious":true,"warning":"Link to o2-invoices.com, not my.o2.co.uk. This is a fake site."}]'::jsonb,
 TRUE,
 '["Link to o2-invoices.com instead of my.o2.co.uk","O2 sends bills by email, not as text payment links","Threatens service suspension to create urgency","Plausible amount makes it harder to spot"]'::jsonb,
 '[]'::jsonb,
 'This is smishing. O2 sends bill notifications by email or through the My O2 app — never as a payment link in a text. Always log in at my.o2.co.uk to view your bill.',
 364),

-- EN / SMS D — Amazon legitimate (sort 365)
('en','sms','both','advanced',
 'Amazon','AMAZON',
 'Amazon sends delivery updates by text if you opted in. No link to an external site, no payment required.',
 'today 08:03','Amazon',
 'Amazon: your order 204-7382910-4563821 will be delivered...',
 E'Amazon: your order 204-7382910-4563821 will be delivered today between 1pm–3pm. Track at amazon.co.uk/orders or in the Amazon app.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Directs you to amazon.co.uk — the official site","No payment or login credentials requested","Concrete delivery window and order number","No external link or pressure to click"]'::jsonb,
 'This is a genuine Amazon delivery update. Note: no suspicious link, no payment request — just a status update with a time window. If in doubt, go to amazon.co.uk yourself rather than following any link in a text.',
 365),

-- EN / WhatsApp E — "is this you?" phishing (sort 370)
('en','whatsapp','both','advanced',
 'Unknown number','+44 7700 900 671',
 'An "is this you?" link from an unknown number always leads to account takeover via a QR code or verification code.',
 'today 21:09','Unknown number',
 'Haha, is this you?? 😂😂 You have to see this...',
 E'Haha, is this you?? 😂😂 You have to see this:\n\n{{link:0}}\n\nI couldn''t believe it when I saw it lol',
 '[{"label":"Watch video","real_url":"https://wa-video-check.com/view?id=GB-447","suspicious":true,"warning":"Link to wa-video-check.com, not an official WhatsApp domain. Clicking can lead to account takeover."}]'::jsonb,
 TRUE,
 '["Unknown number — not a saved contact","\"Is this you?\" is a well-known WhatsApp phishing phrase","Link to wa-video-check.com, not whatsapp.com","Clicking typically leads to a QR code or verification code that hijacks your account"]'::jsonb,
 '[]'::jsonb,
 'This is a classic WhatsApp phishing link. Clicking it asks you to scan a QR code or enter a verification code — after which scammers take over your WhatsApp account and send the same message to all your contacts.',
 370),

-- EN / WhatsApp F — fake PayPal request (sort 371)
('en','whatsapp','both','advanced',
 'Unknown number','+44 7700 900 823',
 'PayPal links shared via WhatsApp are almost always fake. To receive money you never need to click a link.',
 'today 15:22','Unknown number',
 'Hey! I owe you a bit from last week but my PayPal is playing up...',
 E'Hey! I owe you a bit from last week but my PayPal is playing up. Can you just confirm via {{link:0}} and I''ll send it right over? 🙏',
 '[{"label":"Confirm PayPal","real_url":"https://paypal-request.co.uk/confirm?id=gb447","suspicious":true,"warning":"Link to paypal-request.co.uk, not paypal.com. This is a fake payment page that steals your details."}]'::jsonb,
 TRUE,
 '["Link to paypal-request.co.uk instead of paypal.com","You never need to click a link to RECEIVE money","Unknown number — no name shown","Social pressure (\"from last week\") to make you act quickly"]'::jsonb,
 '[]'::jsonb,
 'This is PayPal fraud. The link goes to a fake page designed to steal your bank or PayPal credentials. Receiving money via PayPal requires nothing from you — it just appears in your account. Never click payment links sent via WhatsApp.',
 371),

-- EN / WhatsApp G — Amazon delivery real (sort 372)
('en','whatsapp','both','advanced',
 'Amazon','Amazon',
 'Amazon uses WhatsApp Business for delivery notifications in some regions. No external link, no payment required.',
 'today 11:48','Amazon',
 'Amazon: your order 204-7382910-4563821 is on its way...',
 E'Amazon 📦\n\nYour order 204-7382910-4563821 is on its way and will be delivered today.\n\nEstimated time: 1pm–3pm\nDelivery address: London\n\nTrack at amazon.co.uk/orders or in the Amazon app.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["No external link — directs you to the official amazon.co.uk","No payment or credentials requested","Concrete delivery information with order number and time window","Professional, neutral tone with no pressure"]'::jsonb,
 'This is a genuine WhatsApp Business message from Amazon. Nothing is asked of you — it is just a status update. To verify, look up your order number at amazon.co.uk or in the Amazon app.',
 372),

-- ==================== FR (French) ====================

-- FR / SMS A — Crédit Agricole phishing (sort 362)
('fr','sms','both','advanced',
 'Crédit Agricole','+33 6 52 83 17 44',
 'Une banque n''envoie jamais de lien de connexion par SMS — même si le message semble calme et officiel.',
 'aujourd''hui 09:18','Crédit Agricole',
 'Crédit Agricole : nous avons détecté une connexion depuis...',
 E'Crédit Agricole : nous avons détecté une connexion depuis un appareil inconnu. Ce n''est pas vous ? Bloquez temporairement votre accès via {{link:0}}',
 '[{"label":"Bloquer mon accès","real_url":"https://ca-espace-client.com/bloquer","suspicious":true,"warning":"Lien vers ca-espace-client.com, pas credit-agricole.fr. C''est un site frauduleux."}]'::jsonb,
 TRUE,
 '["Lien vers ca-espace-client.com au lieu de credit-agricole.fr","Une banque n''envoie jamais de lien de connexion par SMS","Le ton calme et professionnel est conçu pour rassurer","L''alerte \"appareil inconnu\" est une technique classique de smishing"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing évolué. ca-espace-client.com n''est pas un domaine du Crédit Agricole. Votre banque ne vous envoie jamais de lien de connexion par SMS. Ouvrez toujours l''appli officielle ou appelez le numéro au dos de votre carte.',
 362),

-- FR / SMS B — La Poste customs phishing (sort 363)
('fr','sms','both','advanced',
 'La Poste','+33 6 71 44 28 93',
 'Les droits de douane sont notifiés par courrier officiel — jamais par lien SMS de la part du transporteur.',
 'aujourd''hui 14:33','La Poste',
 'La Poste : votre colis est retenu en douane. Réglez...',
 E'La Poste : votre colis (1A18006281234567) est retenu en douane. Sa libération nécessite €2,50 de frais de douane. Réglez sur {{link:0}} — livraison sous 24 h.',
 '[{"label":"Payer les frais","real_url":"https://laposte-suivi.com/douane/liberation","suspicious":true,"warning":"Lien vers laposte-suivi.com, pas laposte.fr. C''est un site frauduleux."}]'::jsonb,
 TRUE,
 '["Lien vers laposte-suivi.com au lieu de laposte.fr","Les droits de douane sont notifiés par courrier, pas par SMS","Petite somme (€2,50) pour vous faire payer sans réfléchir","Numéro de suivi inventé pour paraître crédible"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing. Les vrais droits de douane font l''objet d''un avis officiel des Douanes françaises — jamais d''un lien SMS du transporteur. Vérifiez toujours vos colis sur laposte.fr ou dans l''appli La Poste.',
 363),

-- FR / SMS C — Orange invoice phishing (sort 364)
('fr','sms','both','advanced',
 'Orange','+33 6 88 04 37 12',
 'Orange envoie les factures par e-mail ou via Mon Espace Orange — jamais comme lien de paiement par SMS.',
 'aujourd''hui 10:05','Orange',
 'Orange : votre facture de 49,90 € est disponible...',
 E'Orange : votre facture de 49,90 € (mai) est disponible. Réglez avant le 31 mai via {{link:0}} pour éviter la suspension de votre ligne.',
 '[{"label":"Payer ma facture","real_url":"https://orange-facture-client.com/payer/mai","suspicious":true,"warning":"Lien vers orange-facture-client.com, pas espaceclient.orange.fr. C''est un site frauduleux."}]'::jsonb,
 TRUE,
 '["Lien vers orange-facture-client.com au lieu de espaceclient.orange.fr","Orange envoie les factures par e-mail, pas comme lien SMS","Menace de suspension pour créer de l''urgence","Montant crédible difficile à identifier comme fraude"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing. Orange envoie les notifications de facture par e-mail ou via Mon Espace Orange — jamais comme lien de paiement dans un SMS. Connectez-vous toujours sur espaceclient.orange.fr pour voir votre facture.',
 364),

-- FR / SMS D — Amazon legitimate (sort 365)
('fr','sms','both','advanced',
 'Amazon','AMAZON',
 'Amazon envoie des SMS de livraison si vous avez donné votre accord. Aucun lien vers un site externe, aucun paiement requis.',
 'aujourd''hui 08:03','Amazon',
 'Amazon : votre commande 401-7382910-4563821 sera livrée...',
 E'Amazon : votre commande 401-7382910-4563821 sera livrée aujourd''hui entre 13 h et 15 h. Suivi sur amazon.fr/commandes ou dans l''appli Amazon.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Redirige vers amazon.fr — le site officiel","Aucun paiement ni identifiant demandé","Créneau de livraison concret et numéro de commande","Aucun lien externe ni pression pour cliquer"]'::jsonb,
 'C''est un vrai SMS de livraison d''Amazon. Remarquez : aucun lien suspect, aucun paiement demandé — juste une mise à jour de statut. En cas de doute, rendez-vous vous-même sur amazon.fr.',
 365),

-- FR / WhatsApp E — "c'est toi?" phishing (sort 370)
('fr','whatsapp','both','advanced',
 'Numéro inconnu','+33 6 74 03 94 21',
 'Un lien "c''est toi sur la vidéo ?" d''un numéro inconnu conduit toujours à une prise de contrôle de compte.',
 'aujourd''hui 21:09','Numéro inconnu',
 'Haha, c''est toi sur cette vidéo ?? 😂😂 Il faut vraiment...',
 E'Haha, c''est toi sur cette vidéo ?? 😂😂 Il faut vraiment que tu regardes ça :\n\n{{link:0}}\n\nJ''en revenais pas en voyant ça lol',
 '[{"label":"Voir la vidéo","real_url":"https://wa-video-check.com/voir?id=FR-447","suspicious":true,"warning":"Lien vers wa-video-check.com, pas un domaine WhatsApp officiel. Cliquer peut entraîner la prise de contrôle de votre compte."}]'::jsonb,
 TRUE,
 '["Numéro inconnu — pas un contact enregistré","\"C''est toi ?\" est une formule classique de phishing WhatsApp","Lien vers wa-video-check.com, pas whatsapp.com","Cliquer mène souvent à un QR code ou code de vérification qui permet de pirater votre compte"]'::jsonb,
 '[]'::jsonb,
 'C''est un lien de phishing WhatsApp classique. En cliquant, on vous demande de scanner un QR code ou d''entrer un code de vérification. Les escrocs prennent alors le contrôle de votre compte et envoient le même message à tous vos contacts.',
 370),

-- FR / WhatsApp F — fake Lydia (sort 371)
('fr','whatsapp','both','advanced',
 'Numéro inconnu','+33 6 58 14 77 03',
 'Les liens de paiement partagés via WhatsApp sont presque toujours faux. Pour recevoir de l''argent, vous n''avez jamais besoin de cliquer sur un lien.',
 'aujourd''hui 15:22','Numéro inconnu',
 'Coucou ! Je te dois encore un peu d''argent de la semaine...',
 E'Coucou ! Je te dois encore un peu d''argent de la semaine dernière mais mon appli Lydia bug. Tu peux confirmer via {{link:0}} et je te vire ça tout de suite ? 🙏',
 '[{"label":"Confirmer Lydia","real_url":"https://lydia-paiement.fr/confirmer?ref=fr447","suspicious":true,"warning":"Lien vers lydia-paiement.fr, pas lydia-app.com. C''est une fausse page de paiement."}]'::jsonb,
 TRUE,
 '["Lien vers lydia-paiement.fr au lieu de lydia-app.com","Pour RECEVOIR de l''argent, vous n''avez jamais besoin de cliquer sur un lien","Numéro inconnu — pas de nom d''expéditeur","Pression sociale (\"de la semaine dernière\") pour agir vite"]'::jsonb,
 '[]'::jsonb,
 'C''est une fraude Lydia. Le lien mène vers un faux site qui vole vos coordonnées bancaires. Recevoir de l''argent via Lydia ne demande rien de votre part — l''argent apparaît directement dans votre appli. Ne cliquez jamais sur des liens de paiement envoyés par WhatsApp.',
 371),

-- FR / WhatsApp G — Chronopost real (sort 372)
('fr','whatsapp','both','advanced',
 'Chronopost','Chronopost',
 'Chronopost utilise WhatsApp Business pour les notifications de livraison. Pas de lien externe, pas de paiement.',
 'aujourd''hui 11:48','Chronopost',
 'Chronopost: votre colis XP123456789FR est en cours...',
 E'Chronopost 📦\n\nVotre colis XP123456789FR est en cours de livraison et sera remis aujourd''hui.\n\nCréneau estimé : 13 h–15 h\nVille : Paris\n\nSuivi sur chronopost.fr ou dans l''appli Chronopost.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Pas de lien externe — redirige vers chronopost.fr officiel","Aucun paiement ni identifiant demandé","Informations concrètes : numéro de colis et créneau","Ton professionnel et neutre sans urgence"]'::jsonb,
 'C''est un vrai message WhatsApp Business de Chronopost. Aucune action n''est demandée — c''est juste une notification de statut. Pour vérifier, cherchez votre numéro de colis vous-même sur chronopost.fr.',
 372),

-- ==================== FR-BE (Belgian French) ====================

-- FR-BE / SMS A — ING phishing (sort 362)
('fr-BE','sms','both','advanced',
 'ING','+32 4 77 58 33 56',
 'ING n''envoie jamais de lien de connexion par SMS. Ouvrez toujours l''appli ING officielle.',
 'aujourd''hui 09:18','ING',
 'ING : nous avons détecté une connexion depuis un appareil...',
 E'ING : nous avons détecté une connexion depuis un appareil inconnu. Pas vous ? Bloquez temporairement votre compte via {{link:0}}',
 '[{"label":"Bloquer mon compte","real_url":"https://ing-verification.be/bloquer","suspicious":true,"warning":"Lien vers ing-verification.be, pas ing.be. C''est un site frauduleux."}]'::jsonb,
 TRUE,
 '["Lien vers ing-verification.be au lieu de ing.be","ING n''envoie jamais de lien de connexion par SMS","Alerte \"appareil inconnu\" conçue pour créer de la panique","Ton professionnel pour imiter une vraie notification bancaire"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing évolué. ing-verification.be n''est pas un domaine ING. ING n''envoie jamais de liens par SMS pour vous connecter. Ouvrez toujours l''appli ING officielle ou appelez le numéro au dos de votre carte.',
 362),

-- FR-BE / SMS B — bpost phishing (sort 363)
('fr-BE','sms','both','advanced',
 'bpost','+32 4 56 88 12 37',
 'Les vrais droits de douane font l''objet d''un avis officiel — jamais d''un lien SMS de la part du transporteur.',
 'aujourd''hui 14:33','bpost',
 'bpost : votre colis est retenu à la douane...',
 E'bpost : votre colis (BE201234567890) est retenu à la douane. Sa libération nécessite €2,35 de droits d''entrée. Réglez maintenant via {{link:0}}',
 '[{"label":"Payer les droits","real_url":"https://bpost-suivi.be/douane","suspicious":true,"warning":"Lien vers bpost-suivi.be, pas bpost.be. C''est un site frauduleux."}]'::jsonb,
 TRUE,
 '["Lien vers bpost-suivi.be au lieu de bpost.be","Les droits de douane font l''objet d''un avis officiel, pas d''un SMS","Petite somme (€2,35) pour vous faire payer rapidement","Faux numéro de suivi pour paraître légitime"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing. Les vrais droits d''entrée sont communiqués via un avis officiel — jamais par lien SMS. Vérifiez vos colis sur bpost.be ou dans l''appli bpost.',
 363),

-- FR-BE / SMS C — Proximus phishing (sort 364)
('fr-BE','sms','both','advanced',
 'Proximus','+32 4 99 07 44 81',
 'Proximus envoie les factures par e-mail ou via Mon Proximus — jamais comme lien de paiement dans un SMS.',
 'aujourd''hui 10:05','Proximus',
 'Proximus : votre facture de 52,00 € est en attente...',
 E'Proximus : votre facture mensuelle de €52,00 est en attente. Payez avant le 28 mai via {{link:0}} pour éviter toute interruption de service.',
 '[{"label":"Payer ma facture","real_url":"https://proximus-payer.be/facture","suspicious":true,"warning":"Lien vers proximus-payer.be, pas monproximus.be. C''est un site frauduleux."}]'::jsonb,
 TRUE,
 '["Lien vers proximus-payer.be au lieu de monproximus.be","Proximus envoie les factures par e-mail, pas via un SMS","Menace d''interruption pour créer de l''urgence","Montant crédible difficile à reconnaître comme fraude"]'::jsonb,
 '[]'::jsonb,
 'C''est du smishing. Proximus envoie les notifications de facturation par e-mail ou via Mon Proximus — jamais comme lien de paiement SMS. Connectez-vous toujours sur monproximus.be.',
 364),

-- FR-BE / SMS D — Amazon legitimate (sort 365)
('fr-BE','sms','both','advanced',
 'Amazon','AMAZON',
 'Amazon envoie des SMS de livraison si vous y avez consenti. Aucun lien externe, aucun paiement requis.',
 'aujourd''hui 08:03','Amazon',
 'Amazon : votre commande 401-7382910-4563821 sera livrée...',
 E'Amazon : votre commande 401-7382910-4563821 sera livrée aujourd''hui entre 13 h et 15 h. Suivi sur amazon.fr/commandes ou dans l''appli Amazon.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Redirige vers amazon.fr — le site officiel","Aucun paiement ni identifiant demandé","Créneau de livraison concret et numéro de commande","Aucun lien externe ni pression pour cliquer"]'::jsonb,
 'C''est un vrai SMS de livraison d''Amazon. Remarquez : aucun lien suspect, aucun paiement demandé — juste une mise à jour de statut. En cas de doute, rendez-vous vous-même sur amazon.fr.',
 365),

-- FR-BE / WhatsApp E — "c'est toi?" phishing (sort 370)
('fr-BE','whatsapp','both','advanced',
 'Numéro inconnu','+32 4 89 33 57 12',
 'Un lien "c''est toi sur la vidéo ?" d''un numéro inconnu conduit toujours à une prise de contrôle de compte.',
 'aujourd''hui 21:09','Numéro inconnu',
 'Haha, c''est bien toi sur cette vidéo ?? 😂😂 Tu dois vraiment...',
 E'Haha, c''est bien toi sur cette vidéo ?? 😂😂 Tu dois vraiment regarder ça :\n\n{{link:0}}\n\nJ''en revenais pas lol',
 '[{"label":"Voir la vidéo","real_url":"https://wa-video-check.com/voir?id=BE-497","suspicious":true,"warning":"Lien vers wa-video-check.com, pas un domaine WhatsApp officiel. Cliquer peut mener à la prise de contrôle de votre compte."}]'::jsonb,
 TRUE,
 '["Numéro inconnu — pas un contact enregistré","\"C''est toi ?\" est une formule classique de phishing WhatsApp","Lien vers wa-video-check.com, pas whatsapp.com","Cliquer mène souvent à un QR code ou code de vérification qui permet de pirater votre compte"]'::jsonb,
 '[]'::jsonb,
 'C''est un lien de phishing WhatsApp classique. En cliquant, on vous demande de scanner un QR code ou d''entrer un code de vérification. Les escrocs prennent alors le contrôle de votre compte et envoient le même message à tous vos contacts.',
 370),

-- FR-BE / WhatsApp F — fake Payconiq French (sort 371)
('fr-BE','whatsapp','both','advanced',
 'Numéro inconnu','+32 4 77 14 58 03',
 'Les liens Payconiq partagés via WhatsApp sont presque toujours faux. Pour recevoir de l''argent, vous n''avez jamais besoin de cliquer sur un lien.',
 'aujourd''hui 15:22','Numéro inconnu',
 'Salut ! Je te dois encore un peu d''argent de la semaine...',
 E'Salut ! Je te dois encore un peu d''argent de la semaine passée mais mon Payconiq bug. Tu peux confirmer via {{link:0}} et je te transfère ça tout de suite ? 🙏',
 '[{"label":"Confirmer Payconiq","real_url":"https://payconiq-payer.be/confirmer?ref=be447","suspicious":true,"warning":"Lien vers payconiq-payer.be, pas payconiq.be. C''est un faux lien de paiement."}]'::jsonb,
 TRUE,
 '["Lien vers payconiq-payer.be au lieu de payconiq.be","Pour RECEVOIR de l''argent, vous n''avez jamais besoin de cliquer","Numéro inconnu — pas de nom d''expéditeur","Pression sociale pour agir vite"]'::jsonb,
 '[]'::jsonb,
 'C''est une fraude Payconiq. Le lien mène vers un faux site. Recevoir de l''argent via Payconiq ne demande rien de votre part — cela apparaît dans votre appli. Ne cliquez jamais sur des liens de paiement envoyés via WhatsApp.',
 371),

-- FR-BE / WhatsApp G — bpost real French (sort 372)
('fr-BE','whatsapp','both','advanced',
 'bpost','bpost',
 'bpost utilise WhatsApp Business pour les notifications de colis. Pas de lien externe, pas de paiement.',
 'aujourd''hui 11:48','bpost',
 'bpost: votre colis BA987654321BE est en route...',
 E'bpost 📦\n\nVotre colis BA987654321BE est en route et sera livré aujourd''hui.\n\nCréneau estimé : 13 h–15 h\n\nSuivi sur bpost.be ou dans l''appli bpost.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Pas de lien externe — redirige vers bpost.be officiel","Aucun paiement ni identifiant demandé","Informations concrètes avec numéro de colis et créneau","Ton professionnel sans urgence"]'::jsonb,
 'C''est un vrai message WhatsApp Business de bpost. Aucune action n''est demandée — juste une notification de statut. Pour vérifier, cherchez votre numéro de colis sur bpost.be ou dans l''appli bpost.',
 372),

-- ==================== DE (German) ====================

-- DE / SMS A — Sparkasse phishing (sort 362)
('de','sms','both','advanced',
 'Sparkasse','+49 157 7388 1427',
 'Eine Bank sendet niemals einen Anmeldelink per SMS — auch wenn die Nachricht ruhig und professionell klingt.',
 'heute 09:18','Sparkasse',
 'Sparkasse: wir haben einen Anmeldeversuch von einem unbekannten...',
 E'Sparkasse: wir haben einen Anmeldeversuch von einem unbekannten Gerät erkannt. Nicht Sie? Sperren Sie Ihren Zugang vorübergehend über {{link:0}}',
 '[{"label":"Zugang sperren","real_url":"https://sparkasse-login.com/sperren","suspicious":true,"warning":"Link zu sparkasse-login.com, nicht sparkasse.de. Das ist eine gefälschte Website."}]'::jsonb,
 TRUE,
 '["Link zu sparkasse-login.com statt sparkasse.de","Banken senden niemals Anmeldelinks per SMS","Ruhiger, professioneller Ton soll das Misstrauen senken","Warnung vor \"unbekanntem Gerät\" ist ein klassischer Smishing-Trick"]'::jsonb,
 '[]'::jsonb,
 'Das ist fortgeschrittenes Smishing. sparkasse-login.com ist keine Sparkassen-Domain. Ihre Bank schickt niemals Anmeldelinks per SMS. Öffnen Sie immer die offizielle Sparkassen-App oder rufen Sie die Nummer auf Ihrer Karte an.',
 362),

-- DE / SMS B — DHL Zoll phishing (sort 363)
('de','sms','both','advanced',
 'DHL','+49 157 7388 5231',
 'Echte Zollgebühren werden per Brief des Zollamts mitgeteilt — niemals per SMS-Link des Paketdienstleisters.',
 'heute 14:33','DHL',
 'DHL: Ihre Sendung liegt beim Zoll. Zur Freigabe...',
 E'DHL: Ihre Sendung (1Z999AA10123456784) liegt beim Zoll. Zur Freigabe werden €2,10 Zollgebühren benötigt. Bezahlen Sie auf {{link:0}} — Zustellung morgen.',
 '[{"label":"Zollgebühr bezahlen","real_url":"https://dhl-zoll-de.com/freigabe","suspicious":true,"warning":"Link zu dhl-zoll-de.com statt dhl.de oder dhl.com. Das ist eine gefälschte Website."}]'::jsonb,
 TRUE,
 '["Link zu dhl-zoll-de.com statt dhl.de","Echte Zollgebühren kommen per Brief, nicht per SMS","Kleiner Betrag (€2,10) — man zahlt ohne nachzudenken","Konkrete Sendungsnummer erweckt falsches Vertrauen"]'::jsonb,
 '[]'::jsonb,
 'Das ist Smishing. Echte Zollgebühren werden durch das Zollamt per Brief mitgeteilt — nicht per SMS-Link des Paketdienstleisters. Überprüfen Sie Sendungen immer auf dhl.de oder in der DHL-App.',
 363),

-- DE / SMS C — T-Mobile invoice phishing (sort 364)
('de','sms','both','advanced',
 'T-Mobile','+49 157 7388 9032',
 'T-Mobile verschickt Rechnungen per E-Mail oder über Mein T-Mobile — niemals als Zahlungslink per SMS.',
 'heute 10:05','T-Mobile',
 'T-Mobile: Ihre Rechnung über 44,95 € steht bereit...',
 E'T-Mobile: Ihre Rechnung über €44,95 (Mai) steht bereit. Bezahlen Sie bis 31. Mai über {{link:0}}, um eine Sperrung Ihres Anschlusses zu vermeiden.',
 '[{"label":"Rechnung bezahlen","real_url":"https://t-mobile-rechnung.com/bezahlen/mai","suspicious":true,"warning":"Link zu t-mobile-rechnung.com statt meinmagenta.de. Das ist eine gefälschte Website."}]'::jsonb,
 TRUE,
 '["Link zu t-mobile-rechnung.com statt meinmagenta.de","T-Mobile verschickt Rechnungen per E-Mail, nicht per SMS","Androhung der Sperrung erzeugt Druck","Glaubwürdiger Betrag erschwert die Erkennung"]'::jsonb,
 '[]'::jsonb,
 'Das ist Smishing. T-Mobile verschickt Rechnungsbenachrichtigungen per E-Mail oder über Mein T-Mobile — niemals als Zahlungslink per SMS. Melden Sie sich immer selbst auf meinmagenta.de an.',
 364),

-- DE / SMS D — Amazon legitimate (sort 365)
('de','sms','both','advanced',
 'Amazon','AMAZON',
 'Amazon verschickt SMS-Lieferbenachrichtigungen, wenn Sie zugestimmt haben. Kein Link zu einer externen Website, keine Zahlung erforderlich.',
 'heute 08:03','Amazon',
 'Amazon: Ihre Bestellung 302-7382910-4563821 wird...',
 E'Amazon: Ihre Bestellung 302-7382910-4563821 wird heute zwischen 13:00 und 15:00 Uhr geliefert. Tracking auf amazon.de/bestellungen oder in der Amazon-App.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Weiterleitung zu amazon.de — die offizielle Website","Keine Zahlung oder Zugangsdaten verlangt","Konkretes Lieferzeitfenster und Bestellnummer","Kein externer Link, kein Druck zum Klicken"]'::jsonb,
 'Das ist eine echte Lieferbenachrichtigung von Amazon. Beachten Sie: kein verdächtiger Link, keine Zahlungsaufforderung — nur ein Status-Update. Rufen Sie im Zweifelsfall amazon.de selbst auf.',
 365),

-- DE / WhatsApp E — "Bist du das?" phishing (sort 370)
('de','whatsapp','both','advanced',
 'Unbekannte Nummer','+49 157 7388 6721',
 'Ein "Bist du das im Video?"-Link von einer unbekannten Nummer führt immer zu einer Kontoübernahme via QR-Code oder Bestätigungscode.',
 'heute 21:09','Unbekannte Nummer',
 'Haha, bist du das im Video?? 😂😂 Du musst das wirklich sehen...',
 E'Haha, bist du das im Video?? 😂😂 Du musst das wirklich sehen:\n\n{{link:0}}\n\nIch konnte es nicht glauben, als ich es gesehen hab lol',
 '[{"label":"Video ansehen","real_url":"https://wa-video-check.com/ansehen?id=DE-447","suspicious":true,"warning":"Link zu wa-video-check.com, keine offizielle WhatsApp-Domain. Klicken kann zur Kontoübernahme führen."}]'::jsonb,
 TRUE,
 '["Unbekannte Nummer — kein gespeicherter Kontakt","\"Bist du das?\" ist ein bekannter WhatsApp-Phishing-Satz","Link zu wa-video-check.com, nicht whatsapp.com","Klicken führt oft zu QR-Code oder Bestätigungscode, mit dem Ihr Konto übernommen wird"]'::jsonb,
 '[]'::jsonb,
 'Das ist ein klassischer WhatsApp-Phishing-Link. Wer klickt, wird aufgefordert, einen QR-Code zu scannen oder einen Bestätigungscode einzugeben — danach übernehmen Betrüger Ihr WhatsApp-Konto und schicken dieselbe Nachricht an alle Ihre Kontakte.',
 370),

-- DE / WhatsApp F — fake PayPal (sort 371)
('de','whatsapp','both','advanced',
 'Unbekannte Nummer','+49 157 7388 8834',
 'PayPal-Links über WhatsApp sind fast immer gefälscht. Um Geld zu EMPFANGEN, müssen Sie niemals auf einen Link klicken.',
 'heute 15:22','Unbekannte Nummer',
 'Hey! Ich schulde dir noch etwas von letzter Woche...',
 E'Hey! Ich schulde dir noch etwas von letzter Woche, aber mein PayPal spinnt gerade. Kannst du kurz über {{link:0}} bestätigen? Dann überweise ich es sofort. 🙏',
 '[{"label":"PayPal bestätigen","real_url":"https://paypal-zahlung.de/bestaetigen?id=de447","suspicious":true,"warning":"Link zu paypal-zahlung.de statt paypal.com. Das ist eine gefälschte Zahlungsseite."}]'::jsonb,
 TRUE,
 '["Link zu paypal-zahlung.de statt paypal.com","Um Geld zu EMPFANGEN, müssen Sie niemals auf einen Link klicken","Unbekannte Nummer — kein Absendername","Sozialer Druck (\"von letzter Woche\") zum schnellen Handeln"]'::jsonb,
 '[]'::jsonb,
 'Das ist PayPal-Betrug. Der Link führt zu einer gefälschten Seite, die Ihre Bankdaten stiehlt. Geld via PayPal zu empfangen erfordert keine Aktion von Ihnen — es erscheint einfach in Ihrem Konto. Klicken Sie niemals auf Zahlungslinks, die per WhatsApp gesendet wurden.',
 371),

-- DE / WhatsApp G — DHL real (sort 372)
('de','whatsapp','both','advanced',
 'DHL Express','DHL Express',
 'DHL nutzt WhatsApp Business für Lieferbenachrichtigungen. Kein externer Link, keine Zahlung erforderlich.',
 'heute 11:48','DHL Express',
 'DHL Express: Ihre Sendung 1Z999AA10123456784 ist unterwegs...',
 E'DHL Express 📦\n\nIhre Sendung 1Z999AA10123456784 ist unterwegs und wird heute zugestellt.\n\nGeschätzte Lieferzeit: 14:00–16:00 Uhr\nZielort: Berlin\n\nTracking auf dhl.de oder in der DHL-App.',
 '[]'::jsonb,
 FALSE,
 '[]'::jsonb,
 '["Kein externer Link — Weiterleitung zu dhl.de","Keine Zahlung oder Zugangsdaten verlangt","Konkrete Lieferinformationen mit Sendungsnummer und Zeitfenster","Professioneller, neutraler Ton ohne Druck"]'::jsonb,
 'Das ist eine echte WhatsApp-Business-Nachricht von DHL. Es wird nichts von Ihnen verlangt — nur eine Status-Benachrichtigung. Zur Überprüfung suchen Sie Ihre Sendungsnummer selbst auf dhl.de oder in der DHL-App.',
 372);

