-- ============================================================
-- en-US: eigen Amerikaanse set. Kopie van de Britse (en) rijen,
-- daarna geamerikaniseerd via gecoördineerde REPLACE (merk + echt
-- domein + lookalike samen): HMRC→IRS, Barclays→Chase, Royal Mail→USPS,
-- NHS→Medicare, £→$, .co.uk→.com, Amerikaanse spelling. Zo is en-US een
-- volwaardige aparte taal met eigen DB-inhoud, net als nl-BE/fr-BE.
-- ============================================================
INSERT INTO examples (locale, audience, channel, sender, subject, body, annotations, sort_order)
SELECT 'en-US', audience, channel, sender, subject, body, annotations, sort_order
FROM examples WHERE locale = 'en';

INSERT INTO inbox_messages
  (locale, audience, channel, category, sender_name, sender_address, sender_note,
   received_label, subject, preview, body, links, attachments, is_phishing,
   red_flags, green_flags, explanation, sort_order, difficulty, active)
SELECT 'en-US', audience, channel, category, sender_name, sender_address, sender_note,
   received_label, subject, preview, body, links, attachments, is_phishing,
   red_flags, green_flags, explanation, sort_order, difficulty, active
FROM inbox_messages WHERE locale = 'en';

UPDATE examples SET
  sender = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  subject = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(subject, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  body = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(body, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  annotations = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(annotations::text, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize')::jsonb
WHERE locale = 'en-US';

UPDATE inbox_messages SET
  sender_name = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender_name, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  sender_address = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender_address, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  sender_note = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender_note, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  subject = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(subject, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  preview = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(preview, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  body = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(body, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  explanation = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(explanation, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize'),
  links = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(links::text, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize')::jsonb,
  red_flags = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(red_flags::text, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize')::jsonb,
  green_flags = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(green_flags::text, 'hmrc-refund.co.uk', 'irs-refund.com'), 'hmrc.gov.uk', 'irs.gov'), 'my-barclays.secure-review.co.uk', 'my-chase.secure-review.com'), 'barclays-secure-login.com', 'chase-secure-login.com'), 'barclays.co.uk', 'chase.com'), 'royalmail-parcel.co.uk', 'usps-parcel.com'), 'nhs-verify.org', 'medicare-verify.org'), 'nhs.uk', 'medicare.gov'), 'amazon.co.uk', 'amazon.com'), 'paypal.co.uk', 'paypal.com'), 'boots.co.uk', 'cvs.com'), 'camden.gov.uk', 'camden.gov'), 'kestrel-access.co.uk', 'kestrel-access.com'), 'kestrel.co.uk', 'kestrel.com'), 'secure-review.co.uk', 'secure-review.com'), 'HM Revenue &amp; Customs', 'Internal Revenue Service'), 'HM Revenue & Customs', 'Internal Revenue Service'), 'HMRC', 'IRS'), 'BARCLAYS', 'CHASE'), 'Barclays', 'Chase'), 'Royal Mail', 'USPS'), 'NHS Digital', 'Medicare'), 'NHS', 'Medicare'), 'Boots', 'CVS'), 'council tax', 'property tax'), 'Council Tax', 'Property tax'), '.co.uk', '.com'), 'gov.uk', 'usa.gov'), '£', '$'), 'colour', 'color'), 'favourite', 'favorite'), 'organisation', 'organization'), 'licence', 'license'), 'Licence', 'License'), 'apologise', 'apologize'), 'recognise', 'recognize')::jsonb
WHERE locale = 'en-US';

-- en-US polish: 24u→12u tijden, US-telefoon/plaats/idioom, mum→mom.
UPDATE inbox_messages SET
  sender_name = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender_name, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  sender_address = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender_address, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  sender_note = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender_note, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  subject = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(subject, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  preview = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(preview, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  body = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(body, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  explanation = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(explanation, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  links = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(links::text, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM')::jsonb,
  red_flags = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(red_flags::text, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM')::jsonb,
  green_flags = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(green_flags::text, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM')::jsonb
WHERE locale = 'en-US';

UPDATE inbox_messages SET
  subject = regexp_replace(regexp_replace(subject, '\ymum\y','mom','g'), '\yMum\y','Mom','g'),
  preview = regexp_replace(regexp_replace(preview, '\ymum\y','mom','g'), '\yMum\y','Mom','g'),
  body = regexp_replace(regexp_replace(body, '\ymum\y','mom','g'), '\yMum\y','Mom','g')
WHERE locale = 'en-US';

UPDATE examples SET
  sender = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  subject = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(subject, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  body = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(body, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM'),
  annotations = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(annotations::text, '020 7946 0123', '(212) 555-0123'), '020 7946 0555', '(212) 555-0177'), 'Premier Inn London County Hall', 'Hampton Inn Chicago Downtown'), 'Premier Inn', 'Hampton Inn'), 'London County Hall', 'Chicago Downtown'), 'London, United Kingdom', 'Chicago, United States'), '12 High Street, London', '12 Main Street, Chicago, IL'), 'High Street', 'Main Street'), 'Oakwood Surgery', 'Oakwood Family Clinic'), 'ready to collect', 'ready for pickup'), 'collection slip', 'pickup slip'), 'rearrange', 'reschedule'), 'working days', 'business days'), 'New holiday page', 'New time-off page'), 'holiday page', 'time-off page'), 'holiday', 'vacation'), '2025-2026 tax year', '2025 tax year'), '2025/2026 tax year', '2025 tax year'), 'Friday 15 May', 'Friday, May 15'), 'Sunday 17 May', 'Sunday, May 17'), '15 May', 'May 15'), '17 May', 'May 17'), '05:55', '5:55 AM'), '06:47', '6:47 AM'), '10:15', '10:15 AM'), '10:40', '10:40 AM'), '17:30', '5:30 PM'), '17:00', '5:00 PM'), '21:58', '9:58 PM'), '19:39', '7:39 PM'), '14:00', '2:00 PM'), '15:00', '3:00 PM'), '12:00', '12:00 PM'), '9:15', '9:15 AM')::jsonb
WHERE locale = 'en-US';

-- en-US polish 2: Amerikaanse afsluitingen/termen.
UPDATE inbox_messages SET
  sender_name = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender_name, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell'),
  sender_note = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(sender_note, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell'),
  subject = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(subject, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell'),
  preview = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(preview, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell'),
  body = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(body, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell'),
  explanation = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(explanation, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell'),
  links = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(links::text, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell')::jsonb,
  red_flags = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(red_flags::text, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell')::jsonb,
  green_flags = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(green_flags::text, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell')::jsonb
WHERE locale = 'en-US';

UPDATE examples SET
  body = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(body, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell'),
  annotations = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(annotations::text, 'Kind regards', 'Best regards'), 'Yours faithfully', 'Sincerely'), 'Yours sincerely', 'Sincerely'), 'Personal Tax Account', 'online IRS account'), 'by post', 'by mail'), 'usa.gov', 'irs.gov'), 'cancelled', 'canceled'), 'Cancelled', 'Canceled'), 'mobile phone', 'cell phone'), 'mobile number', 'cell number'), 'your mobile', 'your cell')::jsonb
WHERE locale = 'en-US';

-- en-US brand conversion: O2 → AT&T for SMS telecom phishing (sort 364)
UPDATE inbox_messages SET
  sender_name = REPLACE(sender_name, 'O2', 'AT&T'),
  sender_note = REPLACE(REPLACE(sender_note, 'O2 sends bills by email or through the My O2 app — never as a payment link in a text.', 'AT&T sends bills by email or through the myAT&T app — never as a payment link in a text.'), 'O2', 'AT&T'),
  body = REPLACE(REPLACE(REPLACE(body, 'O2: your March bill of £35.00 is ready. Pay before 31 March via {{link:0}} to avoid suspension of your service.', 'AT&T: your March bill of $35.00 is ready. Pay before March 31 via {{link:0}} to avoid suspension of your service.'), 'O2', 'AT&T'), '£', '$'),
  preview = REPLACE(REPLACE(preview, 'O2', 'AT&T'), '£', '$'),
  subject = REPLACE(subject, 'O2', 'AT&T'),
  links = REPLACE(REPLACE(REPLACE(links::text, 'o2-invoices.com', 'att-invoices.com'), 'my.o2.co.uk', 'myatt.com'), 'O2', 'AT&T')::jsonb,
  red_flags = REPLACE(REPLACE(REPLACE(red_flags::text, 'o2-invoices.com', 'att-invoices.com'), 'my.o2.co.uk', 'myatt.com'), 'O2', 'AT&T')::jsonb,
  explanation = REPLACE(REPLACE(REPLACE(explanation, 'O2 sends bill notifications by email or through the My O2 app — never as a payment link in a text. Always log in at my.o2.co.uk to view your bill.', 'AT&T sends bill notifications by email or through the myAT&T app — never as a payment link in a text. Always log in at myatt.com to view your bill.'), 'O2', 'AT&T'), 'my.o2.co.uk', 'myatt.com')
WHERE locale = 'en-US' AND channel = 'sms' AND sort_order = 364;
